### ISSUE TITLE
Mapping object locations from habitat to blender

### ISSUE THREAD

**Issue by Ainaz99** [facebookresearch/habitat-sim#1004]
## ❓ Questions and Help
Hi. Happy new year :)
I'm trying to add some objects to a replica scene, both in habitat and blender. I know how to map the coordinate system between them. Object rotations seem to be matching, but there is some discrepancy between object locations in habitat and blender. I'm using `sim.set_translation(object_id)` in habitat and `obj.location` in blender which are perfectly matching after mapping the coordinate system. Is there any other way to set the object location in habitat? 
I'm attaching some photos from both habitat and blender (from left to right, the first image is from habitat, the second is from blender and they are merged in the third image).
Thanks for your help.

![7](https://user-images.githubusercontent.com/69212889/103487441-c79cf280-4e1a-11eb-9c37-de2ab4ceef8b.png)
![12](https://user-images.githubusercontent.com/69212889/103487445-ccfa3d00-4e1a-11eb-91c3-08cf995ef511.png)
![28](https://user-images.githubusercontent.com/69212889/103487447-d1bef100-4e1a-11eb-89b1-927c63eb6186.png)

**Comment by aclegg3** [comment]
Hey @Ainaz99,

Great debugging images. thanks. It looks like your Blender objects are not centered at their local origins. As in this image, the object origin and transformation pivot is at the edge of the box. 

<img src="https://user-images.githubusercontent.com/1445143/103556395-92b68d00-4e66-11eb-9d2e-86b71cdacc89.png" width="200">

When an object is loaded into Habitat, we move the origin to be coincident with the object's center of mass (COM) for physics simulation purposes (computed from the center of the object's bounding box if not provided in the config file). 

**You have a couple choices for handling this:**

You can reset the origin of your Blender reference objects with right click as shown below:
<img src="https://user-images.githubusercontent.com/1445143/103556693-02c51300-4e67-11eb-9cdd-04791100a625.png" width="800">

You can manually set the object's COM (e.g. via the object config file as described [here](https://aihabitat.org/docs/habitat-sim/attributesJSON.html#object-attributes)). Note that this approach will result in physics simulation artifacts and should be used only for kinematic objects.

You can re-export your objects from Blender centered at their COM using the Blender operation shown here and then use the edited object assets in Habitat:
![image](https://user-images.githubusercontent.com/1445143/103557334-e1185b80-4e67-11eb-8b03-56d978ee0fba.png)

Hope this helps. 👍

**Comment by Ainaz99** [comment]
Changing the origin in Blender worked! Thanks a lot @aclegg3 .

**Comment by qingchu123** [comment]
now i try to map the object in blender,but i encounter some problem, can you @Ainaz99 give some suggestion on how to map the coordinate system between them?
