### ISSUE TITLE
Question about request datasets

### ISSUE THREAD

**Issue by GracefulMan** [facebookresearch/habitat-sim#1035]
## ❓ Questions and Help
Hello,Thanks very much for providing such a good simulation environment! I want to use this repo for my research experiments and i had sent a email for requesting dataset according to the requirements, but until now i still don't get reply.I want to ask about how long it will take to receive the data? thanks!!!

**Comment by dhruvbatra** [comment]
We don't release the data and don't control that process. So can't say.
