### ISSUE TITLE
How to register an action that determines the body moving and head direction independently?

### ISSUE THREAD

**Issue by PeihaoChen** [facebookresearch/habitat-sim#1037]
## ❓ Questions and Help
I want to build an agent that can determine the body moving and head direction independently (ie, moving the body and the head forward, and turn only the head to the left at the same time).

I see the MoveForwardAndSpin action example that can move forward and then spin the agent. 
However, if I set the `body_action=True`, the body will move forward and spin together with the sensor (i.e., changing the position and rotation of both body and sensor). 
If I set the `body_action=False`, the agent will not change the position (ie, the body's position and rotation will not be changed). 
What I expect is that the body moves forward (ie, changing the body's position while keeping the body's rotation) and the sensor moves forward and spins to the left (ie, changing the position because it moves forward with the body and changing the rotation because the agent's head turns left).

https://github.com/facebookresearch/habitat-sim/blob/6c124dbe09f89ea64f9d94982ab0e41110edad45/examples/tutorials/new_actions.py#L38-L53

I knew that I can implement the `MoveForward` and then 'LookLeft' actions to achieve my goal. However, I wonder is it possible to achieve this goal within one action such that I only need to implement the step function once?

Many thanks!

**Comment by erikwijmans** [comment]
This isn't something we support currently and likely won't at the habitat sim level as a single action.  At the habitat API level, this can be done via the task action API (https://github.com/facebookresearch/habitat-lab/blob/master/habitat/tasks/nav/nav.py#L1041).

You can do this either by directly manipulating the agent state or by calling forward then left as you said but using just the agent.act method to avoid rendering twice.
