### ISSUE TITLE
Simulator remove_object method isn't deallocating the physObjectId

### ISSUE THREAD

**Issue by NaveenVSrinivasan** [facebookresearch/habitat-sim#1053]
## 🐛 Bug

When I call remove_object on a given object_id, the object is removed from the scene but the id is not appropriately deallocated and scrubbed. Thus, in downstream methods the simulator stops at the assertIDValidity method in PhysicsManager.h because it catches that the count of an object_id in existingObjects_ is 0.

## System Info

ENVIRONMENT INFO:
Platform: Linux-5.4.0-1025-aws-x86_64-with-debian-buster-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.9
Mac version:
Python version: 3.6.12
Architecture: 64bit
Win version:
System OS: Linux
Release: 5.4.0-1025-aws
Version: #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020
Operational System: linux
GCC version: b'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\n'
CMAKE version: b'cmake version 3.19.3\n'
NVIDIA-SMI: b'Wed Jan 27 16:42:13 2021       \n+-----------------------------------------------------------------------------+\n| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |\n|-------------------------------+----------------------+----------------------+\n| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n|                               |                      |               MIG M. |\n|===============================+======================+======================|\n|   0  Tesla K80           On   | 00000000:00:17.0 Off |                    0 |\n| N/A   28C    P0    53W / 149W |   3545MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   1  Tesla K80           On   | 00000000:00:18.0 Off |                    0 |\n| N/A   20C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   2  Tesla K80           On   | 00000000:00:19.0 Off |                    0 |\n| N/A   23C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   3  Tesla K80           On   | 00000000:00:1A.0 Off |                    0 |\n| N/A   21C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   4  Tesla K80           On   | 00000000:00:1B.0 Off |                    0 |\n| N/A   23C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   5  Tesla K80           On   | 00000000:00:1C.0 Off |                    0 |\n| N/A   20C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   6  Tesla K80           On   | 00000000:00:1D.0 Off |                    0 |\n| N/A   24C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n|   7  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |\n| N/A   22C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n'

Conda packages versions:
(kondo) srinivasann@ip-172-31-59-134:~/projects/habitat-sim/habitat_sim/utils$ conda list
# packages in environment at /home/srinivasann/miniconda3/envs/kondo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
absl-py                   0.11.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bullet                    2.88            py36hb3f55d8_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
cmake                     3.19.3               h4547794_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dataclasses               0.8                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    4.3.1                hca11adc_2    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.8.1                he1b5a44_0    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.12             pyhd8ed1ab_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
grpcio                    1.34.0                   pypi_0    pypi
gym                       0.10.9                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
habitat                   0.1.6                     dev_0    <develop>
habitat-sim               0.1.6                    pypi_0    pypi
headless                  1.0                           0    aihabitat
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10                     pypi_0    pypi
ifcfg                     0.21                     pypi_0    pypi
imageio                   2.9.0                      py_0    conda-forge
imageio-ffmpeg            0.4.3              pyhd8ed1ab_0    conda-forge
importlib-metadata        3.3.0                    pypi_0    pypi
ipykernel                 5.3.4            py36h5ca1d4c_0    anaconda
ipython                   7.16.1           py36h95af2a2_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py36h5fab9bb_2    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.0            py36h5fab9bb_1    conda-forge
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuv                     1.40.0               h7f98852_0    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
llvmlite                  0.35.0                   pypi_0    pypi
lmdb                      1.0.0                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markdown                  3.3.3                    pypi_0    pypi
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36h5fdd944_1    conda-forge
mock                      4.0.3                    pypi_0    pypi
moviepy                   2.0.0.dev2               pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numba                     0.52.0           py36h284efc9_0    conda-forge
numpy                     1.19.4           py36h8732dcd_1    conda-forge
numpy-quaternion          2020.11.2.17.0.49          pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.4.0.46                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py36h10ecd5c_0    conda-forge
pip                       21.0               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.13             pyha770c72_0    conda-forge
protobuf                  4.0.0rc2                 pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyglet                    1.5.11                   pypi_0    pypi
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.6.12               hcff3b4d_2
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     21.0.1           py36h81c33ee_0    conda-forge
quaternion                2020.9.5.14.42.2  py36h68bb277_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rhash                     1.4.1                h7f98852_0    conda-forge
rsa                       4.6                      pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
shapely                   1.7.1            py36h15bcdef_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tb-nightly                2.5.0a20201217           pypi_0    pypi
tensorboard               1.13.1                   pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tk                        8.6.10               h21135ba_1    conda-forge
torch                     1.7.1                    pypi_0    pypi
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
tree                      1.8.0                h516909a_1    conda-forge
trimesh                   3.9.1              pyhd3deb0d_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
withbullet                1.0                           0    aihabitat
x264                      1!161.3030           h7f98852_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxcursor           1.2.0                h516909a_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxinerama          1.1.4             hf484d3e_1000    conda-forge
xorg-libxrandr            1.5.2                h516909a_1    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-randrproto           1.5.0             h516909a_1001    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yacs                      0.1.8                    pypi_0    pypi
zeromq                    4.3.3                h58526e2_3    conda-forge
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge

**Comment by jturner65** [comment]
Hi

Can you share a minimal python script that demonstrates the issue you are having?

**Comment by NaveenVSrinivasan** [comment]
Resolved! The issue was on my end. The error was caused when an objectId was erroneously cached after an object was removed and was passed to a sim call of getInitializationTemplate().
