### ISSUE TITLE
How to test the testing files in tests/ ?

### ISSUE THREAD

**Issue by ZhuFengdaaa** [facebookresearch/habitat-sim#1067]
## ❓ Questions and Help
I want to test some features of the functions defined in `tests/`, such as the `test_sim_multiagent_move_and_reset` in the `test_simulator.py`. But I cannot find any documentation or code that refers to these files. 

Could anyone teach me how to use that, please?

**Comment by aclegg3** [comment]
These are part of the [pytest](https://docs.pytest.org/en/stable/) suite for Habitat-sim. 

Once installed (e.g. through conda `conda install pytest`), you should be able to run them like
 `pytest tests/test_simulator.py` 
to run the full set of tests in that file, or like 
`pytest tests/test_simulator.py::test_sim_multiagent_move_and_reset` 
to run a single test. 

You can use the `-s` argument to enable command-line logging during the tests.
