### ISSUE TITLE
How/Where to add objects data for physical interactions in habitat-sim built with Conda(first method)

### ISSUE THREAD

**Issue by AJ1897** [facebookresearch/habitat-sim#1077]
## ❓ Questions and Help
Hey!
**
- [ ] I installed habitat-sim using: **conda install habitat-sim -c conda-forge -c aihabitat** : Works fine
- [ ] Downloaded datasets and extracted to my desired location: **mypath**
- [ ] Tested interactive testing using : **habitat-viewer mypath/scene_datasets/habitat-test-scenes/skokloster-castle.glb** : Works fine
- [ ] I wanted to test physical interactions but I am confused as to where I shall extract the objects data. I tried extracting it with the path: **my_username/habitat-sim/data/objects/** but I still cannot see any objects in simulation. 
**
Kindly guide me with the same!
Thanks.

**Comment by dhruvbatra** [comment]
Have you gone through the interaction tutorial? 

aihabitat.org/tutorial
