### ISSUE TITLE
System Requirements?

### ISSUE THREAD

**Issue by yc-chn** [facebookresearch/habitat-sim#1101]
## ❓ Questions and Help
os version? cpu cores? ram? gpu? vram? storage?
Minimum Spec, Good, Ideal?
not found in docs, not found in readme, not found in aihabitat.org homepage

**Comment by erikwijmans** [comment]
We don't give these as it's so dependent on what you want to do that it is impossible to give meaningful recommendations.  In general, any machine that can do a reasonable job at DL training is fine.

For OS, we support linux flavor and MacOS.  Folks have gotten it compiling on windows (as magnum supports that), but we don't test it.

**Comment by dman82499** [comment]
will windows ever be supported in the future?

**Comment by Skylion007** [comment]
It is not a priority at the moment.

The graphics library should support Windows out of the box, so it's probably just a matter of tweaking the CMake files/build process. Feel free to submit a PR.
