### ISSUE TITLE
Habitat Tutorials on Colab are failing.

### ISSUE THREAD

**Issue by yashkant** [facebookresearch/habitat-sim#1109]
## Steps to Reproduce

1. Run any notebooks from -- https://aihabitat.org/tutorial/2020/

## Additional context
I debugged this issue, it seems like the default Python Version for Colab has changed from 3.6 to 3.7. 
The installation [script](https://raw.githubusercontent.com/facebookresearch/habitat-sim/master/examples/colab_utils/colab_install.sh) used in the tutorial has a hardcoded Python version of 3.6, which links the conda installed libraries to `site-packages`. 

## Fix 
As of now, I am able to get everything running by just changing the version of Python in the installation script from 3.6 to 3.7.
[Here](https://transfer.sh/o6kpR/colab_install.sh) is the script that works for me currently. 

Ideally, we should be inserting this version dynamically by checking the Python version running on Colab Notebook.

**Comment by Skylion007** [comment]
I feared this might happen... https://twitter.com/GoogleColab/status/1365062244225060865?s=20

**Comment by Skylion007** [comment]
Closed by #1110
