### ISSUE TITLE
--compute_action_shortest_path says method not found 

### ISSUE THREAD

**Issue by iszihan** [facebookresearch/habitat-sim#111]
Hello, I'm trying to use example.py to make the agent save png image while traversing the shortest path to the goal position. When I try to use the option --compute_shortest_path, it says in the demo_runner.py file (line 260), the simulator object has no attribute named "make_action_pathfinder(agent_id)". And i indeed cannot find the method. I'm wondering is this a bug to be fixed? or is there any other way to accomplish what I want to do with the example.py? 

Thank you!

**Comment by naoto0804** [comment]
I've faced the same issue. Is there any update??

**Comment by naoto0804** [comment]
Thanks a lot for fixing it!
