### ISSUE TITLE
Using noisy pyrobot controls

### ISSUE THREAD

**Issue by ayushjain1144** [facebookresearch/habitat-sim#1127]
## ❓ Questions and Help
Hi, 

Thank you for your awesome work. I am interested in using noisy pyrobot controls:
https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/agent/controls/pyrobot_noisy_controls.py

Could you help me figure out how can I replace my normal actions with this noise model? Thanks!

**Comment by Skylion007** [comment]
If you are using habitat-lab just change the ActionSpace config: https://github.com/facebookresearch/habitat-lab/blob/e7dd59ff596da13b2032d3431f984609bf3389b9/examples/new_actions.py#L162
