### ISSUE TITLE
Ply file fails to import 

### ISSUE THREAD

**Issue by AJ1897** [facebookresearch/habitat-sim#1142]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

Hey!

I have been trying to import scans from ScanNet dataset. When I try to import the ply file into habitat-sim. I get the following error:

**Platform: can't get Xft.dpi property for virtual DPI scaling, falling back to physical DPI
Renderer: llvmpipe (LLVM 7.0, 256 bits) by VMware, Inc.
OpenGL version: 3.3 (Core Profile) Mesa 18.3.6
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    mesa-dsa-createquery-except-pipeline-stats
    mesa-forward-compatible-line-width-range
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0316 04:26:18.998952  3469 viewer.cpp:444] Dataset : default
I0316 04:26:18.999096  3469 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : default changed to proposed JSON configuration filename : default.scene_dataset_config.json
I0316 04:26:18.999115  3469 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Dataset) : Proposing JSON name : default.scene_dataset_config.json from original name : default | This file  does not exist.
I0316 04:26:18.999294  3469 AssetAttributesManager.cpp:117] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
I0316 04:26:18.999354  3469 AssetAttributesManager.cpp:117] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I0316 04:26:18.999419  3469 AssetAttributesManager.cpp:117] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
I0316 04:26:18.999456  3469 AssetAttributesManager.cpp:117] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I0316 04:26:18.999480  3469 AssetAttributesManager.cpp:117] Asset attributes (cubeSolid : cubeSolid) created and registered.
I0316 04:26:18.999497  3469 AssetAttributesManager.cpp:117] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I0316 04:26:18.999549  3469 AssetAttributesManager.cpp:117] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
I0316 04:26:18.999590  3469 AssetAttributesManager.cpp:117] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I0316 04:26:18.999620  3469 AssetAttributesManager.cpp:117] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I0316 04:26:18.999644  3469 AssetAttributesManager.cpp:117] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I0316 04:26:18.999676  3469 AssetAttributesManager.cpp:117] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I0316 04:26:18.999706  3469 AssetAttributesManager.cpp:117] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I0316 04:26:18.999722  3469 AssetAttributesManager.cpp:105] AssetAttributesManager::buildCtorFuncPtrMaps : Built default primitive asset templates : 12
I0316 04:26:19.000536  3469 SceneDatasetAttributesManager.cpp:23] File (default) not found, so new default dataset attributes created and registered.
I0316 04:26:19.000550  3469 MetadataMediator.cpp:47] MetadataMediator::createDataset : Dataset default successfully created.
I0316 04:26:19.006218  3469 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Physics Manager) : Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json | This file  does not exist.
I0316 04:26:19.006263  3469 PhysicsAttributesManager.cpp:27] File (./data/default.physics_config.json) not found, so new default physics manager attributes created and registered.
I0316 04:26:19.006271  3469 AbstractObjectAttributesManagerBase.h:175] AbstractObjectAttributesManager<T>::createObject  (Stage) : Making attributes with handle : scene0447_01_vh_clean.ply
I0316 04:26:19.006279  3469 ManagedContainerBase.cpp:19] ManagedContainerBase::convertFilenameToJSON : Filename : scene0447_01_vh_clean.ply changed to proposed JSON configuration filename : scene0447_01_vh_clean.stage_config.json
I0316 04:26:19.006299  3469 AttributesManagerBase.h:283] AttributesManager<T>::createFromJsonOrDefaultInternal  (Stage) : Proposing JSON name : scene0447_01_vh_clean.stage_config.json from original name : scene0447_01_vh_clean.ply | This file  does not exist.
I0316 04:26:19.006392  3469 AbstractObjectAttributesManagerBase.h:181] AbstractObjectAttributesManager<T>::createObject  (Stage) : Done making attributes with handle : scene0447_01_vh_clean.ply
I0316 04:26:19.006403  3469 AbstractObjectAttributesManagerBase.h:188] File (scene0447_01_vh_clean.ply) exists but is not a recognized config filename extension, so new default Stage attributes created and registered.
W0316 04:26:19.006418  3469 Simulator.cpp:160] Navmesh file not found, checked at 
I0316 04:26:19.006445  3469 SceneGraph.h:93] Created DrawableGroup: 
W0316 04:26:19.006544  3469 ResourceManager.cpp:228] ResourceManager::loadStage : Not loading semantic mesh - File Name : scene0447_01_vh_clean_semantic.ply does not exist.
I0316 04:26:19.006558  3469 ResourceManager.cpp:262] ResourceManager::loadStage : start load render asset scene0447_01_vh_clean.ply.
I0316 04:26:19.006563  3469 ResourceManager.cpp:569] ResourceManager::loadStageInternal : Attempting to load stage scene0447_01_vh_clean.ply 
I0316 04:26:19.006578  3469 ResourceManager.cpp:1108] Importing Basis files as ASTC 4x4 for scene0447_01_vh_clean.ply
Trade::AbstractImporter::object3D(): index 0 out of range for 0 entries**

I am not sure of what to do. Kindly help me.

**Comment by aclegg3** [comment]
Thanks for reporting this issue. We've tracked down the cause to lack of import pipeline support for these ply files with vertex colors and no material/texture/scene definition. We'll need to address this once other scheduled development tasks are completed.
