### ISSUE TITLE
Conda install for specific tag of habitat-sim

### ISSUE THREAD

**Issue by Kritika100** [facebookresearch/habitat-sim#1143]
Are there pre-build binaries or conda packages for a specific tag e.g. v0.1.5 of habitat-sim ?

The following command installs the master or latest version of habitat-sim :
conda install habitat-sim -c conda-forge -c aihabitat
Please help.
Thanks

**Comment by erikwijmans** [comment]
Yes, you can specify the version number, i.e. `condo install habitat-sim=0.1.6 -c conda-forge -c aihabitat`.  We do have binaries for 0.1.4 and 0.1.5, but they have slightly strange version numbers and only python 3.6 as we were doing the initial testing then, you can see the version numbers here: https://anaconda.org/aihabitat/habitat-sim/files

**Comment by Kritika100** [comment]
Thanks  @erikwijmans.
