### ISSUE TITLE
Problem installing Habitat-Sim

### ISSUE THREAD

**Issue by leokonto** [facebookresearch/habitat-sim#1209]
**System Settings:**
Ubuntu 18.04 LTS
Conda 4.9.2

**Execution order**
git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
conda create -n habitat python=3.6 cmake=3.14.0
conda activate habitat
pip install -r requirements.txt
sudo apt-get update || true
sudo apt-get install -y --no-install-recommends \
     libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev
python setup.py install

-----------------------------------------------------------------------------------------------------------------------------

After I run the last command I get following output:

running install
running bdist_egg
running egg_info
creating habitat_sim.egg-info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/examples
copying examples/demo_runner.py -> build/lib.linux-x86_64-3.6/examples
copying examples/ab_test.py -> build/lib.linux-x86_64-3.6/examples
copying examples/__init__.py -> build/lib.linux-x86_64-3.6/examples
copying examples/benchmark.py -> build/lib.linux-x86_64-3.6/examples
copying examples/settings.py -> build/lib.linux-x86_64-3.6/examples
copying examples/example.py -> build/lib.linux-x86_64-3.6/examples
creating build/lib.linux-x86_64-3.6/tests
copying tests/test_controls.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_random_seed.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_profiling_utils.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_examples.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_utils.py -> build/lib.linux-x86_64-3.6/tests
copying tests/__init__.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_physics.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_greedy_follower.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_light_setup.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_gfx.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_simulator.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_agent.py -> build/lib.linux-x86_64-3.6/tests
copying tests/conftest.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_configs.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_sensors.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_attributes_managers.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_snap_point.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_navmesh.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_data_extraction.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_semantic_scene.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_noise_models.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_compare_profiles.py -> build/lib.linux-x86_64-3.6/tests
copying tests/test_pyrobot_noisy_controls.py -> build/lib.linux-x86_64-3.6/tests
creating build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/scene.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/attributes.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/errors.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/simulator.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/sensor.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/sim.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/gfx.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/geo.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/attributes_managers.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/metadata.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/logging.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/registry.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/physics.py -> build/lib.linux-x86_64-3.6/habitat_sim
creating build/lib.linux-x86_64-3.6/habitat_sim/nav
copying habitat_sim/nav/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/nav
copying habitat_sim/nav/greedy_geodesic_follower.py -> build/lib.linux-x86_64-3.6/habitat_sim/nav
creating build/lib.linux-x86_64-3.6/habitat_sim/agent
copying habitat_sim/agent/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent
copying habitat_sim/agent/agent.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent
creating build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/common.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/profiling_utils.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/gfx_replay_utils.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/collect_env.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/viz_utils.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/compare_profiles.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors
copying habitat_sim/sensors/sensor_suite.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors
copying habitat_sim/sensors/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors
creating build/lib.linux-x86_64-3.6/habitat_sim/bindings
copying habitat_sim/bindings/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/bindings
creating build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/object_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/default_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/pyrobot_noisy_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
creating build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/data_structures.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/pose_extractor.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/data_extractor.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/gaussian_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/no_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/speckle_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/sensor_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/redwood_depth_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/poisson_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models/data
copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models/data
running build_ext
Submodule 'docs/m.css' (https://github.com/mosra/m.css) registered for path 'docs/m.css'
Submodule 'src/deps/Sophus' (https://github.com/strasdat/Sophus) registered for path 'src/deps/Sophus'
Submodule 'src/deps/assimp' (https://github.com/assimp/assimp) registered for path 'src/deps/assimp'
Submodule 'src/deps/bullet3' (https://github.com/bulletphysics/bullet3) registered for path 'src/deps/bullet3'
Submodule 'src/deps/corrade' (https://github.com/mosra/corrade.git) registered for path 'src/deps/corrade'
Submodule 'src/deps/eigen' (https://gitlab.com/libeigen/eigen.git) registered for path 'src/deps/eigen'
Submodule 'src/deps/glfw' (https://github.com/glfw/glfw) registered for path 'src/deps/glfw'
Submodule 'src/deps/glog' (https://github.com/google/glog.git) registered for path 'src/deps/glog'
Submodule 'src/deps/googletest' (https://github.com/google/googletest) registered for path 'src/deps/googletest'
Submodule 'src/deps/imgui' (https://github.com/ocornut/imgui.git) registered for path 'src/deps/imgui'
Submodule 'src/deps/magnum' (https://github.com/mosra/magnum.git) registered for path 'src/deps/magnum'
Submodule 'src/deps/magnum-bindings' (https://github.com/mosra/magnum-bindings.git) registered for path 'src/deps/magnum-bindings'
Submodule 'src/deps/magnum-integration' (https://github.com/mosra/magnum-integration.git) registered for path 'src/deps/magnum-integration'
Submodule 'src/deps/magnum-plugins' (https://github.com/mosra/magnum-plugins.git) registered for path 'src/deps/magnum-plugins'
Submodule 'src/deps/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'src/deps/pybind11'
Submodule 'src/deps/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'src/deps/rapidjson'
Submodule 'src/deps/recastnavigation' (https://github.com/erikwijmans/recastnavigation.git) registered for path 'src/deps/recastnavigation'
Submodule 'src/deps/tinyobjloader' (https://github.com/syoyo/tinyobjloader.git) registered for path 'src/deps/tinyobjloader'
Cloning into '/home/leo/habitat/habitat-sim/docs/m.css'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/Sophus'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/assimp'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/bullet3'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/corrade'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/eigen'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/glfw'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/glog'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/googletest'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/imgui'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum-bindings'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum-integration'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum-plugins'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/pybind11'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/rapidjson'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/recastnavigation'...
Cloning into '/home/leo/habitat/habitat-sim/src/deps/tinyobjloader'...
Submodule path 'docs/m.css': checked out 'de86049b87f8dc12c022406c201abb533bc78f68'
Submodule path 'src/deps/Sophus': checked out 'b475c0a81a197ff8ea6bdcf8df8a2f5a7b1da879'
Submodule path 'src/deps/assimp': checked out '8f0c6b04b2257a520aaab38421b2e090204b69df'
Submodule path 'src/deps/bullet3': checked out '830f0a9565b1829a07e21e2f16be2aa9966bd28c'
Submodule path 'src/deps/corrade': checked out 'c46703649880f0f8b4feac62cce5b18821677e27'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/corrade/toolchains'
Cloning into '/home/leo/habitat/habitat-sim/src/deps/corrade/toolchains'...
Submodule path 'src/deps/corrade/toolchains': checked out '6957ebbc9f18aa478fac2e99e6687c18410bab29'
Submodule path 'src/deps/eigen': checked out '0fd6b4f71dd85b2009ee4d1aeb296e2c11fc9d68'
Submodule path 'src/deps/glfw': checked out '0a49ef0a00baa3ab520ddc452f0e3b1e099c5589'
Submodule path 'src/deps/glog': checked out '96a2f23dca4cc7180821ca5f32e526314395d26a'
Submodule path 'src/deps/googletest': checked out '00938b2b228f3b70d3d9e51f29a1505bdad43f1e'
Submodule path 'src/deps/imgui': checked out 'ca30ef4269150e71a950106c6cfa8f94898581da'
Submodule path 'src/deps/magnum': checked out '46f4518eb6ca121dfa3da2884dc5c8ad5417e97b'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum/toolchains'
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum/toolchains'...
Submodule path 'src/deps/magnum/toolchains': checked out '6957ebbc9f18aa478fac2e99e6687c18410bab29'
Submodule path 'src/deps/magnum-bindings': checked out '52f2073ff9c399ad2120085c9ca6f6a021fdafc1'
Submodule path 'src/deps/magnum-integration': checked out 'a157a78945a98124c31dde2177cc62efea9a40a0'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-integration/toolchains'
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum-integration/toolchains'...
Submodule path 'src/deps/magnum-integration/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/magnum-plugins': checked out '15b8cac94f2a3ffcf09dd7703293fc747024e0f8'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-plugins/toolchains'
Cloning into '/home/leo/habitat/habitat-sim/src/deps/magnum-plugins/toolchains'...
Submodule path 'src/deps/magnum-plugins/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/pybind11': checked out '8de7772cc72daca8e947b79b83fea46214931604'
Submodule path 'src/deps/rapidjson': checked out '73063f5002612c6bf64fe24f851cd5cc0d83eef9'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'src/deps/rapidjson/thirdparty/gtest'
Cloning into '/home/leo/habitat/habitat-sim/src/deps/rapidjson/thirdparty/gtest'...
Submodule path 'src/deps/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
Submodule path 'src/deps/recastnavigation': checked out '354591e10a772b8057e42a4f9de701155b9aaa02'
Submodule path 'src/deps/tinyobjloader': checked out 'e52dfdbecdf8893b161a65e508bc009746fa6042'
CMake Error at /home/leo/anaconda3/envs/habitat/share/cmake-3.14/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  /home/leo/anaconda3/envs/habitat/bin/x86_64-conda_cos6-linux-gnu-cc.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/leo/habitat/habitat-sim/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    include_package_data=True,
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.build_extension(ext)
  File "setup.py", line 273, in build_extension
    env=env,
  File "/home/leo/anaconda3/envs/habitat/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-H/home/leo/habitat/habitat-sim/src', '-Bbuild', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/leo/habitat/habitat-sim/build/lib.linux-x86_64-3.6/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/leo/anaconda3/envs/habitat/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=ON', '-DTARGET_HEADLESS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.

**Comment by erikwijmans** [comment]
```
Could not find compiler set in environment variable CC:

/home/leo/anaconda3/envs/habitat/bin/x86_64-conda_cos6-linux-gnu-cc.
Call Stack (most recent call first):
CMakeLists.txt:15 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

Seems like your system does not have a c/cpp compiler installed.  `sudo apt install build-essential` will get you one

**Comment by leokonto** [comment]
A simple reboot and sudo apt-get upgrade seemed to do the trick actually. Still thank you for your timely answer!
