### ISSUE TITLE
Proposal: replace glog with Corrade::Utility::Debug

### ISSUE THREAD

**Issue by mosra** [facebookresearch/habitat-sim#121]
I'm seeing a lot of code like

```cpp
LOG(INFO) << "User provided object inertia " 
          << bInertia.x() << " " << bInertia.y() << " " << bInertia.z();
```

or a `switch` that looks like 

```cpp
      case Magnum::MeshPrimitive::Lines:
        LOG(ERROR) << "Invalid primitive: Lines";
        break;
      case Magnum::MeshPrimitive::Points:
        LOG(ERROR) << "Invalid primitive: Points";
        break;
      case Magnum::MeshPrimitive::LineLoop:
        LOG(ERROR) << "Invalid primitive Line loop";
        break;
      ...
```

It's making me sad, because it wastes programmer time -- logging / printf debugging should not involve any mental overhead of "how the heck do I print this variable". The [Utility::Debug](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Debug.html) class in Magnum can do the same as just:

```cpp
Debug{} << "User provided object inertia" << bInertia;
```

and it can also print *any* container, almost all Magnum enum values (as names, not numbers, of course), it has output redirection (and muting), debug/warning/error levels, colored output if you want to get fancy and it can [print images](https://blog.magnum.graphics/backstage/multidimensional-strided-array-views/#enter-strided-array-views) as well.

I never used glog, but looking at the project page there doesn't even seem to be any real docs for it, apart from a [raw HTML file](https://github.com/google/glog/blob/master/doc/glog.html). How well maintained that project is? For the WebGL build in #53 we'd need to use something else anyway, so I would propose switching away from it completely.

My question is -- is there any glog feature that `Utility::Debug` doesn't have and you need it? One thing I'm aware of is that it doesn't prefix the output with file/line by default, but there's a (not yet merged) proposal that adds it as an opt-in feature on supported compilers: https://github.com/mosra/corrade/pull/55

**Comment by msavva** [comment]
Thanks @mosra for making this proposal!  It will certainly make things easier for us down the line if we can leverage logging from Magnum (and get free WebGL build support).  Overall, it does seem that switching from `glog` to `Utility::Debug` will bring benefits without giving up too much.

In addition to file/line prefixes, a few other features of `glog` that we currently use are: having a file sink for the log, verbosity level control and module-level log output filtering through "setting flags" (see http://rpg.ifi.uzh.ch/docs/glog.html).  Are analogues of these features easy through `Utility::Debug`?

**Comment by mosra** [comment]
There's `Debug`, `Warning`, `Error` and `Fatal` (which exits after printing a message) for different verbosity levels. Each of them can be separately scope-redirected to any of C++ streams (so stdout, stderr, file output, ...) and also muted (see the docs linked above for details). Redirecting to standard output *and* a file would need to be done using a custom `ostream` implementation, at the moment there's no such functionality. 

If you'd need to configure the file redirection / muting / verbosity level through command-line arguments or environment, you would need to wire that in (for example using `Utility::Arguments`).
Compared to glog it's completely macro-less, which means some features that glog has can't be easily done without wrapping everything in macros as well. That means it also affects everything related to file/line info (such as filename-based filtering) -- mosra/corrade#55 relies on `std::source_location` to get this info and compiler support is pretty spotty at the moment.

In my experience I needed file/line info very rarely in practice and definitely not for every message, but I don't want to force you into anything :)

**Comment by mosra** [comment]
#179 might be another reason to move away from gflags.

**Comment by mosra** [comment]
mosra/corrade#55 for the file/line info in out is merged now, support is on GCC 8+ and Clang 9+ (and Apple Clang / Xcode 12+, I guess).

**Comment by mosra** [comment]
With #496 the file+line info in Debug is available for all GCC versions and Clang 9+.
