### ISSUE TITLE
.glb files of gibson dataset is black in habitat-viewer

### ISSUE THREAD

**Issue by glattm** [facebookresearch/habitat-sim#1232]
I wanted to try out the gibson dataset with habitat. I downloaded it from https://github.com/StanfordVL/GibsonEnv#database
and watch it with the habitat viewer:

`habitat-viewer /path/to/Allensville.glb`

Every file is only displayed as a black  surface. I'm able to navigate in them with arrow keys or setting the agent in random places.

What am i doing wrong ?

**Comment by aclegg3** [comment]
Loading gibson's Allensville scene with the viewer via (`./build/viewer -- /path/to/gibson/Allensville.glb`) I see:
![image](https://user-images.githubusercontent.com/1445143/118676111-fc995880-b7af-11eb-8b4c-6adff16dfd2a.png)

**Comment by glattm** [comment]
When i try to run `./build/viewer -- /path/to/gibson/Allensville.glb` i get the following screen
![ScreenshotAllensville](https://user-images.githubusercontent.com/83392763/118833997-30fd3980-b8c2-11eb-9acd-41783cc6eff2.png)
I can navigate and print the agents position onto the screen, so it seems to work but only with a black screen


The only file that works for me is "Ackermanville.glb"
If i run `./build/viewer -- /path/to/gibson/Ackermanville.glb` i get this screen:
![ScreenshotAckermanville](https://user-images.githubusercontent.com/83392763/118834416-7faad380-b8c2-11eb-8cc8-780f814f6a30.png)

which seems to work fine
