### ISSUE TITLE
module 'habitat_sim' has no attribute 'CameraSensorSpec'

### ISSUE THREAD

**Issue by vdean** [facebookresearch/habitat-sim#1234]
## Habitat-Sim version
Latest version via Conda

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Master branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

I installed habitat-sim via Conda. The interactive demo with habitat-viewer works, but when I run the example script, I get an error about no attribute CameraSensorSpec. A collaborator tried installing on an entirely different setup and saw the same error.

## Steps to Reproduce

python examples/example.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb

Traceback (most recent call last):
  File "examples/example.py", line 70, in <module>
    perf = demo_runner.example()
  File "/home/vdean/habitat-sim/examples/demo_runner.py", line 409, in example
    start_state = self.init_common()
  File "/home/vdean/habitat-sim/examples/demo_runner.py", line 322, in init_common
    self._cfg = make_cfg(self._sim_settings)
  File "/home/vdean/habitat-sim/examples/settings.py", line 77, in make_cfg
    color_sensor_spec = habitat_sim.CameraSensorSpec()
AttributeError: module 'habitat_sim' has no attribute 'CameraSensorSpec'
## Expected behavior
The non-interactive testing should should an agent traversing a path.

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/master/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

ENVIRONMENT INFO:
Platform: Linux-5.4.0-72-generic-x86_64-with-debian-buster-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.9
Mac version: 
Python version: 3.6.13
Architecture: 64bit 
Win version:    
System OS: Linux
Release: 5.4.0-72-generic
Version: #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021
Operational System: linux
GCC version: b'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\n'
CMAKE version: b'cmake version 3.14.0\n'
NVIDIA-SMI: b'Wed May 12 10:19:10 2021       \n+-----------------------------------------------------------------------------+\n| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |\n|-------------------------------+----------------------+----------------------+\n| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n|                               |                      |               MIG M. |\n|===============================+======================+======================|\n|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0  On |                  N/A |\n| 22%   42C    P8    16W / 250W |    244MiB / 12204MiB |      4%      Default |\n|                               |                      |                  N/A |\n+-------------------------------+----------------------+----------------------+\n'
Pip packages versions:
b'imageio==2.9.0\nimageio-ffmpeg==0.4.3\nmatplotlib==3.0.3\nnumba==0.51.2\nnumpy==1.19.1\nnumpy-quaternion==2021.4.5.14.42.35\ntqdm==4.60.0\n'
Conda packages versions:
b'attrs                     21.2.0             pyhd8ed1ab_0    conda-forge  19.1.0\ngitpython                 3.1.15             pyhd8ed1ab_0    conda-forge\nimageio                   2.9.0                      py_0    conda-forge\nimageio-ffmpeg            0.4.3              pyhd8ed1ab_0    conda-forge\nmatplotlib                3.2.2                         1    conda-forge\nnumba                     0.51.2           py36h7c3b610_0    conda-forge\nnumpy                     1.19.5           py36h2aa4a07_1    conda-forge\npillow                    6.2.1            py36h6b7be26_0    conda-forge\nscipy                     1.5.3            py36h976291a_0    conda-forge  1.3.0\ntqdm                      4.60.0             pyhd8ed1ab_0    conda-forge\n'

**Comment by aclegg3** [comment]
Looks like you may be running master branch scripts on [version 0.1.7](https://github.com/facebookresearch/habitat-sim/releases/tag/v0.1.7) conda build. You could clone that version of the repo, or conda install [the nightly](https://anaconda.org/aihabitat-nightly/habitat-sim) build instead.
