### ISSUE TITLE
What do the parameters of the variable `habitat_sim.SensorSpec.orientation` mean?

### ISSUE THREAD

**Issue by zhangtianjia** [facebookresearch/habitat-sim#1248]
## Habitat-Sim version
Very thankful for providing such a wonderful simulator.
## ❓ Questions and Help
I want to set the orientation for my customized sensor. I create the configure instance by:
```
sensor_spec = habitat_sim.SensorSpec()
sensor_spec.uuid = `color`
sensor_spec.sensor_type = habitat_sim.SensorType.COLOR
sensor_spec.position = [0, 1, 0]
sensor_spec.oritentation = [x, y, z]
```
However, the meaning of the `position` and `orientation` is not clarified. As far as I know, the position is with respect to the agent coordinate in meters. Then what do the three entries of the `orientation` mean (Euler angles in the three rotation axes? ) and what are their units(degree or radian？)?

**Comment by dhruvbatra** [comment]
Yes. Radian. 

See here e.g. https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/ECCV_2020_Interactivity.ipynb#scrollTo=MAHxJgUkMANT&line=1&uniqifier=1
