### ISSUE TITLE
Retrieve world coordinate in Image Extractor

### ISSUE THREAD

**Issue by yuyecreus** [facebookresearch/habitat-sim#1282]
Hello everybody, 

I am looking at the Image Extractor Class (https://aihabitat.org/docs/habitat-sim/image-extractor.html).

I am wondering if there exists a way to hack this class so it can retrieve the world coordinate from which each image sample is taken. 
Thank you very much!

**Comment by Skylion007** [comment]
You retrieve this from the agent position. See the ECCV tutorials for more info on how to control the agent. Just add that call when saving out the images.
