### ISSUE TITLE
How to set the camera height in Image Extraction?

### ISSUE THREAD

**Issue by AgentEXPL** [facebookresearch/habitat-sim#1321]
I have read the Image Extractor Tutorial, and know how to set the camera pose. But I have on idea on how to set the height of camera sensor, where the height is the distance between the sensor and the ground. Hope some good guy to help me.

**Comment by Skylion007** [comment]
You can do this by changing the sensor position in the agent config. See our various Colab tutorials for more info.

**Comment by AgentEXPL** [comment]
Thanks for your guidence. I have found the details on how to set the agent.
