### ISSUE TITLE
Importing animated human characters

### ISSUE THREAD

**Issue by rithik25** [facebookresearch/habitat-sim#1334]
I would like to import several human characters in my scene with a walking animation. Is using a URDF file that describes the character the only option to import a human character? Also, how do I go about animating the human character from the URDF to create a walking animation?

**Comment by aclegg3** [comment]
Hey @rithik25, 

Yes, URDF is currently the only supported format for loading robots and characters into Habitat. Once instanced into the simulator you can set the joint states of the character, add joint motors, and run dynamic simulation to animate it. 

You can check out the [ArticulatedObject python API](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ManagedArticulatedObject.html) and [related unit tests](https://github.com/facebookresearch/habitat-sim/blob/d2ccdcb923a20e8bbe4054466f2418e5906a8fe2/tests/test_physics.py#L683) for pointers. More tutorial resources should be available in the near future.
