### ISSUE TITLE
Object category name <-> id for mp3d

### ISSUE THREAD

**Issue by zhangfuyang** [facebookresearch/habitat-sim#1346]
Hi,

I am looking for a map for object `semantic id` to `semantic name` in mp3d. I couldn't find this info in the doc. So I print it by checking with the simulator (checking with `obj.category.name()` and `obj.category.index()`). Below is what I get. -1 is mapping to an empty string. I wonder what does that means?  Also what is "void". And it seems there is no id number 32 and 35?

Is there an existing official doc for this information? Thank you!

```
-1 
0 void
1 wall
2 floor
3 chair
4 door
5 table
6 picture
7 cabinet
8 cushion
9 window
10 sofa
11 bed
12 curtain
13 chest_of_drawers
14 plant
15 sink
16 stairs
17 ceiling
18 toilet
19 stool
20 towel
21 mirror
22 tv_monitor
23 shower
24 column
25 bathtub
26 counter
27 fireplace
28 lighting
29 beam
30 railing
31 shelving
33 gym_equipment
34 seating
36 furniture
37 appliances
38 clothes
39 objects
40 misc
```

**Comment by erikwijmans** [comment]
You can see the full mapping here: https://github.com/niessner/Matterport/blob/master/metadata/mpcat40.tsv.  The ones that are missing for yours are likely because you constructed this from a single scene and not all scenes have all objects.  `-1` is unlabeled.
