### ISSUE TITLE
Habitat different version coexist? 

### ISSUE THREAD

**Issue by zenght** [facebookresearch/habitat-sim#1348]
### ❓ Questions and Help
I was wondering, can different versions of Habitat coexist on the same server?  I have already install habitat-sim V.0.1.5 on the server. However, when I followed the official tutorial to install habitat-sim v.0.1.7. There some API cannot be imported, such as the "CameraSensorSpec".

**Comment by erikwijmans** [comment]
You'll have to use some python environment manager like conda to have different versions installed at the same time.

**Comment by Skylion007** [comment]
or virtualenv or something similar.
