### ISSUE TITLE
Build from Docker: Segmentation fault (score dumped)

### ISSUE THREAD

**Issue by DianDYu** [facebookresearch/habitat-sim#135]
<img width="520" alt="Screen Shot 2019-08-06 at 11 57 13 PM" src="https://user-images.githubusercontent.com/9640379/62601326-f3bee780-b8a5-11e9-9792-3201fd912cb5.png">
  1. I tried to build docker with the provided docker file and run "python habitat-sim/examples/example.py" but got "Segmentation fault (core dumped)"

2. Then I pull and run docker from fairembodied/habitat:latest. I got the following error:
'''
==== Initialized Sensor Spec: =====
Sensor uuid:  color_sensor
Sensor type:  SensorType.COLOR
Sensor position:  [0.  1.5 0. ]
===================================
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0807 06:48:37.864651   392 WindowlessContext.cpp:93] Check failed: numDevices > 0 [EGL] No devices detected
*** Check failure stack trace: ***
Aborted (core dumped)
'''
Any suggestion on how to solve both of this (I would prefer the first one because I can change the docker and build upon it). Thanks!

**Comment by erikwijmans** [comment]
I suspect that not being able to pick-up any GPUs and the segfault are related.  Does `nvidia-smi` while inside the docker container produce the expected output (i.e. shows all the systems GPUs)?  EGL also only works with nvidia GPUs on linux AFAIK and I believe this is also true even when inside a docker container (i.e. the host system must be linux).

**Comment by DianDYu** [comment]
Thanks!

**Comment by AAdeleye** [comment]
How did you solve this issue? I have a similar issue:

![Screenshot from 2019-12-06 14-32-40](https://user-images.githubusercontent.com/9774995/70361290-dbe87780-1835-11ea-8553-b2f47a625561.png)


The docker file with git checkout version "9129fb2d35569cbdc07ac784fd58d6287240ad8b" for HabitatSim and "55fc9353a81d9a2a899dcd7bc08c8be39d228b8c" for Habitat-api
