### ISSUE TITLE
Improvements to install instructions 

### ISSUE THREAD

**Issue by dhuber23b** [facebookresearch/habitat-sim#136]
Here are a few suggestions for improving the installation instructions and README.md

1) move the note about cmake requirement to be between step 3 and 4 in the instructions (or make a new step there).  This will make it smoother for people who install.  I was following the instructions, they failed, then I searched the page for cmake and found the note.  

2) Add a link to the docs from the README.md file.  Currently it is not there, and I only found it by clicking on the example demo link.

3) After trying the demo notebook, I found that I was missing scipy and matplotlib.  The warning indicates that they really should be installed.  I suggest adding these dependencies as optional in the install or including in the requirements list.

**Comment by aclegg3** [comment]
Thanks for the suggestions.
