### ISSUE TITLE
CameraSensorSpec Attribute error

### ISSUE THREAD

**Issue by rithik25** [facebookresearch/habitat-sim#1363]
Hello,

I am using version 0.1.7 of habitat-sim. I am using color_sensor_spec = habitat_sim.sensor.CameraSensorSpec() to create a new sensor, but get the following error:

```
    color_sensor_spec = habitat_sim.sensor.CameraSensorSpec()
AttributeError: module 'habitat_sim.sensor' has no attribute 'CameraSensorSpec'
```

The code seems to be consistent with the documentation [here](https://aihabitat.org/docs/habitat-sim/habitat_sim.sensor.CameraSensorSpec.html), so I'm not sure what the problem is. Would appreciate some help to fix this.

**Comment by jturner65** [comment]
That functionality is new since 0.1.7 came out, this past January.  The docs on the site reflect the current Habitat master branch.  If you require the 0.1.7 version of Habitat, you can build the docs from that tag of the repository 
https://github.com/facebookresearch/habitat-sim/tree/v0.1.7/docs
