### ISSUE TITLE
Running habitat-viewer with my own scene

### ISSUE THREAD

**Issue by phj128** [facebookresearch/habitat-sim#1399]
## Habitat-Sim version
v0.2.0

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Master branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

Running habitat-viewer with my own scene. I have already generated the navmesh as the tutorial based on my own scene.

## Steps to Reproduce

1.  habitat-viewer /path/to/my/own/scene.glb

 Please note that without a minimal working example to reproduce the bug, we may not be able to help you.

## Expected behavior

The program works at the first, but when I move the camera quickly (rotation) or move the camera to some places with WSAD, the program would collapse and report the error below.

Assertion measurement._movingSum >= currentMeasurementData failed at /opt/conda/envs/py36/conda-bld/habitat-sim_1625040415038/work/src/deps/magnum/src/Magnum/DebugTools/FrameProfiler.cpp:199
[1] 18653 abort (core dumped) habitat-viewer ../path/to/my/own/scene.glb

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/master/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python habitat_sim/utils/collect_env.py
```
ENVIRONMENT INFO:

latform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.17
Mac version: 
Python version: 3.6.13
Architecture: 64bit 
Win version:    
System OS: Linux
Release: 4.15.0-140-generic
Version: #144~16.04.1-Ubuntu SMP Fri Mar 19 21:24:12 UTC 2021
Operational System: linux
GCC version: b'gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609'
CMAKE version: b'cmake version 3.14.0'
Wed Jul 21 11:42:01 2021       
NVIDIA-SMI:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:26:00.0  On |                  N/A |
| 45%   35C    P8    17W / 125W |   1821MiB /  5941MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1248      G   /usr/lib/xorg/Xorg                          1040MiB |
|    0      2375      G   ...quest-channel-token=8677440257041945335   222MiB |
|    0      3000      G   /opt/teamviewer/tv_bin/TeamViewer             14MiB |
|    0     23644      G   ...s/pycharm/pycharm-2019.2.1/jbr/bin/java    59MiB |
|    0     24618      G   /usr/bin/totem                                13MiB |
|    0     29749      G   compiz                                       464MiB |
+-----------------------------------------------------------------------------+
Pip packages versions:
b'imageio==2.9.0\nimageio-ffmpeg==0.4.4\nmatplotlib==3.3.4\nnumba==0.53.1\nnumpy==1.19.5\nnumpy-quaternion==2021.6.9.13.34.11\ntqdm==4.61.1\n'
Conda packages versions:
b'attrs                     21.2.0             pyhd8ed1ab_0    conda-forge  19.1.0\ngitpython                 3.1.18             pyhd8ed1ab_0    conda-forge\nimageio                   2.9.0                      py_0    conda-forge\nimageio-ffmpeg            0.4.4              pyhd8ed1ab_0    conda-forge\nmatplotlib                3.3.4                    pypi_0    pypi\nnumba                     0.53.1           py36h1328434_1    conda-forge\nnumpy                     1.19.5           py36h2aa4a07_1    conda-forge\npillow                    8.2.0                    pypi_0    pypi\nscipy                     1.5.4                    pypi_0    pypi  1.3.0\ntqdm                      4.61.1             pyhd8ed1ab_0    conda-forge\n'

**Comment by aclegg3** [comment]
Interesting. Looks like it could be a system incompatibility issue. Our standard platforms don't seem to have this issue. I notice the crash is occurring inside the `Magnum FrameProfiler`. (FYI @mosra) 

If you are willing to build from source it may solve the problem and if not you could comment out the profiler code in the `viewer.cpp` as it isn't an essential feature.
