### ISSUE TITLE
A mistake in "def make_video" in "viz_utils.py"

### ISSUE THREAD

**Issue by AgentEXPL** [facebookresearch/habitat-sim#1421]
## Habitat-Sim version : conda stable version
I installed habitat-sim a few days ago by conda install command.

When I ran "ECCV_2020_Interactivity.py" and tried to make a video with overlay images from different sensors. It failed. The reason is that there is a mistake in [Line 246](https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/utils/viz_utils.py#L246) of "viz_utils.py". In "def make_video" function, "overlay_settings=None" is used. However, it should be "overlay_settings=overlay_settings".

--Original Code------------------------------------------------------------------------
    for ob in observations:
        # primary image processing
        image_frame = make_video_frame(
            ob,
            primary_obs,
            primary_obs_type,
            video_dims,
            overlay_settings=None,
            observation_to_image=observation_to_image,
        )

        # write the desired image to video
        writer.append_data(np.array(image_frame))

---Correct Code----------------------------------------------------------------------------
    for ob in observations:
        # primary image processing
        image_frame = make_video_frame(
            ob,
            primary_obs,
            primary_obs_type,
            video_dims,
            overlay_settings=overlay_settings,
            observation_to_image=observation_to_image,
        )

        # write the desired image to video
        writer.append_data(np.array(image_frame))

**Comment by aclegg3** [comment]
Another great catch. Thanks!
