### ISSUE TITLE
Question about Redwood Depth Noise Implementation

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [facebookresearch/habitat-sim#1455]
## Habitat-Sim version
v0.2.1

Habitat-lab commit: `bc85d09`
Habitat-sim commit: `fc7fb11`

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/ **Yes**

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/ **Yes**

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

I have a question about Redwood Depth Noise as a follow-up to the #987. Specifically, I am wondering whether the original GPU version is correct while the CPU version is off. Two major reasons:

### From Literature

From the original paper ["Unsupervised Intrinsic Calibration of Depth Sensors via SLAM"](http://www.roboticsproceedings.org/rss09/p27.html)'s Sec. IV, the author states

> ...  Finally, we discretize the depth multiplier images into bins of 8 × 6 pixels. At 640×480 resolution and a maximum range of 10m, this results in 32,000 parameters.

Essentially, this means the noise bins are of shape `[80, 80, 5]`. From the commit `d3d150c62f7d47c4350dd64d798017b2f47e66a9`, which is before #987:

1. GPU version gives `[80, 80, 5]`
https://github.com/facebookresearch/habitat-sim/blob/d3d150c62f7d47c4350dd64d798017b2f47e66a9/src/esp/sensor/RedwoodNoiseModel.cu#L13-L14

2. CPU version gives `[80, 100, 4]`
https://github.com/facebookresearch/habitat-sim/blob/d3d150c62f7d47c4350dd64d798017b2f47e66a9/habitat_sim/sensors/noise_models/redwood_depth_noise_model.py#L105-L106

IMHO, I think GPU version is correct.

### From Running 

Logically, I think the following line of function `_undistort` will cause out-of-bounds (OOB) error if we have noise bins of shape `[80, 100, 4]`:
https://github.com/facebookresearch/habitat-sim/blob/fc7fb11ccec407753a73ab810d1dbb5f57d0f9b9/habitat_sim/sensors/noise_models/redwood_depth_noise_model.py#L39

The reason is that since our noise bins are of shape `[80, 100, 4]`, the `min(max(i1, 0), 4)` and `min(i2, 4)` may output value of `4`, which will go out of the boundary.

However, we never encounter such OOB issue. After investigation, I find it is because `numba` does not check OOB error by default. See [this documentation](https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html#bounds-checking):

> By default, instead of causing an IndexError, accessing an out-of-bound index of an array in a Numba-compiled function will return invalid values or lead to an access violation error (it’s reading from invalid memory locations).

I have verified it by the following:
```python
@numba.jit(nopython=True, fastmath=True)
def _undistort(x, y, z, model):
    i2 = int((z + 1) / 2)
    i1 = int(i2 - 1)
    a = (z - (i1 * 2.0 + 1.0)) / 2.0
    x = x // 8
    y = y // 6

    d = 4

    f = (1 - a) * model[y, x, d] + a * model[y, x, d]

    if f < 1e-5:
        return 0
    else:
        return z / f
``` 

- When `numba` is **disabled**, I encountered OOB error.
- When `numba` is **enabled**, no error will be thrown.

Any suggestions on this? Thanks a lot.

**Comment by Skylion007** [comment]
Ping @erikwijmans since he authored #987 . Is it possible the original bug was in the CPU code?

**Comment by Xiaoming-Zhao** [comment]
Hi @Skylion007, thanks a lot for your reply. I share the same thoughts with you. I think the original CPU code may have some issues.

Another thing is that it seems like the unit test does not test the situation when `numba` is disabled. I think it may be beneficial to add such tests.

**Comment by erikwijmans** [comment]
Hmm yeah, looks like that is a bug. For #987 I was just trying to match the CPU implementation. I'll need to think about when is the best time to fix this as the 2021 habitat challenge is running that CPU code.

**Comment by Xiaoming-Zhao** [comment]
Hi @erikwijmans, just a follow-up on this? Do you plan to fix this before the 2022's challenge? Thanks

**Comment by erikwijmans** [comment]
Yep, this should be fixed. I pushed a fix for this. Also fixed a few other bugs while I was at it.

**Comment by dhruvbatra** [comment]
Thank you @Xiaoming-Zhao of reminding us of this. Would you have time to test the solution?

**Comment by Xiaoming-Zhao** [comment]
Hi @dhruvbatra, sorry that I missed your message.

I have tested with `habitat-lab/examples/example_pointnav.py` using the following commit:
- habitat-lab: `e934b15`
- habitat-sim: `b14c0e9` 

I think the updated implementation is correct as it matches the original paper's description and the out-of-boundary (OOB) error disappears when I disable `numba`, where OOB error occurred previously. Feel free to let me know if there is anything else I can help with.

**Comment by dhruvbatra** [comment]
Awesome, thank you @Xiaoming-Zhao!
