### ISSUE TITLE
Camera configuration kills Google colab

### ISSUE THREAD

**Issue by Gricha1** [facebookresearch/habitat-sim#1467]
AGENT = habitat_sim.agent.AgentConfiguration()
rgb_sensor_spec = habitat_sim.CameraSensorSpec()
BACKEND = habitat_sim.SimulatorConfiguration()
BACKEND.scene_id=test_scene

CONF = habitat_sim.Configuration(BACKEND, [AGENT])

When i try to use:
sim = habitat_sim.Simulator(CONF)

The Google colab's kernel dies. It happens when i try to add camera configuration.

**Comment by Skylion007** [comment]
If the colab kernal dies, it's proibably segfault. The most common reason is an invalid config / environment (like encountering a filenotfound error when loading the scene, invalid configuration, etc...)

**Comment by Gricha1** [comment]
On the example of using habitat sim on google colab the authors are using google colab's GPU. So the problem was that i didnt use gpu in colab, thanks :)
