### ISSUE TITLE
Inconsistency between RGB and semantic images in Matterport3D

### ISSUE THREAD

**Issue by ReNginx** [facebookresearch/habitat-sim#1468]
## Habitat-Sim version
v0.2.1

## ❓ Questions and Help
Hi, I was using habitat to generate paired color and semantic images in matterport3d. I found  habitat produce inconsistent results in scene JmbYfDe2QKZ.   There's an erroneous mesh in the ply file (circled out in the first image). 
I use code modified from the tutorial https://aihabitat.org/docs/habitat-sim/stereo-agent.html, taking shots using different sensors. The mesh appears in semantic images, but not in color and depth images.

I'm wondering what caused this problem, and how we can fix it.

Thanks and looking forward to your response!

![error](https://user-images.githubusercontent.com/12798205/132386874-8734df48-0c91-4ad3-be38-e6a257010acf.png)
![colored_000000](https://user-images.githubusercontent.com/12798205/132386358-882f15d2-d3da-4953-a3d8-a9a101623470.png)
![rgb_000000](https://user-images.githubusercontent.com/12798205/132386342-7e53f2e0-98b5-4a0d-ba7e-1fe1a65fa5c9.jpg)
![depth_000000](https://user-images.githubusercontent.com/12798205/132386369-baccc9c1-4505-4edc-82d2-ddf28252d84f.png)

**Comment by aclegg3** [comment]
Hey @ReNginx,

The semantic meshes for MP3D were generated semi-automatically from 2D crowd sourced annotations. Some of them have artifacts like this. You could manually correct the .ply files if you like, but there isn't really anything we can do about that otherwise.
