### ISSUE TITLE
Ground Truth semantic annotation of Gibson?

### ISSUE THREAD

**Issue by zenght** [facebookresearch/habitat-sim#1500]
Hi, I want to know how to get semantic annotations corresponding to Gibson datasets. I followed the method to obtain the corresponding images [https://aihabitat.org/docs/habitat-api/habitat-api-demo.html#scene-semantic-annotations](url). but the image seems to exist only two values. 
![move_forwardreplica_gorgb](https://user-images.githubusercontent.com/33613705/134916530-514c808d-c458-42e2-85ed-8e6f193f8e44.png)

![move_forwardreplica_go](https://user-images.githubusercontent.com/33613705/134916422-2ebb73a5-0975-4fc8-8a23-1ecae27a155e.png)
And the dataset I used is Habitat -Gibson dataset.

**Comment by dhruvbatra** [comment]
Those likely are the only annotations available in the Gibson dataset. Try MP3D.

**Comment by vincent341** [comment]
> Hi. I'm struggling with creating 2D semantic maps for MP3D. Would you mind letting me know how to get 2D top-down ground truth of semantic maps of MP3D? Thanks very much.

**Comment by vincentcartillier** [comment]
Hi @vincent341, (duplicate from [here](https://github.com/facebookresearch/habitat-sim/issues/948)) 
You can check the following project: [Semantic-MapNet](https://github.com/vincentcartillier/Semantic-MapNet) in which we built such top-down semantic maps for MP3D.

Specifically you should check the following scripts:
```
data/build_point_cloud_from_mesh_h5.py
compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py
```

**Comment by vincent341** [comment]
> Hi @vincent341, (duplicate from [here](https://github.com/facebookresearch/habitat-sim/issues/948)) You can check the following project: [Semantic-MapNet](https://github.com/vincentcartillier/Semantic-MapNet) in which we built such top-down semantic maps for MP3D.
> 
> Specifically you should check the following scripts:
> 
> ```
> data/build_point_cloud_from_mesh_h5.py
> compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py
> ```

Appreciate your help very much, Vince.
