### ISSUE TITLE
depth to world coordinate (when height and width are not equal)

### ISSUE THREAD

**Issue by zhangfuyang** [facebookresearch/habitat-sim#1510]
Hi,

This demo (https://aihabitat.org/docs/habitat-lab/view-transform-warp.html) shows the way to get the world coordinate. But it asserts W==H.

I wonder how about w and h are not equal ... Sorry, this question sounds quite stupid:( But I couldn't make it works... 

Does it just need to change `xs, ys = np.meshgrid(np.linspace(-1,1,W), np.linspace(1,-1,W))` to `xs, ys = np.meshgrid(np.linspace(-1,1,H), np.linspace(1,-1,W))` and other reshape parts? I tried this but it doesn't work.

**Comment by zhangfuyang** [comment]
I find the bug on my side.

**Comment by sreenithy** [comment]
Hi @zhangfuyang  how did you fix this?
