### ISSUE TITLE
How to generate camera poses?

### ISSUE THREAD

**Issue by zsh2000** [facebookresearch/habitat-sim#1512]
Thanks for the awesome tool! 

I have successfully rendered RGB images and semantic labels on Replica dataset using 

`python examples/example.py --save_png --semantic_sensor`

I want to get the corresponding camera poses (better in the format of extrinsic matrix and instrinsic matrix) together with the rendered RGB images and semantic labels. But there is no options in "example.py" enabling the generation of poses.

Could you please tell me how to do it?

**Comment by cbyan1003** [comment]
> Thanks for your reply! I'll try it out.

Could you please tell me how to get the camera pose in details?
And also I meet a problem, when I use `--semantic sensor` to get the output semantic image from replica dataset, but the ouput is wrong. How to generate semantic image? I guess my setting is wrong.

**Comment by oskar0812** [comment]
Hi, I was wondering if you solved this problem? I also encountered the same problem
