### ISSUE TITLE
error: [Errno 2] No such file or directory: 'build/compile_commands.json'

### ISSUE THREAD

**Issue by 201814476** [facebookresearch/habitat-sim#1530]
## Habitat-Sim version
habitat-sim commit == 020041d75eaf3c70378a9ed0774b5c67b9d3ce99

1. When I run: python setup.py install --headless， it occurred error: [Errno 2] No such file or directory: 'build/compile_commands.json'.

2. Then I run: rm -rf build, it occurred subprocess.CalledProcessError: Command '['cmake', '-H/mnt/cd43550d-ff7b-4058-a185-a6b1f0bd96ea/PointNav-VO-main/habitat-sim-020041d75eaf3c70378a9ed0774b5c67b9d3ce99/src', '-Bbuild', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/cd43550d-ff7b-4058-a185-a6b1f0bd96ea/PointNav-VO-main/habitat-sim-020041d75eaf3c70378a9ed0774b5c67b9d3ce99/build/lib.linux-x86_64-3.7/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/dell/anaconda3/envs/pointnav-vo/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=OFF', '-DTARGET_HEADLESS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=OFF']' returned non-zero exit status 1.

3. Then I run sudo apt install libx11-dev, it occurred error: [Errno 2] No such file or directory: 'build/compile_commands.json',again!

Can you tell me the reason? Thanks a lot!

**Comment by erikwijmans** [comment]
You can force cmake to re-run with `--cmake` which should generate that
