### ISSUE TITLE
failed building docs locally

### ISSUE THREAD

**Issue by maominzhe** [facebookresearch/habitat-sim#1533]
## Habitat-Sim version
v0.2.1

## ❓ Questions and Help
I got a problem when I'm following the instruction on building docs locally, it returns the following error when I run `./build.sh`: 

Warning: libgs not found
warning: ignoring unsupported tag 'HTML_FORMULA_FORMAT' at line 1504, file Doxyfile
warning: ignoring unsupported tag 'FORMULA_MACROFILE' at line 1530, file Doxyfile
..........
User/habitat-sim/src/esp/physics/RigidBase.h:102: warning: unable to resolve reference to 'Rigid' for \ref command
User/habitat-sim/src/esp/physics/RigidObject.h:113: warning: The following parameters of esp::physics::RigidObject::initialize(const assets::ResourceManager &resMgr, const assets::AbstractPhysicsAttributes::ptr physicsAttributes) are not documented:
  parameter 'resMgr'
........
   File "conf.py", line 17, in <module>
    import habitat_sim  # NOQA
  File "../habitat_sim/__init__.py", line 14, in <module>
    from habitat_sim.nav import *
  File "../habitat_sim/nav/__init__.py", line 1, in <module>
    from habitat_sim._ext.habitat_sim_bindings import (
ModuleNotFoundError: No module named 'habitat_sim._ext'

I followed the suggestions from #491 but it didn't work.
`echo $(cd examples; python -c "import habitat_sim; print(habitat_sim.__file__)")`
shows
`(habitat) ➜  docs git:(020041d7) python -c "import habitat_sim;print(habitat_sim.__file__)"
/Users/maomao/opt/anaconda3/envs/habitat/lib/python3.6/site-packages/habitat_sim-0.1.5-py3.6-macosx-10.9-x86_64.egg/habitat_sim/__init__.py`

I also tried `unset PYTHONPATH`

Any help on how to solve this? much much thanks!

**Comment by erikwijmans** [comment]
The docs require a local build IIRC as we don't ship the doxygen files.
