### ISSUE TITLE
Issues with running lighting_tutorial

### ISSUE THREAD

**Issue by sparsh-umd** [facebookresearch/habitat-sim#1566]
I created a new conda environment(pythpn3.8.10 & cmake3.4.10) & installed habitat-sim with `conda install habitat-sim withbullet -c conda-forge -c aihabitat`. Then I ran 'python3 setup.py --bullet install'.

1) When I test the installation with `habitat-viewer /path/to/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb` the following gets printed to terminal & viewer pops up & just stays blank(screenshot attached). Wait doesn't help, so I had to click 'Force Quit' which ultimately kills the simulator.

Terminal output:
`Renderer: AMD RENOIR (DRM 3.42.0, 5.14.8-051408-lowlatency, LLVM 12.0.0) by AMD
OpenGL version: 4.6 (Core Profile) Mesa 21.0.3
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    mesa-implementation-color-read-format-dsa-explicit-binding
    mesa-dsa-createquery-except-pipeline-stats
    mesa-forward-compatible-line-width-range
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1116 10:16:43.308897 46267 ManagedFileBasedContainer.h:210] <Dataset>::convertFilenameToPassedExt : Filename : default changed to proposed scene_dataset_config.json filename : default.scene_dataset_config.json
I1116 10:16:43.308987 46267 AttributesManagerBase.h:365] <Dataset>::createFromJsonOrDefaultInternal : Proposing JSON name : default.scene_dataset_config.json from original name : default | This file  does not exist.
I1116 10:16:43.309165 46267 AssetAttributesManager.cpp:120] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
I1116 10:16:43.309232 46267 AssetAttributesManager.cpp:120] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I1116 10:16:43.309274 46267 AssetAttributesManager.cpp:120] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
I1116 10:16:43.309299 46267 AssetAttributesManager.cpp:120] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I1116 10:16:43.309315 46267 AssetAttributesManager.cpp:120] Asset attributes (cubeSolid : cubeSolid) created and registered.
I1116 10:16:43.309324 46267 AssetAttributesManager.cpp:120] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I1116 10:16:43.309355 46267 AssetAttributesManager.cpp:120] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
I1116 10:16:43.309383 46267 AssetAttributesManager.cpp:120] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I1116 10:16:43.309399 46267 AssetAttributesManager.cpp:120] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I1116 10:16:43.309422 46267 AssetAttributesManager.cpp:120] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I1116 10:16:43.309448 46267 AssetAttributesManager.cpp:120] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I1116 10:16:43.309473 46267 AssetAttributesManager.cpp:120] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I1116 10:16:43.309482 46267 AssetAttributesManager.cpp:108] ::constructor : Built default primitive asset templates : 12
I1116 10:16:43.310115 46267 SceneDatasetAttributesManager.cpp:36] File (default) not found, so new default dataset attributes created and registered.
I1116 10:16:43.310148 46267 MetadataMediator.cpp:127] ::createSceneDataset : Dataset default successfully created.
I1116 10:16:43.310160 46267 AttributesManagerBase.h:365] <Physics Manager>::createFromJsonOrDefaultInternal : Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json | This file  exists.
I1116 10:16:43.310266 46267 PhysicsAttributesManager.cpp:26] JSON Configuration File (./data/default.physics_config.json) based physics manager attributes created and registered.
I1116 10:16:43.310273 46267 MetadataMediator.cpp:212] ::setActiveSceneDatasetName : Previous active dataset  changed to default successfully.
I1116 10:16:43.310277 46267 MetadataMediator.cpp:183] ::setCurrPhysicsAttributesHandle : Old physics manager attributes  changed to ./data/default.physics_config.json successfully.
I1116 10:16:43.310288 46267 MetadataMediator.cpp:68] ::setSimulatorConfiguration : Set new simulator config for scene/stage :  and dataset : default which is currently active dataset.
Using PhysicsManager config:  /home/sparsh/habitat/habitat-sim/./data/default.physics_config.json
I1116 10:16:43.316956 46267 AttributesManagerBase.h:365] <Physics Manager>::createFromJsonOrDefaultInternal : Proposing JSON name : /home/sparsh/habitat/habitat-sim/./data/default.physics_config.json from original name : /home/sparsh/habitat/habitat-sim/./data/default.physics_config.json | This file  exists.
I1116 10:16:43.317085 46267 PhysicsAttributesManager.cpp:26] JSON Configuration File (/home/sparsh/habitat/habitat-sim/./data/default.physics_config.json) based physics manager attributes created and registered.
I1116 10:16:43.317096 46267 MetadataMediator.cpp:68] ::setSimulatorConfiguration : Set new simulator config for scene/stage : ../versioned_data/habitat_test_scenes_1.0/skokloster-castle.glb and dataset : default which is currently active dataset.
I1116 10:16:43.317112 46267 ManagedFileBasedContainer.h:210] <Object Template>::convertFilenameToPassedExt : Filename : data/objects/example_objects changed to proposed object_config.json filename : data/objects/example_objects.object_config.json
W1116 10:16:43.317118 46267 AttributesManagerBase.h:301] <Object Template>::loadAllTemplatesFromPathAndExt : Parsing Object Template : Cannot find data/objects/example_objects as directory or data/objects/example_objects.object_config.json as config file. Aborting parse.
I1116 10:16:43.317122 46267 viewer.cpp:771] Scene Dataset Configuration file location : default | Loading Scene : ../versioned_data/habitat_test_scenes_1.0/skokloster-castle.glb
I1116 10:16:43.317131 46267 MetadataMediator.cpp:68] ::setSimulatorConfiguration : Set new simulator config for scene/stage : ../versioned_data/habitat_test_scenes_1.0/skokloster-castle.glb and dataset : default which is currently active dataset.
Killed
`

![Screenshot from 2021-11-16 10-16-52](https://user-images.githubusercontent.com/90801318/142012963-91e05af9-f76d-4642-bdcd-45cd2cfa662e.png)

2) When I try to run the lighting_setup tutorial with `python3 examples/tutorials/lighting_tutorial.py`, I get the following error:
`ImportError: generic_type: type "SceneNode" referenced unknown base type "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicTranslationRotationScalingTransformation3D<float> >"
`

Thanks for the help!

**Comment by erikwijmans** [comment]
```
installed habitat-sim with conda install habitat-sim withbullet -c conda-forge -c aihabitat. Then I ran 'python3 setup.py --bullet install'.
```

Don't install habitat-sim via conda and then via setup.py. That may end up causing a version mismatch between habitat and magnum (which seems like what happened here). Do only one or the other.

**Comment by sparsh-umd** [comment]
Thanks for the reply @erikwijmans!

When I ran `lighting_setup.py` before installing habitat via `python3 setup.py --bullet install` I was getting something like `system is configured to run bullet but bullet isn't installed`. Hence, I ran the above command with setup.py, hoping that it'd solve the issue (Also, I thought I came across something like 'bullet physics engine doesn't get automatically installed with conda install').

Now, I tried to create a new conda environment & installed habitat-sim only with conda. I was able to run the testing with `habitat-viewer`, but lighting_tutorial.py isn't running. I'm getting a `Segmentation fault (core dumped)` error. The following is the complete terminal output:

WARNING: Logging before InitGoogleLogging() is written to STDERR
I1118 00:03:13.779678 12889 ManagedFileBasedContainer.h:210] <Dataset>::convertFilenameToPassedExt : Filename : default changed to proposed scene_dataset_config.json filename : default.scene_dataset_config.json
I1118 00:03:13.779711 12889 AttributesManagerBase.h:365] <Dataset>::createFromJsonOrDefaultInternal : Proposing JSON name : default.scene_dataset_config.json from original name : default | This file  does not exist.
I1118 00:03:13.779958 12889 AssetAttributesManager.cpp:120] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
I1118 00:03:13.780009 12889 AssetAttributesManager.cpp:120] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I1118 00:03:13.780047 12889 AssetAttributesManager.cpp:120] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
I1118 00:03:13.780071 12889 AssetAttributesManager.cpp:120] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I1118 00:03:13.780082 12889 AssetAttributesManager.cpp:120] Asset attributes (cubeSolid : cubeSolid) created and registered.
I1118 00:03:13.780093 12889 AssetAttributesManager.cpp:120] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I1118 00:03:13.780120 12889 AssetAttributesManager.cpp:120] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
I1118 00:03:13.780143 12889 AssetAttributesManager.cpp:120] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I1118 00:03:13.780156 12889 AssetAttributesManager.cpp:120] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I1118 00:03:13.780166 12889 AssetAttributesManager.cpp:120] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I1118 00:03:13.780184 12889 AssetAttributesManager.cpp:120] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I1118 00:03:13.780198 12889 AssetAttributesManager.cpp:120] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I1118 00:03:13.780205 12889 AssetAttributesManager.cpp:108] ::constructor : Built default primitive asset templates : 12
I1118 00:03:13.780763 12889 SceneDatasetAttributesManager.cpp:36] File (default) not found, so new default dataset attributes created and registered.
I1118 00:03:13.780778 12889 MetadataMediator.cpp:127] ::createSceneDataset : Dataset default successfully created.
I1118 00:03:13.780786 12889 AttributesManagerBase.h:365] <Physics Manager>::createFromJsonOrDefaultInternal : Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json | This file  exists.
I1118 00:03:13.781102 12889 PhysicsAttributesManager.cpp:26] JSON Configuration File (./data/default.physics_config.json) based physics manager attributes created and registered.
I1118 00:03:13.781116 12889 MetadataMediator.cpp:212] ::setActiveSceneDatasetName : Previous active dataset  changed to default successfully.
I1118 00:03:13.781119 12889 MetadataMediator.cpp:183] ::setCurrPhysicsAttributesHandle : Old physics manager attributes  changed to ./data/default.physics_config.json successfully.
I1118 00:03:13.781123 12889 MetadataMediator.cpp:68] ::setSimulatorConfiguration : Set new simulator config for scene/stage : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb and dataset : default which is currently active dataset.
Renderer: AMD RENOIR (DRM 3.42.0, 5.14.8-051408-lowlatency, LLVM 12.0.0) by AMD
OpenGL version: 4.6 (Core Profile) Mesa 21.0.3
Using optional features:
    GL_ARB_vertex_array_object
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_robustness
    GL_ARB_texture_storage
    GL_ARB_invalidate_subdata
    GL_ARB_texture_storage_multisample
    GL_ARB_multi_bind
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_texture_filter_anisotropic
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    mesa-implementation-color-read-format-dsa-explicit-binding
    mesa-dsa-createquery-except-pipeline-stats
    mesa-forward-compatible-line-width-range
I1118 00:03:13.817095 12889 ManagedFileBasedContainer.h:210] <Scene Instance>::convertFilenameToPassedExt : Filename : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb changed to proposed scene_instance.json filename : data/scene_datasets/habitat-test-scenes/van-gogh-room.scene_instance.json
I1118 00:03:13.817118 12889 MetadataMediator.cpp:311] ::getSceneAttributesByName : Dataset : default has no preloaded SceneAttributes or StageAttributes named : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb so loading/creating a new StageAttributes with this name, and then creating a SceneAttributes with the same name that references this stage.
I1118 00:03:13.817127 12889 ManagedFileBasedContainer.h:210] <Stage Template>::convertFilenameToPassedExt : Filename : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb changed to proposed stage_config.json filename : data/scene_datasets/habitat-test-scenes/van-gogh-room.stage_config.json
I1118 00:03:13.817132 12889 AttributesManagerBase.h:365] <Stage Template>::createFromJsonOrDefaultInternal : Proposing JSON name : data/scene_datasets/habitat-test-scenes/van-gogh-room.stage_config.json from original name : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb | This file  does not exist.
E1118 00:03:13.817241 12889 StageAttributesManager.cpp:86] ::registerObjectFinalize : Render asset template handle : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb specified in stage template with handle : data/scene_datasets/habitat-test-scenes/van-gogh-room.glb does not correspond to any existing file or primitive render asset.  Aborting. 
Segmentation fault (core dumped)

**Comment by aclegg3** [comment]
`data/scene_datasets/habitat-test-scenes/van-gogh-room.glb does not correspond to any existing file or primitive render asset. Aborting.`
Looks like you need to download the example assets as described [here](https://github.com/facebookresearch/habitat-sim#testing).

**Comment by sparsh-umd** [comment]
Thanks for the reply @aclegg3! It helps.

I actually ran that command & downloaded the example assets. It got downloaded as `data/versioned_data/habitat_test_scenes_1.0/` & the lighting_tutorial.py expects data as `data/scene_datasets/habitat-test-scenes/`. 
https://github.com/facebookresearch/habitat-sim/blob/3f385c4976dc2f8394f8e3f823ad21ef1d4cecbe/examples/tutorials/lighting_tutorial.py#L58

I changed the above line of code to `data/versioned_data/habitat_test_scenes_1.0/` & it works! You probably want to modify lighting_tutorial.py accordingly.

Thanks!

**Comment by aclegg3** [comment]
Thanks @sparsh-umd, the datasets downloader should be creating `data/scene_datasets/habitat-test-scenes` as a symbolic link to `data/versioned_data/habitat_test_scenes_1.0/ `. Maybe this wasn't working properly on your system? I think your solution of using the absolute path makes sense, but beware other possible issues with tutorial code expecting that symlinks are created and valid.

**Comment by sparsh-umd** [comment]
Thanks for the reply @aclegg3 !

Oh, right! I understand what happened.

I downloaded the dataset on a different machine (The symlinks are working here) & just copied the data from that machine to the current machine I'm running the tutorial on.
