### ISSUE TITLE
Segfault in Viewer Utility

### ISSUE THREAD

**Issue by bigbike** [facebookresearch/habitat-sim#157]
## Steps to reproduce

  1. Compile the code; 
  2. run viewer with a scene without providing the navmesh;
  3.

## Observed Results

   segfault.

## Expected Results

  Viewer should performs as a virtual touring system for the scene.

## Relevant Code

The problem comes from the following line in viewer.cpp
```
const vec3f position = pathfinder_->getRandomNavigablePoint();

```
It segfaults if the pathfinder is not initialized before this line. 

@aclegg3

**Comment by mosra** [comment]
Ran into this a few minutes ago while testing PLY import after the proposed shader cleanup and since it blocks me, I'm opening #161 with a fix.
