### ISSUE TITLE
Installing Habitat-Sim Package via Conda for Windows

### ISSUE THREAD

**Issue by jmeola42** [facebookresearch/habitat-sim#1570]
When I attempted to install Habitat-Sim through conda on my Windows machine, I received the following error:

>conda install habitat-sim withbullet -c conda-forge -c aihabitat
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - habitat-sim

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/aihabitat/win-64
  - https://conda.anaconda.org/aihabitat/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page."

When I went to the anaconda.org page, I found the conda installer for habitat-sim only supports Linux and OSX? Is there a way to install habitat-sim via conda for Windows or should I use pip instead (said it was experimental, so wanted to check first)

**Comment by Skylion007** [comment]
We currently do not support Windows.

**Comment by jmeola42** [comment]
> We currently do not support Windows. It may work on the Windows Subsystem for Linux2 with the newest release of Windows 10, but we have not tested it extensively.

At all or just with conda installation?

**Comment by Skylion007** [comment]
At all.

**Comment by jmeola42** [comment]
Should I install a VM with Linux and try to work on it there? Would that be more reliable?

**Comment by Skylion007** [comment]
Assuming you can give the VM access to the GPU, then yes.

**Comment by jmeola42** [comment]
I'm using VirtualBox and I have an NVidia GeForce GTX 1660 Ti. That should be sufficient for allowing the Virtual Machine access to my GPU, right?

**Comment by jmeola42** [comment]
I guess I haven't found a way of giving the VM access to the GPU, since the AIHabitat Demo doesn't load the images on the Ubuntu VM

**Comment by anas-zafar** [comment]
hi @Skylion007 , do we have windows support now?

**Comment by yaoling1997** [comment]
Sad it doesn't have windows support in 2024.
