### ISSUE TITLE
Trying to run AI Habitat Demo and getting Windowless Context Error

### ISSUE THREAD

**Issue by jmeola42** [facebookresearch/habitat-sim#1579]
I'm trying to run the AI Habitat Demo and I'm getting this error and no image showing up. I'm running on a newly installed VM running Ubuntu.

ManagedContainerBase::convertFilenameToJSON : Filename :  default  changed to proposed JSON configuration filename :  default.scene_dataset_config.json
AttributesManager<T>::createFromJsonOrDefaultInternal  ( Dataset ) : Proposing JSON name :  default.scene_dataset_config.json  from original name :  default  | This file   does not exist.
Asset attributes ( capsule3DSolid  :  capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false ) created  and registered.
Asset attributes ( capsule3DWireframe  :  capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1 ) created  and registered.
Asset attributes ( coneSolid  :  coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true ) created  and registered.
Asset attributes ( coneWireframe  :  coneWireframe_segments_32_halfLen_1.25 ) created  and registered.
Asset attributes ( cubeSolid  :  cubeSolid ) created  and registered.
Asset attributes ( cubeWireframe  :  cubeWireframe ) created  and registered.
Asset attributes ( cylinderSolid  :  cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true ) created  and registered.
Asset attributes ( cylinderWireframe  :  cylinderWireframe_rings_1_segments_32_halfLen_1 ) created  and registered.
Asset attributes ( icosphereSolid  :  icosphereSolid_subdivs_1 ) created  and registered.
Asset attributes ( icosphereWireframe  :  icosphereWireframe_subdivs_1 ) created  and registered.
Asset attributes ( uvSphereSolid  :  uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false ) created  and registered.
Asset attributes ( uvSphereWireframe  :  uvSphereWireframe_rings_16_segments_32 ) created  and registered.
AssetAttributesManager::buildCtorFuncPtrMaps : Built default primitive asset templates :  12
File (default) not found, so new default  dataset attributes created  and registered.
MetadataMediator::createDataset : Dataset  default  successfully created.
AttributesManager<T>::createFromJsonOrDefaultInternal  ( Physics Manager ) : Proposing JSON name :  ./data/default.physics_config.json  from original name :  ./data/default.physics_config.json  | This file   does not exist.
File (./data/default.physics_config.json) not found, so new default  physics manager attributes created  and registered.
AbstractObjectAttributesManager<T>::createObject  ( Stage ) : Making attributes with handle :  /skokloster-castle.glb
ManagedContainerBase::convertFilenameToJSON : Filename :  /skokloster-castle.glb  changed to proposed JSON configuration filename :  /skokloster-castle.stage_config.json
AttributesManager<T>::createFromJsonOrDefaultInternal  ( Stage ) : Proposing JSON name :  /skokloster-castle.stage_config.json  from original name :  /skokloster-castle.glb  | This file   does not exist.
AbstractObjectAttributesManager<T>::createObject  ( Stage ) : Done making attributes with handle :  /skokloster-castle.glb
File (/skokloster-castle.glb) exists but is not a recognized config filename extension, so new default   Stage  attributes created  and registered.
Loading navmesh from  /skokloster-castle.navmesh
Loaded.
Created DrawableGroup:  
Platform::WindowlessEglApplication::tryCreateContext(): cannot create EGL context: EGL_BAD_MATCH
WindowlessContext: Unable to create windowless context

**Comment by erikwijmans** [comment]
Please run again with `export MAGNUM_LOG=verbose MAGNUM_GPU_VALIDATION=ON`. Please as look through https://github.com/facebookresearch/habitat-sim/issues/288 and the issues that reference it.
