### ISSUE TITLE
About environment file

### ISSUE THREAD

**Issue by JiayunjieJYJ** [facebookresearch/habitat-sim#1598]
## ❓ Questions and Help
I want to ask: if I got an environment file in habitat, can I transform it to a 3D file with the form of ".obj + .mtl"?  

Because ".obj + .mtl" file is commonly used in 3D design, and then habitat can cooperate with other simulators.  

Thanks!

**Comment by erikwijmans** [comment]
No, we currently don't support saving out the render scene graph.
