### ISSUE TITLE
how to create navmesh file?

### ISSUE THREAD

**Issue by hpf9017** [facebookresearch/habitat-sim#1601]
## Habitat-Sim version
v0.2.1

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
I have the STP file of a scene, I can transfer to glb file to load in habitat sim.
but how can I generate .navmesh file ?

thank you~

**Comment by aclegg3** [comment]
Hey, @hpf9017. The short answer is to use the [recompute_navmesh()](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#recompute_navmesh) function. For a deeper dive on navmesh configuration and the habitat `Pathfinder` API, check out [this interactive tutorial Colab](https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/main/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb). Specifically, see the `Working with the NavMesh` section.
