### ISSUE TITLE
Habitat 2.0 release date?

### ISSUE THREAD

**Issue by tangyuq** [facebookresearch/habitat-sim#1604]
Any update on the release of the greate Habitat 2.0 specified in https://arxiv.org/pdf/2106.14405.pdf? :)

**Comment by aclegg3** [comment]
Habitat-sim features supporting Habitat 2.0 as described in the paper are already on the `main` branch. For rearrangement tasks and other method related implementations, see the [public stable branch on habitat-lab 751](https://github.com/facebookresearch/habitat-lab/pull/751).
