### ISSUE TITLE
Building error on main

### ISSUE THREAD

**Issue by mmahdavian** [facebookresearch/habitat-sim#1613]
## Habitat-Sim version
main
Ubuntu 16
gcc

Hi. I am trying to build the main version of the habitat-sim with this command "python setup.py build_ext --parallel 5 install". Because I need to use the fairmotion. I am getting following error. I searched a lot for a solution. But I haven't been able to resolve it. I am not sure if it is due to a problem in libglfw3 or not. Do you have any idea about it?
`[ 71%] Linking CXX static library libassimp.a
[ 72%] Linking CXX shared module ../_magnum.cpython-37m-x86_64-linux-gnu.so
[ 72%] Built target assimp
[ 72%] Compiling data resource file /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/build/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/resource_AssimpImporter.cpp
Scanning dependencies of target AssimpImporter
[ 72%] Building CXX object deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/CMakeFiles/AssimpImporter.dir/AssimpImporter.cpp.o
[ 72%] Building CXX object deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/CMakeFiles/AssimpImporter.dir/resource_AssimpImporter.cpp.o
/usr/bin/ld: ../../../../glfw/src/libglfw3.a(context.c.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: ../../../../glfw/src/libglfw3.a(context.c.o): unable to initialize decompress status for section .debug_info
../../../../glfw/src/libglfw3.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/build.make:346: recipe for target 'deps/magnum-bindings/src/python/_magnum.cpython-37m-x86_64-linux-gnu.so' failed
make[2]: *** [deps/magnum-bindings/src/python/_magnum.cpython-37m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:4830: recipe for target 'deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/all' failed
make[1]: *** [deps/magnum-bindings/src/python/magnum/CMakeFiles/magnum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/types.h:59:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:49,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/defs.h:275:45: warning: use of old-style cast [-Wold-style-cast]
 static const ai_real ai_epsilon = (ai_real) 0.00001;
                                             ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/types.h:535:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:49,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/vector3.inl: In member function ‘const aiVector3t<TReal>& aiVector3t<TReal>::operator/=(TReal)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/vector3.inl:157:32: warning: use of old-style cast [-Wold-style-cast]
     const TReal invF = (TReal) 1.0 / f;
                                ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/types.h:538:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:49,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl: In member function ‘aiMatrix3x3t<TReal>& aiMatrix3x3t<TReal>::Transpose()’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:172:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)a2, (TReal&)b1);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:172:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)a2, (TReal&)b1);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:173:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)a3, (TReal&)c1);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:173:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)a3, (TReal&)c1);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:174:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)b3, (TReal&)c2);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix3x3.inl:174:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)b3, (TReal&)c2);
                                    ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:54:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/types.h:539,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:49,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/MathFunctions.h: In function ‘IntegerType Assimp::Math::gcd(IntegerType, IntegerType)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/MathFunctions.h:58:40: warning: use of old-style cast [-Wold-style-cast]
  const IntegerType zero = (IntegerType)0;
                                        ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/types.h:539:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:49,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl: In member function ‘aiMatrix4x4t<TReal>& aiMatrix4x4t<TReal>::Transpose()’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:222:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)b1, (TReal&)a2);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:222:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)b1, (TReal&)a2);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:223:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)c1, (TReal&)a3);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:223:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)c1, (TReal&)a3);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:224:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)c2, (TReal&)b3);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:224:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)c2, (TReal&)b3);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:225:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d1, (TReal&)a4);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:225:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d1, (TReal&)a4);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:226:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d2, (TReal&)b4);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:226:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d2, (TReal&)b4);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:227:24: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d3, (TReal&)c4);
                        ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:227:36: warning: use of old-style cast [-Wold-style-cast]
     std::swap( (TReal&)d3, (TReal&)c4);
                                    ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl: In member function ‘void aiMatrix4x4t<TReal>::DecomposeNoScaling(aiQuaterniont<TReal>&, aiVector3t<TReal>&) const’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/matrix4x4.inl:513:58: warning: use of old-style cast [-Wold-style-cast]
     rotation = aiQuaterniont<TReal>((aiMatrix3x3t<TReal>)_this);
                                                          ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/Logger.hpp:50:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/DefaultLogger.hpp:48,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:66:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/TinyFormatter.h: In copy constructor ‘Assimp::Formatter::basic_formatter<T, CharTraits, Allocator>::basic_formatter(const Assimp::Formatter::basic_formatter<T, CharTraits, Allocator>&)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/TinyFormatter.h:103:31: warning: use of old-style cast [-Wold-style-cast]
         underlying << (string)other;
                               ^
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/scene.h:56:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:73:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h: In function ‘aiReturn aiGetMaterialFloat(const aiMaterial*, const char*, unsigned int, unsigned int, ai_real*)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1437:77: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
     return aiGetMaterialFloatArray(pMat,pKey,type,index,pOut,(unsigned int*)0x0);
                                                                             ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h: In function ‘aiReturn aiGetMaterialInteger(const aiMaterial*, const char*, unsigned int, unsigned int, int*)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1475:79: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
     return aiGetMaterialIntegerArray(pMat,pKey,type,index,pOut,(unsigned int*)0x0);
                                                                               ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h: At global scope:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
     unsigned int* flags         = NULL);
                                       ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1578:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
In file included from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.h:1596:0,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/scene.h:56,
                 from /home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:73:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::Get(const char*, unsigned int, unsigned int, Type*, unsigned int*) const’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:95:38: warning: use of old-style cast [-Wold-style-cast]
         (const aiMaterialProperty**)&prop);
                                      ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:106:33: warning: use of old-style cast [-Wold-style-cast]
         iNum = std::min((size_t)iNum,prop->mDataLength / sizeof(Type));
                                 ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::Get(const char*, unsigned int, unsigned int, Type&) const’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:122:38: warning: use of old-style cast [-Wold-style-cast]
         (const aiMaterialProperty**)&prop);
                                      ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:201:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const float*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:213:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const double*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:225:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const aiUVTransform*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:237:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const aiColor4D*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:249:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const aiColor3D*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:261:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const aiVector3D*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:273:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const int*, unsigned int, const char*, unsigned int, unsigned int)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:285:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = float; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:305:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = double; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:318:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = aiUVTransform; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:331:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = aiColor4t<float>; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:344:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = aiColor3D; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:357:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = aiVector3t<float>; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:370:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl: In member function ‘aiReturn aiMaterial::AddProperty(const TYPE*, unsigned int, const char*, unsigned int, unsigned int) [with TYPE = int; aiReturn = aiReturn]’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/assimp/code/../include/assimp/material.inl:383:43: warning: use of old-style cast [-Wold-style-cast]
     return AddBinaryProperty((const void*)pInput,
                                           ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp: In function ‘Corrade::Containers::String Magnum::Trade::{anonymous}::customMaterialKey(Corrade::Containers::StringView, aiTextureType)’:
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1276:30: warning: case value ‘1001242’ not in enumerated type ‘const aiTextureType’ [-Wswitch]
             #define _f(type) case AssimpOptionalTextureType_ ## type <aiTextureType>::Value: \
                              ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1291:13: note: in expansion of macro ‘_f’
             _f(SHEEN)
             ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1276:30: warning: case value ‘1001243’ not in enumerated type ‘const aiTextureType’ [-Wswitch]
             #define _f(type) case AssimpOptionalTextureType_ ## type <aiTextureType>::Value: \
                              ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1292:13: note: in expansion of macro ‘_f’
             _f(CLEARCOAT)
             ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1276:30: warning: case value ‘1001244’ not in enumerated type ‘const aiTextureType’ [-Wswitch]
             #define _f(type) case AssimpOptionalTextureType_ ## type <aiTextureType>::Value: \
                              ^
/home/mohammad/Mohammad_ws/habitat/test/habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/AssimpImporter/AssimpImporter.cpp:1293:13: note: in expansion of macro ‘_f’
             _f(TRANSMISSION)
             ^
[ 72%] Linking CXX static library libAssimpImporter.a
[ 72%] Built target AssimpImporter
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 472, in <module>
    include_package_data=True,
  File "/home/mohammad/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/mohammad/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/mohammad/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/mohammad/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 262, in run
    self.build_extension(ext)
  File "setup.py", line 372, in build_extension
    [osp.join(CMAKE_BIN_DIR, "cmake"), "--build", self.build_temp] + build_args
  File "/home/mohammad/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--', '-j5']' returned non-zero exit status 2.`

**Comment by erikwijmans** [comment]
I haven't seen that error before, but it looks like your glfw lib is corrupted. Try reinstalling glfw.
