### ISSUE TITLE
Rendering errors in habitat_sim

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-sim#165]
## Steps to reproduce

I have been trying to reproduce these errors for almost a day now, but they just seem to happen a bit arbitrarily. 

## Observed Results

The rendering gets messed up in some episodes. Here, is an example of correctly rendered images. The first image is the RGB rendering, the 2nd image is blank (can be ignored), the 3rd and 4th rendering are top-down egocentric maps that I generated, and the 5th view is the TopDownMap rendering.
![image](https://user-images.githubusercontent.com/31301440/63368301-3b804d00-c343-11e9-85d9-c2817209367e.png)

In the same environment, a different episode led to rendering like this:
![image](https://user-images.githubusercontent.com/31301440/63368232-20154200-c343-11e9-815e-030d18c75b83.png)

- The issue seems to happen in habitat_simulator itself and it gets fixed before I can figure out why it's happening. 
- The same episode on consistently worked on one machine (with a Titan V GPU), but failed on another machine with Tesla K40s. However, it does happen on the Titan V as well in other cases (the above images were from Titan V). 

I realize that this is quite vague, but I'm not clear how to be more specific. Is this something that others have experienced? Could you suggest some alternate ways by which I can attempt to reproduce this and provide better information?

**Comment by aclegg3** [comment]
May be hardware specific driver issues. Backend rendering tech has changed significantly since this issue was open. Please re-open or create new issue if this crops up again.
