### ISSUE TITLE
How to ignore the following warning?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/habitat-sim#1674]
warning come from the code [ManagedPhysicsObjectBase.h:324](https://github.com/facebookresearch/habitat-sim/blob/91f322cf72ec225742e54095728680aeed6e4ac8/src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h#L320)

```
W0221 16:34:14.326818 26834 ManagedPhysicsObjectBase.h:324] This object no longer exists. Please delete any variable references.
```
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.1

Habitat-Sim: v0.2.1

![image](https://user-images.githubusercontent.com/34536352/154963739-ff2bbc4b-89cd-4d17-8c2e-251f3150d594.png)

**Comment by aclegg3** [comment]
Hey @yyf17,

This output indicates that you are holding and making API calls to a `ManagedObject` (e.g. a [ManagedRigidObject](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ManagedRigidObject.html)) which has already been deleted or gone out of scope. Likely you are updating the position or state of a visualization object or something which is added and removed without the object reference being removed from a local cache in your script.

While I suggest you find this bug, if you just want to silence logger output, you can do so as described in our [configurable logging API docs](https://aihabitat.org/docs/habitat-sim/logging.html).

**Comment by yyf17** [comment]
@aclegg3 Thank you！
