### ISSUE TITLE
how to set object fixed?

### ISSUE THREAD

**Issue by hpf9017** [facebookresearch/habitat-sim#1676]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

Hi, I want to set an object fixed, so that it can not be moved by the anent?
How can I set this property of an object?

Thank you!

**Comment by dhruvbatra** [comment]
https://aihabitat.org/docs/habitat-sim/managed-rigid-object-tutorial.html
