### ISSUE TITLE
Image Segmentation not working

### ISSUE THREAD

**Issue by MishraIN** [facebookresearch/habitat-sim#1680]
I am using a pair of .glb and .navmesh for our data. File .glb is generated using assimp. I am following tutorial here but I am just blue screen for segmentation part. 

https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb 
 
For my data I am getting "House has 0 levels, 0 regions and 0 objects". How can I achieve something like this?

House has 1 levels, 10 regions and 187 objects House center:[-2.7928104 1.3372791 -1.5051247] dims:[17.57338 2.9023619 8.8595495] Level id:0, center:[-3.1573648 1.33728 -1.5051247], dims:[16.69967 2.90236 8.8595495] Region id:0_0, category:bedroom, center:[-8.821845 1.2594094 -2.691538 ], dims:[4.163309 2.5356622 4.2073426] Object id:0_0_0, category:wall, center:[-8.86568 1.2817702 -2.73879 ], dims:[4.5891 2.581481 4.591819] Object id:0_0_1, category:ceiling, ....

**Comment by jturner65** [comment]
Can you please share the semantic text file, that contains the data for the expected levels, regions and objects in the scene?

**Comment by MishraIN** [comment]
I am missing that file in my data. I do see .house file in the mp3d_example/17DRP5sb8fy data, is that the semantic text file?

**Comment by jturner65** [comment]
Yes, that is one format for semantic scene descriptor text data.  [Here is the habitat sim parser that reads the file, to get the expected format.](https://github.com/facebookresearch/habitat-sim/blob/49afedddcfc7c90746bd67d236b08849ef69922d/src/esp/scene/Mp3dSemanticScene.cpp#L105) .  

There are other formats that are understood as well by habitat-sim, such as [Replica](https://github.com/facebookresearch/habitat-sim/blob/49afedddcfc7c90746bd67d236b08849ef69922d/src/esp/scene/ReplicaSemanticScene.cpp#L41) and [Gibson](https://github.com/facebookresearch/habitat-sim/blob/49afedddcfc7c90746bd67d236b08849ef69922d/src/esp/scene/GibsonSemanticScene.cpp#L34) - the links will direct you to the parsing code that should inform you of the expected format.

**Comment by MishraIN** [comment]
Sorry, I am so new to this. I am using matterport dataset generated by iPhone, how do I build semantic text file? Do we have to manually label it or is there pre trained models which can be used for creating semantic text file which can identify common objects?

**Comment by dhruvbatra** [comment]
Habitat just renders the semantic annotations, we don't generate them. For 3D scans you capture yourself, there are no semantics available because automatically providing voxel-level 3D annotations is an open research problem.

**Comment by jturner65** [comment]
No problem! I hope I can help :).  Synthesizing semantic annotations is an open research problem, to the best of my knowledge, particularly in a 3d environment.

One thing to consider is that these annotations in Habitat-Sim are not really images, they are regions on a 3d mesh/graph- Habitat-sim now supports both vertex annotations or texture annotations (i.e. going into blender and painting the annotation color onto the mesh).

**Comment by jturner65** [comment]
Remember, you need to also provide a text file that will provide the mappings from the colors found on the mesh to the semantic ids/categories, etc.

**Comment by MishraIN** [comment]
I see. I will try with a small space with only few objects.
