### ISSUE TITLE
Can't setup habitat-sim (CalledProcessError)

### ISSUE THREAD

**Issue by nargenziano** [facebookresearch/habitat-sim#1695]
### I'm using ###
- Ubuntu 18.04 LTS (WSL Windows 10)
- miniconda3
### Steps I've followed ###
```
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim; git checkout tags/v0.1.5; 
pip install -r requirements.txt; 
```
### Error ###
When trying to run `python setup.py install`, I get the following:

![image](https://user-images.githubusercontent.com/91571630/158794737-348943b8-e63b-4542-a9c1-5373114952e7.png)

Thanks for any advice.

**Comment by erikwijmans** [comment]
> Ubuntu 18.04 LTS (WSL Windows 10)

We don't support Windows/WSL unfortunately. Anecdotally we've heard of people getting it to work but we are unable to provide support.
