### ISSUE TITLE
Conda install with cuda

### ISSUE THREAD

**Issue by Hoyyyaard** [facebookresearch/habitat-sim#1696]
How can I install haibitat-sim through conda with cuda?
It doesnt work when I install with headless and It will report"must build habitat-sim with cuda for gpu2gpu-transfer"

**Comment by dhruvbatra** [comment]
Too little information to help you. Please consider asking on slack to the community.

**Comment by Zhongxyyyy** [comment]
> How can I install haibitat-sim through conda with cuda? It doesnt work when I install with headless and It will report"must build habitat-sim with cuda for gpu2gpu-transfer"

Have you found the solution? I met the same question as well

**Comment by Zhongxyyyy** [comment]
> "must build habitat-sim with cuda for gpu2gpu-transfer"

Thanks for you reply. I installed the habitat-sim with conda headless, but when I run task relaed code, it will report"must build habitat-sim with cuda for gpu2gpu-transfer". So should I need install from source and add ''--with-cuda'' to solve it?

**Comment by erikwijmans** [comment]
Yep

**Comment by Zhongxyyyy** [comment]
> Yep

Unfortunately, it didn't work in my computer, I will open a new issue to ask for help.

**Comment by xwaiyy123** [comment]
> > Yep
> 
> Unfortunately, it didn't work in my computer, I will open a new issue to ask for help.

我遇到了相同的问题，这个问题你解决了吗？

**Comment by Zhongxyyyy** [comment]
> 
解决了，最终是用source来build的，本地机器一直没弄好，用远程的服务器重建了一个环境搞好了

**Comment by Zhongxyyyy** [comment]
> > > Yep
> > 
> > 
> > Unfortunately, it didn't work in my computer, I will open a new issue to ask for help.
> 
> 我遇到了相同的问题，这个问题你解决了吗？

解决了，最终是用source来build的，本地机器一直没弄好，用远程的服务器重建了一个环境搞好了

**Comment by labixiaochao** [comment]
> > > > Yep
> > > 
> > > 
> > > Unfortunately, it didn't work in my computer, I will open a new issue to ask for help.
> > 
> > 
> > 我遇到了相同的问题，这个问题你解决了吗？
> 
> 解决了，最终是用source来build的，本地机器一直没弄好，用远程的服务器重建了一个环境搞好了

I used this command conda install habitat-sim=0.2.4 withbullet -c conda-forge -c aihabitat to install habitat-sim, but encountered the same error as yours when setting the gpu_gpu parameter. May I ask how you solved it? File "/home/simu/miniconda3/envs/habitat/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/simulator.py", line 609, in _initialize_sensor
assert cuda_enabled, "Must build habitat sim with cuda for gpu2gpu-transfer"
AssertionError: Must build habitat sim with cuda for gpu2gpu-transfer
Error executing job with overrides: []
Traceback (most recent call last):
File "/home/simu/vln/vlfm/vlfm/run.p
