### ISSUE TITLE
No data/datasets/pointnav directory

### ISSUE THREAD

**Issue by retoc71586** [facebookresearch/habitat-sim#1699]
## Habitat-Sim version
v0.2.0

## ❓
I am trying to run the some of the example scripts but I always get errors regarding the habitat-test-scenes like:
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/pointnav/habitat-test-scenes/v1/train/train.json.gz'

In fact my 'data' directory contains only:    objects        replica_cad     scene_datasets  versioned_data , no datasets folder.
I can find that folder in /habitat-lab/configs/datasets/pointnav but it only contains .yaml files

**Comment by dhruvbatra** [comment]
`python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes habitat_test_pointnav_dataset` should do it. Looks like we dropped those links from the readme as we transition to using rearrangement tasks as the demo. 

@erikwijmans -- can you please send a quick PR to the readme?
