### ISSUE TITLE
ModuleNotFoundError: No module named 'magnum.platform.glfw'; 'magnum.platform' is not a package

### ISSUE THREAD

**Issue by abstinentcode** [facebookresearch/habitat-sim#1702]
python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
Traceback (most recent call last):
  File "examples/viewer.py", line 18, in <module>
    from magnum.platform.glfw import Application
ModuleNotFoundError: No module named 'magnum.platform.glfw'; 'magnum.platform' is not a package
-------------------------------------------------------------
 When I run the viewer.py, I got this issue. Can anyone have some ideas to fix it? thanks a lot.

**Comment by SarthakJaindebugger** [comment]
I'm facing the same issue too.
I installed habitat-sim and lab via this link: https://github.com/facebookresearch/sound-spaces/issues/80
I tried it on both Ubuntu and Google Colab
