### ISSUE TITLE
Customize the shortest path algorithm

### ISSUE THREAD

**Issue by rosanom** [facebookresearch/habitat-sim#1708]
Hi there! About computing shortest paths, I was wondering if there is a way to customize the algorithm to find it. I need paths that take into account the distance from obstacles, so that a shortest path follower agent can avoid crawling along them. Could you suggest me which classes are responsible for computing the shortest path and how can I modify them? I had a look to the [test_greedy_follower.py](https://github.com/facebookresearch/habitat-sim/blob/main/tests/test_greedy_follower.py) python script and to the [ECCV navigation tutorial notebook](https://github.com/facebookresearch/habitat-sim/blob/69d41c9c9fa66d060e1ea674211c7f47e5e59b17/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb) but it is not clear to me where the `PathFinder` and `ShortestPath` classes are located and what is their role...

Thank you in advance!

**Comment by aclegg3** [comment]
Hey @rosanom,

The source code for NavMesh computation and shortest path heuristics are written in C++ and located entirely in [the nav module](https://github.com/facebookresearch/habitat-sim/tree/main/src/esp/nav). You are welcome to fork the code and try out your own modifications.

Sounds like you want to add a heuristic that the best path doesn't need to be shortest, but should balance path length with distance to objects. This would require a custom implementation, possibly in C++ if you want to modify existing code.

Another simpler option if you just want a bit more distance from the objects with default sim features is to grow the agent radius (i.e., shrink the navmesh). This has the side effect of possibly closing off tight spaces, however, so it would be a balance.
