### ISSUE TITLE
DISPLAY not detected in headless run

### ISSUE THREAD

**Issue by hoongtong** [facebookresearch/habitat-sim#1711]
## Habitat-Sim version
v0.2.1

## Question

I made a docker image from base `jupyter/tensorflow-notebook`, where I installed the libgl libraries myself (e.g. libnvidia-gl) with presumably the correct version. I installed habitat-sim using the following command:

```
RUN mamba install -y -c aihabitat habitat-sim withbullet headless
```

However, when I try to create a simulator object, the kernel crashes with the message: `DISPLAY not detected. For headless systems, compile with --headless for EGL support`. This leads me to believe that it is not running in headless mode? FYI: I am running it a notebook.

**Comment by erikwijmans** [comment]
We don't support mamba currently. That support will be added in the v0.2.2 release.
