### ISSUE TITLE
How to get collision information between agent and scene?

### ISSUE THREAD

**Issue by hpf9017** [facebookresearch/habitat-sim#1721]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
We try to use [ContactPointData](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ContactPointData.html),
but it doesn't work.
Is there anything wrong with the way we used or we should use other sensor ? Thank you very much!

**Comment by aclegg3** [comment]
Hey, @hpf9017, I'd need to see how you use it to know if there is an issue or bug.

FYI: the ContactPointData should be updated by calls to Simulator.[step_world](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#step_world)() and Simulator.[perform_discrete_collision_detection](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#perform_discrete_collision_detection)(). 
It can be queried with Simulator.[get_physics_contact_points](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#get_physics_contact_points)(). 
It should contain any contacts recorded by Bullet collision detection between active collision shapes as specified by the configured collision groups (see [CollisionGroupHelper](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.CollisionGroupHelper.html)).
