### ISSUE TITLE
Question about the 3d object bounding box

### ISSUE THREAD

**Issue by zfang399** [facebookresearch/habitat-sim#1722]
Hi! I want to ask a question about the 3d object bounding box, as I'm having trouble getting it correct and the documentation on this seems to just provide the input and output shapes (and not explanation of the variables).

The `obb` has several properties: `center`, `sizes`, `rotation`, `local_to_world`, `world_to_local`. I'm trying to extract the 3d box with the representation of its x/y/z lengths and a transformation from world coordinates to camera coordinates.

1. I was able to fuse the pointcloud from observations taken at different agent poses, which means the extrinsics were correct (i got the extrinsics by combining the position and rotation of the agent state). So I first tried to get the similar "extrinsics" for those boxes by combing its center position and rotation, but the visualized boxes look off. I have two questions regarding this: (1) is the obb position and agent position in the same coord system and representation? (2) is the obb rotation and agent rotation in the same coord system and representation? The obb rotation was given as a numpy array while the agent rotation a quaternion. 
2. What does local_to_world and world_to_local mean? What is the `local` frame here? 

Thanks a lot!!

**Comment by erikwijmans** [comment]
1. Center is in the agent's coordinate frame. The rotation takes points from the coordinate frame where the OBB is an AABB and rotates them to the agent's coordinate frame. So you don't need to rotate center as that's already in the agent's coordinate frame.
2. The local frame here refers to the coordinate frame where the OBB is an AABB with its center at (0.5, 0.5, 0.5) and sizes (1, 1, 1). AKA when the OBB is the unit cube (min=(0, 0, 0), max=(1, 1, 1)). You can get the 8 corners of the OBB in the agent's coordinate frame by take the 8 corners of the unit cube and transforming them by `local_to_world`.
