### ISSUE TITLE
Support customizing scene lighting in Replica dataset

### ISSUE THREAD

**Issue by mengsong16** [facebookresearch/habitat-sim#1733]
Dear Habitat Team,

I would like to change the scene lighting of office 3 in the [Replica dataset](https://github.com/facebookresearch/Replica-Dataset) by calling `set_light_setup()` function, and found that there is no direct support in the Habitat simulator in this situation. The attempts I have made include:
1. Convert the `replica_v1/office_3/mesh.ply` to `replica_v1/office_3/habitat/mesh_semantic.glb` using `assimp export`
2. The Habitat simulator loads the mesh file `mesh_semantic.glb` successfully but loses track of the texture files in `replica_v1/office_3/textures`.

- This has ensured that the simulator loaded the glb file instead of ply file to avoid failing `NO_LIGHT_KEY assertion` in `ResourceManager.cpp` when importing a ply file and trying to change its lighting.

3. After importing the scene file into the simulator, I tried to set up a new point light by calling `set_light_setup()`, but it failed and the scene is dark. 

- I have successfully set the same point light in the test scene `scene_datasets/habitat-test-scenes/van-gogh-room.glb` by the same code.

It seems that converting ply to glb by `assimp` cannot keep the texture files in the glb and lose some rendering keys in glb to enable the lighting setup. What can I do to keep the textures in glb and enable the change of scene lighting for the Replica dataset? What changes do I need to make in the glb file to make this happen? 

Thanks for your help!

**Comment by erikwijmans** [comment]
We don't support lighting with the PTex replica meshes and it would be a lot of effort to add this since the ptex meshes use a custom shader.
