### ISSUE TITLE
Get camera's y-coordinate in interactive viewer

### ISSUE THREAD

**Issue by arjung128** [facebookresearch/habitat-sim#1737]
## Habitat-Sim version
v0.2.0

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

Is there a way to get the camera's y-coordinate when walking around a scene using habitat-sim? I know that pressing `q` prints the agent's location, but this does not seem to change when 'z' or 'x' are pressed to move the agent up/down. Thanks!

**Comment by aclegg3** [comment]
Hey @arjung128,

Each Sensor object is attached to a SceneNode with its own transformation. 

For example, in the [ECCV Advanced Features Colab](https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/main/examples/tutorials/colabs/ECCV_2020_Advanced_Features.ipynb), "Motion Tracking Camera" scenario, the Sensor is queried from the Simulator by name.

In typical configurations the Sensor is attached to a parent Agent SceneNode. In the C++ viewer we provide the convenience function: `esp::sensor::CameraSensor& getAgentCamera()` to get the primary RGB Sensor object from which `.node()` references the SceneNode. Every [SceneNode](https://aihabitat.org/docs/habitat-sim/classesp_1_1scene_1_1SceneNode.html) has local and absolute transformation properties.
