### ISSUE TITLE
Lighting modifications - sim.set_light_setup() isn't working

### ISSUE THREAD

**Issue by yaelbenoren** [facebookresearch/habitat-sim#1738]
Hi 
I understand there is a problem with the lighting tutorial (issue #1450)
I saw in the comments that adding `cfg.sim_cfg.override_scene_light_defaults = True` does enable changing the lighting to `habitat_sim.gfx.DEFAULT_LIGHTING_KEY`. However, I am trying to create my own lighting and fail.

`cfg = make_cfg(sim_settings)`
`cfg.sim_cfg.scene_light_setup = habitat_sim.gfx.DEFAULT_LIGHTING_KEY`
`cfg.sim_cfg.override_scene_light_defaults = True`
`sim = habitat_sim.Simulator(cfg)` #creates default lighting
`light_setup = sim.get_light_setup()`
`light_setup.append(LightInfo(vector=[1.0, 2.0, 1.6, 1.0], model=LightPositionModel.Global))`
`sim.set_light_setup(light_setup, "my_scene_lighting")`
`cfg.sim_cfg.scene_light_setup = "my_scene_lighting"`
`sim.reconfigure(cfg)`

However, lighting doesn't change. sim.get_light_setup() != light_setup
What am I doing wrong?

Optimally I would like to use lighting from a JSON file but I can't find an example for it. Is there a way to do this? 
Thank you

**Comment by aclegg3** [comment]
Hey @yaelbenoren,

Looks like you are editing the same `cfg.sim_cfg` already used to create the initial simulator. When the reconfigure checks if `cfg ==  sim.cfg` it will always return true and opt out of the reconfigure early. Your code would probably work if you make a new `cfg2 = make_cfg(sim_settings)` and then change your light setup.

Regarding a file based approach. Take a look at [ReplicaCAD](https://aihabitat.org/datasets/replica_cad/). The synthetic dataset here includes lighting config files in `configs/lighting/` imported by the SceneDatasetConfig (e.g. `replicaCAD.scene_dataset_config`) and then referenced in the SceneInstance files (e.g. `configs/scenes/apt_0.scene_instance.json`).
