### ISSUE TITLE
Change background of scene

### ISSUE THREAD

**Issue by yaelbenoren** [facebookresearch/habitat-sim#1739]
Is there a way to change the background of a scene so that is is not black? 
![frame_000193](https://user-images.githubusercontent.com/83911779/166150004-e34b16ae-4567-45c5-a7c7-a0ccf33f8c22.jpg)

**Comment by aclegg3** [comment]
@yaelbenoren we support single color overrides per-sensor via the [`clear_color` property in the VisualSensorSpec](https://aihabitat.org/docs/habitat-sim/habitat_sim.sensor.VisualSensorSpec.html#clear_color).

If you want a more complex skybox you'll need to texture a cube or sphere yourself in an external editor and load it into the scene like other objects.
