### ISSUE TITLE
ArmEEAction does not support grasping?

### ISSUE THREAD

**Issue by arjung128** [facebookresearch/habitat-sim#1770]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

Is there any reason why `ArmEEAction` does not support grasping, unlike `ArmAction`?

**Comment by aclegg3** [comment]
@ASzot may have more context here.

**Comment by aclegg3** [comment]
All robotics wrappers and grasping support is now in habitat-lab.
