### ISSUE TITLE
Can only be installed via conda when python is 3.8

### ISSUE THREAD

**Issue by 20481535** [facebookresearch/habitat-sim#1778]
## Habitat-Sim version
vx.x.x or main?

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Main branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## Steps to Reproduce

1.
2.
3.

 Please note that without a minimal working example to reproduce the bug, we may not be able to help you.

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/main/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python src_python/habitat_sim/utils/collect_env.py
```

 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - GPU models and configuration:
 - CUDA version:
 - PIP/conda dependencies packages versions
 - Any other relevant information:

**Comment by dhruvbatra** [comment]
Not seeing a well-formed question. Please read the README.
