### ISSUE TITLE
issues when creating two image extractor

### ISSUE THREAD

**Issue by Derry-Xing** [facebookresearch/habitat-sim#1784]
## Habitat-Sim version
amin

## 🐛 Bug

/envs/habitat/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

## Steps to Reproduce

    train_extractor = ImageExtractor(args.datadir, output=['rgba'], pose_extractor_name="panorama_extractor", mode="train")
    test_extractor = ImageExtractor(args.datadir, output=['rgba'], pose_extractor_name="panorama_extractor", mode="test")

**Comment by aclegg3** [comment]
We don't support multiple instances of the Simulator object (instanced within the ImageExtractor) within the same python process. You may want to try a multiprocess approach or run your train and test extractors sequentially.
