### ISSUE TITLE
[Linux] CgltfImporter.h:36:10: fatal error: 'Magnum/configure.h' file not found

### ISSUE THREAD

**Issue by jaraujo98** [facebookresearch/habitat-sim#1785]
## Habitat-Sim version: latest main

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Main branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

While running either `build.sh` or `build_js.sh` with the latest main on Linux the following error occurs (lines before the error were cherry-picked for context from the output of `build.sh`)

```
-- Found MagnumPlugins: /home/.../habitat-sim/src/deps/magnum-plugins/src  found components: BasisImporter GltfImporter PrimitiveImporter StanfordImporter StbImageImporter StbImageConverter 
(...)
-- Found MagnumPlugins: /home/.../habitat-sim/src/deps/magnum-plugins/src  found components: GltfImporter StbImageImporter StbImageConverter
(...)
[ 13%] Built target CgltfImporter-dependencies
(...)
[ 13%] Built target GltfImporter-dependencies
(...)
[ 19%] Building CXX object deps/magnum-plugins/src/MagnumPlugins/CgltfImporter/CMakeFiles/CgltfImporter.dir/CgltfImporter.cpp.o
(...)
[ 50%] Compiling data resource file /home/.../habitat-sim/build_js/deps/magnum/src/MagnumPlugins/AnySceneImporter/resource_AnySceneImporter.cpp
In file included from /home/.../habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/CgltfImporter/CgltfImporter.cpp:28:
/home/.../habitat-sim/src/deps/magnum-plugins/src/MagnumPlugins/CgltfImporter/CgltfImporter.h:36:10: fatal error: 'Magnum/configure.h' file not found
#include <Magnum/configure.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

## Steps to Reproduce

Steps to reproduce the behavior (on my end, since the CI machines seem to have no problem with this):

1. Clone the latest habitat-sim
2. `./build.sh` or `./build_js.sh`

 Please note that without a minimal working example to reproduce the bug, we may not be able to help you.

## Expected behavior

Habitat-sim compiling without errors.

## Additional context

Compiling works fine with commit hash 0e552d74c3f6c996b64d0a0f71240e19829ac9bf. This seems to be caused by PRs #1776 and #1777, which rename CgltfImporter.

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/main/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python src_python/habitat_sim/utils/collect_env.py
```

ENVIRONMENT INFO:
Platform: Linux-5.4.0-117-generic-x86_64-with-debian-bullseye-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.17
Mac version: 
Python version: 3.7.13
Architecture: 64bit 
Win version:    
System OS: Linux
Release: 5.4.0-117-generic
Version: #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022
Operational System: linux
GCC version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CMAKE version: cmake version 3.14.0

**Comment by Skylion007** [comment]
I ran into this exact problem and cleaning the build directory fixed it.
