### ISSUE TITLE
How to create K

### ISSUE THREAD

**Issue by 20481535** [facebookresearch/habitat-sim#1786]
## ❓ Questions and Help

K = np.array([
    [1 / np.tan(hfov / 2.), 0., 0., 0.],
    [0., 1 / np.tan(hfov / 2.), 0., 0.],
    [0., 0.,  1, 0],
    [0., 0., 0, 1]])

Is above code correct to create K? What is the unit of 1 / np.tan(hfov / 2.)? meter? SHould I change it to mm?

**Comment by dhruvbatra** [comment]
Please read the documentation: 
https://aihabitat.org/docs/habitat-lab/view-transform-warp.html

**Comment by stavyadatta** [comment]
Hi! Hope you are well! How do i get this hfov value! The hfov method described seems outdated

Thank you!
