### ISSUE TITLE
import maps module in colab 

### ISSUE THREAD

**Issue by yaofeng11** [facebookresearch/habitat-sim#1789]
## Habitat-Sim version
v0.2.1
I wonder that in colab maps module has been used in top-down view, I just download habitat-sim versionv0.2.1. But I can not fond maps.py file in the whole habitat-sim file, however it is in the habitat-lab file,  which I mean if I want to use maps module do I have to
install the habitat-lab file?

**Comment by aclegg3** [comment]
Hey @yaofeng11,

Yeah, the Colab imports `maps` from Habitat-lab: `from habitat.utils.visualizations import maps` to draw the map. You'll need to install lab in your conda environment to import that feature. 

However, as noted by the tutorial, you can get the map data array from sim without lab:
> You can get the topdown map directly from the Habitat-sim API with *PathFinder.get_topdown_view*.
    This map is a 2D boolean array
    `sim_topdown_map = sim.pathfinder.get_topdown_view(meters_per_pixel, height)`
