### ISSUE TITLE
add_object function seems to fail with Habitat_sim 0.2.2

### ISSUE THREAD

**Issue by srkiyengar** [facebookresearch/habitat-sim#1792]
Hi,

I have a working code with Habitat_sim version 0.2.0 where I have been successfully using the "add_object" function to introduce rigid object into the Simulator. I updated my version to 0.2.2 and I now get the following error:

AttributeError: 'Simulator' object has no attribute 'add_object'

Is it related to the change? -"[Breaking Change][Refactor]--Remove all object manipulation functions from Simulator #1574".

If you have a sample python sample on how to add objects, it will be highly appreciated.

Thanks!

**Comment by aclegg3** [comment]
Hey, @srkiyengar.

Exactly right, we've removed the `Simulator` based object manipulation functions and moved them into the [RigidObjectManager](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.RigidObjectManager.html) instead. The [ECCV tutorials](https://aihabitat.org/tutorial/2020/) are updated with the new API for reference. Specifically check out `Habitat-Sim for Interaction`.

Short answer to your specific query:
`sim.get_rigid_object_manager().add_object_by_template_id()`
