### ISSUE TITLE
The functions of pf.get_bounds()

### ISSUE THREAD

**Issue by derrick-xwp** [facebookresearch/habitat-sim#1796]
## ❓ Questions and Help
What kind of bounds are returned form def [get_bounds](https://aihabitat.org/docs/habitat-sim/habitat_sim.nav.PathFinder.html#get_bounds)(self, /)?

**Comment by derrick-xwp** [comment]
Is it a bound in top-down view or world coordinate?

**Comment by erikwijmans** [comment]
They are in world coordinates
