### ISSUE TITLE
About agent's location

### ISSUE THREAD

**Issue by yaofeng11** [facebookresearch/habitat-sim#1800]
## Habitat-Sim version
v0.2.2

Dear there:
  I'm using habitat-sim for my paper experiment. I wonder that after the agent takes one step, how I can get the top-down map with agent? I mean that if it exist any API to directly gain agent's position(x,y,z), or any exist API to show the top-down map with agent.
For example, I take the action sim.step("move_forward") when the start position is (0,0,0), I can use API like get_state() to directly get the location(0.25,0,0)

**Comment by erikwijmans** [comment]
Please look through the tutorials: https://aihabitat.org/docs/habitat-sim/. The first colab answers this.
