### ISSUE TITLE
Starting agent in a navigable position

### ISSUE THREAD

**Issue by soyeonm** [facebookresearch/habitat-sim#1804]
## Habitat-Sim version
v0.1.5 (but I am asking in general)

Hello, I have a question about knowing a valid "start position" of the agent. 
I know that there are episodes data provided by the "navigation challenges" (for example, gibson's episode data here: https://github.com/devendrachaplot/Object-Goal-Navigation), and there are "starting poses" in these data. 

I wonder if I can get a valid starting pose (that is inside the house and not under the floor, etc), from a random scene (for gibson, hm3d, or other data). I have seen this post: https://github.com/devendrachaplot/Object-Goal-Navigation, but it looks like we can't get a valid "z" position (height) of where the agent is standing, with this method.

By any chance, is there a way to figure out a valid starting position in a ".glb"?

Thank you all the time!

**Comment by dhruvbatra** [comment]
Please read the "Habitat-Sim Basics for Navigation" tutorial: https://aihabitat.org/tutorial/2020/

And in general, please consider going through the tutorials.
