### ISSUE TITLE
Color topdown map

### ISSUE THREAD

**Issue by jingjing00kk** [facebookresearch/habitat-sim#1805]
Hello,
I have a question about top down map. We can receive a black and white top down map using function "get_topdown_view".
Can I get color topdown map like this? And how?
![topdown_floors](https://user-images.githubusercontent.com/108913029/177937919-7606be93-3cbb-458c-b01e-95673ddd3128.png)
Thank you!

**Comment by jingjing00kk** [comment]
Thank you~

**Comment by jingjing00kk** [comment]
Thank you @aclegg3 

But when I edit the hm3d .glb file with Blender, there are only meshes. Textures are not shown in the Blender (the mode of Blender is changed to texture mode, and I have test other .glb files, and the textures were displayed well.) . Also I tried 3dmax, micrsoft 3D viewer, the .glb files could not be opened by these softwares. Are the .glb formats  in the HM3d datasets specialized or different with normal .glb files or the version of the software should be a some special one?

**Comment by aclegg3** [comment]
@jingjing00kk, there are multiple downloads for HM3D. The habitat download is basis compressed for more efficient use in simulation. Blender won't load those. The other formats should contain uncompressed textures for the same scenes which can be loaded in Blender.
