### ISSUE TITLE
no example/viewer.py

### ISSUE THREAD

**Issue by WWenMing** [facebookresearch/habitat-sim#1824]
I have done :

conda create -n habitat python=3.7 cmake=3.14.0
conda activate habitat
conda install habitat-sim withbullet -c conda-forge -c aihabitat

My problem is the habitat-sim which installed by conda is where , "path/to/habitat" --> what means the "path"
and I find one hatibta-sim in "/home/.conda/envs/habi/lib/python3.7/site-packets",but it doesn't include the folder "example",so I can't find the example/viewer.py to test
![图片](https://user-images.githubusercontent.com/52840809/182514691-c7700c8d-605b-46fe-9e69-53042836cd73.png)

I appreciately you can help me , thank you .

**Comment by aclegg3** [comment]
Hey @WWenMing, if you want the examples you'll need to clone the repo and run them from that directory.
You can run the examples from a conda install, but as you noted they don't come with the conda package.

**Comment by dwei-k** [comment]
hello, @aclegg3 
when I run the `python examples/viewer.py --scene Data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
` I met 
Traceback (most recent call last):
  File "examples/viewer.py", line 19, in <module>
    from magnum import shaders, text
ImportError: cannot import name 'text' from 'magnum'

**Comment by jemo-mh** [comment]
> hello, @aclegg3 when I run the `python examples/viewer.py --scene Data/scene_datasets/habitat-test-scenes/skokloster-castle.glb ` I met Traceback (most recent call last): File "examples/viewer.py", line 19, in from magnum import shaders, text ImportError: cannot import name 'text' from 'magnum'

How did you solve this problem?

**Comment by dwei-k** [comment]
@jemo-mh hi, it has been a long time for me, I remeber I didn't clone the stable tag of this repo at that time, when I clone the right branch, it was solved.

**Comment by jemo-mh** [comment]
> @jemo-mh hi, it has been a long time for me, I remeber I didn't clone the stable tag of this repo at that time, when I clone the right branch, it was solved.

Thanks for your help! I will try it.
Which method did you install habitat-sim??
Did you use pip install?,  Anaconda? or setup.py method?

**Comment by Youmna-H** [comment]
Any updates on how to solve the  ImportError: cannot import name 'text' from 'magnum' error? I am facing the same issue.
