### ISSUE TITLE
Is it possible to have a dynamic modifed scene by habitat-sim?

### ISSUE THREAD

**Issue by anavuongdin** [facebookresearch/habitat-sim#1827]
Dear authors,
First of all, I appreciate your simulator and I find them interesting.
I'm currently trying to interact with your simulator via https://github.com/facebookresearch/habitat-sim/blob/main/examples/viewer.py. I tried to edit the scene by modifying the file "skokloster-castle.glb". I added some objects and your simulator ran pretty well.
However, when I added some moving objects to the scene (skokloster-castle.glb), nothing happened.
My question is as follows: Is there any way to edit some scenes with dynamic objects (for example, a running dog)?
Thanks in advance.

**Comment by aclegg3** [comment]
Hey @anavuongdin, 

We do support object dynamics via the SceneDataset configs. These can be rigid objects or articulated objects. See the [ECCV tutorials](https://aihabitat.org/tutorial/2020/) for the details and examples.

However, it sounds like what you really want is to animate a mesh. Unfortunately, we don't currently support non-rigid animation in Habitat-sim. You can control the trajectory of objects or the positions of joints with the simulation API, but not a keyframed mesh animation exported to glTF.

**Comment by anavuongdin** [comment]
Uploading habitat-sim-2022-08-12_09.34.17.mp4…
Hi, I tried to add moving objects via your documentation https://aihabitat.org/docs/habitat-sim/managed-rigid-object-tutorial.html.
However, when I integrated these codes into file: `examples/viewer.py` to see if I can interact with dynamic objects, they were completely frozen as in the video.
Can you please help me? Thank you!

**Comment by aclegg3** [comment]
Hey @anavuongdin,

Looks like maybe you have not installed Habitat-sim with Bullet physics support. Did you all `--bullet` to the build?
e.g. `python setup.py install --bullet` from source or `conda install habitat-sim withbullet -c conda-forge -c aihabitat` from conda install.

**Comment by aclegg3** [comment]
Hey, @anavuongdin 

Objects in `MotionType::KINEMATIC` are directly controlled by the user. If you want your objects to respond to collisions with other objects in the space, they will need to be `MotionType::DYNAMIC`.
