### ISSUE TITLE
Incomplete semantic annotations via habitat_sim.utils.datasets_download

### ISSUE THREAD

**Issue by sagadre** [facebookresearch/habitat-sim#1828]
## Habitat-Sim version
Habitat-Sim 0.2.2

## 🐛 Bug

As per this [README](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d), I am running the following command to retrieve `hm3d_minival`, which should come with semantic annotations:
`python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_minival`

However, many of the scenes do not have `*.semantic.txt` or `*.semantic.glb` files. Here is the resulting folder tree:
<img width="501" alt="Screen Shot 2022-08-10 at 3 05 56 PM" src="https://user-images.githubusercontent.com/16566743/184028960-744ef5ff-4497-4c8c-9f7d-00ca1b0c43a7.png">

**Comment by aclegg3** [comment]
Hey @sagadre, 
At this point we have not annotated the full dataset of 1000 scenes, so this is expected. The scene dataset file: `hm3d_annotated_basis.scene_dataset_config.json` should isolate scenes with annotations from the other scenes in the dataset.
