### ISSUE TITLE
conda the special version

### ISSUE THREAD

**Issue by Dora238** [facebookresearch/habitat-sim#1839]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
my problem is how to use the conda to install the special version habitat-sim
like habitat-sim 0.1.7  and the commit version == ee75ba5312fff02aa60c04f0ad0b357452fc2edc
what's the command should input?
thank you

**Comment by dhruvbatra** [comment]
From our readme: 

> Conda packages for older versions can installed by explicitly specifying the version, e.g. conda install habitat-sim=0.1.6 -c conda-forge -c aihabitat
