### ISSUE TITLE
Some data size error of the depth sensor

### ISSUE THREAD

**Issue by doudoudou1999** [facebookresearch/habitat-sim#1856]
When I run the run.py of the depth sensor, there is always an error like:

Traceback (most recent call last):
  File "ss_baselines/av_nav/run.py", line 101, in <module>
    main()
  File "ss_baselines/av_nav/run.py", line 95, in main
    trainer.train()
  File "/home/gyx/sound-spaces/ss_baselines/av_nav/ppo/ppo_trainer.py", line 267, in train
    rollouts.observations[sensor][0].copy_(batch[sensor])
RuntimeError: The size of tensor a (5) must match the size of tensor b (128) at non-singleton dimension 1

And then I print the size of rollouts.observations[sensor][0] and batch[sensor] I found:

rollouts.observations[sensor][0].shape torch.Size([5, 128, 128, 1])
batch[sensor].shape torch.Size([5, 128, 128, 1, 1])

It seems that the size of these two data is diffrent, so how to fix this problem?

Thank you very much!

**Comment by dhruvbatra** [comment]
@ChanganVR
