### ISSUE TITLE
ReplicaCAD: Semantic IDs for Background

### ISSUE THREAD

**Issue by BIT-DYN** [facebookresearch/habitat-sim#1872]
First of all thanks for such a great job.

I have a problem with generating semantic images using the ReplicaCAD dataset.
Backgrounds such as the ground, walls and cabinets in the semantic image do not get any semantic id.
Is there any way to distinguish different categories of backgrounds?

![frame000000](https://user-images.githubusercontent.com/74786439/192211912-20af4360-bed2-4442-913e-09e8dce9dd7a.png)
![semanticmyvis000010](https://user-images.githubusercontent.com/74786439/192212030-807eb7dc-38f3-4f64-b604-0934b7b27034.png)

**Comment by aclegg3** [comment]
Hey @BIT-DYN,

You are correct that ReplicaCAD objects have semantic ids assigned, but the stage does not. Adding annotations here isn't on our current development roadmap.

One method for you to add them would be to bake the semantic ids into per-vertex colors in the stage .glb assets. You could paint these or manually assign them in Blender. Best bet is to create a separate semantic asset with these colors baked in.

Alternatively, you can assign semantic ids to any SceneNode programmatically (see [the docs](https://aihabitat.org/docs/habitat-sim/habitat_sim.scene.SceneNode.html#semantic_id)). If you knew which nodes in the SceneGraph corresponded with particular objects this could be done at scene load time per-stage.
