### ISSUE TITLE
Habitat_sim install script for Colab is failing - new error

### ISSUE THREAD

**Issue by srkiyengar** [facebookresearch/habitat-sim#1884]
## Habitat-Sim version

A new error is showing when executing 
curl -L https://raw.githubusercontent.com/facebookresearch/habitat-sim/master/examples/colab_utils/colab_install.sh | NIGHTLY=false bash -s

It was working well as of October 2, 2022.

## 🐛 Bug

Habitat_sim install fails during this part of the installation:
Cloning into 'habitat-sim'...
remote: Enumerating objects: 925, done.
remote: Counting objects: 100% (925/925), done.
remote: Compressing objects: 100% (865/865), done.
remote: Total 925 (delta 82), reused 543 (delta 46), pack-reused 0
Receiving objects: 100% (925/925), 44.23 MiB | 22.20 MiB/s, done.
Resolving deltas: 100% (82/82), done.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './habitat_baselines/**/requirements.txt'
python: can't open file 'setup.py': [Errno 2] No such file or directory
An error occured during the installation of Habitat-sim or Habitat-Lab.

## Steps to Reproduce
**Executing the script in colab is sufficient.**

!curl -L https://raw.githubusercontent.com/facebookresearch/habitat-sim/master/examples/colab_utils/colab_install.sh | NIGHTLY=false bash -s

**I have attached all the messages from the execution of the script. The error is at the very end of the long attached file "install_error.pdf", the last few lines.**
[install_error.pdf](https://github.com/facebookresearch/habitat-sim/files/9700061/install_error.pdf)

**Comment by aclegg3** [comment]
Thanks @srkiyengar. The file was moved in lab. The above PR should fix this.
