### ISSUE TITLE
How to get the extrinsic camera matrices?

### ISSUE THREAD

**Issue by cbyan1003** [facebookresearch/habitat-sim#1899]
I use replica dataset on habitat-sim headless mode.
Follow the ImageExtractor Docs, I get the rgba, depth, semantic images. But how to get the extrinsic camera matrices? I would be grateful if you could give me some demos.

**Comment by cbyan1003** [comment]
And my goal is to get the RGBA, depth, semantc image, and get the camera extrinsic parameter matrix at the moment the image was taken.

**Comment by aclegg3** [comment]
Hey @cbyan1003,

Check this previous thread #1795, there are some pointers to examples and API details.
