### ISSUE TITLE
Semantic mask of an desired object which includes the occluded parts

### ISSUE THREAD

**Issue by eric-xw** [facebookresearch/habitat-sim#19]
It would be very useful if the simulator can support a function that provides the semantic mask of an object at a specific view, including both its visible and occluded parts.

It can then  further enable various tasks related to computer vision like amodal recognision/detection.

**Comment by aclegg3** [comment]
Configurable semantic id enabled by #668. To get occluded part, simply re-configure the simulator with "NONE" scene and render with only the object in question to create a mask.
