### ISSUE TITLE
examples not availables

### ISSUE THREAD

**Issue by MichaelGaliciaZ** [facebookresearch/habitat-sim#1902]
I can't use any examples from the examples folder, when I install using conda, the directory is not downloaded.

**Comment by aclegg3** [comment]
Hey @MichaelGaliciaZ,

Correct, the examples directory is not part of the habitat-sim module. You'll need to clone the repo to get those files. However, you can use them with a conda install, so no need to install from source. Just be sure to conda install the same version you clone locally (e.g. `main` branch for conda nightly)

**Comment by MichaelGaliciaZ** [comment]
Ok

It's necessary install nightly version!

Now is working :)
