### ISSUE TITLE
Cannot detect added object via depth sensor

### ISSUE THREAD

**Issue by XiaohanLei** [facebookresearch/habitat-sim#1908]
Hi!

I put the banana.glb into skokloster-castle.glb, and I can successfully get the rgb image seeing the banana inside. But when I want to detect the banana by using depth sensor, I get nothing. By the way, I change the banana's scale to 10 times for better visualization.

Could anyone give me some suggestions.

Thanks!

**Comment by aclegg3** [comment]
That's very odd. Are your depth and rgb sensors configured with the same transformation? Could you attach the corresponding depth and rgb images to this issue?

**Comment by XiaohanLei** [comment]
Thanks for your quick reply, I carefully checked the configuration file and I can get the view from the depth sensor.
