### ISSUE TITLE
there is no data/objects/locobot data inside this folder

### ISSUE THREAD

**Issue by frischzenger** [facebookresearch/habitat-sim#1914]
## Habitat-Sim version
main

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Main branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## Steps to Reproduce

1.python -m habitat_sim.utils.datasets_download --uids habitat_example_objects --data-path /path/to/data/
2.python path/to/habitat-sim/examples/tutorials/nb_python/managed_rigid_object_tutorial.py
3.error because of can not find data/objects/locobot_merged.object_config.json

## System Info
```

 - Linux
 - PyTorch1.12.0
 - Python 3.6:
 - GPU GTX1080TI:
 - CUDA 11.3:
 - PIP/conda dependencies packages versions

**Comment by aclegg3** [comment]
Hey @frischzenger,

The downloader string from the tutorial is 
```
python -m habitat_sim.utils.datasets_download --uids habitat_example_objects locobot_merged --data-path path/to/data/
```
This includes 2 uids. You're missing the `locobot_merged` uid here.
