### ISSUE TITLE
FRL_INSTANCE_MESH is no longer used in the simulator and should be deprecated.

### ISSUE THREAD

**Issue by bigbike** [facebookresearch/habitat-sim#192]
## Problem
 FRL_INSTANCE_MESH is for the initial scan of the apartments, and it is replaced by mesh_semantic.ply in the public released replica dataset. Such model can be loaded using our generic instance mesh loader.

Thus, it should be deprecated.

More details: #190 

Search
```
FRL_INSTANCE_MESH 
```

**Comment by msbaines** [comment]
Fixed by #191
