### ISSUE TITLE
Cannot download habitat test scenes in Qatar

### ISSUE THREAD

**Issue by alper111** [facebookresearch/habitat-sim#1942]
## Habitat-Sim version
v0.2.2

## 🐛 Bug
The following command gives 403 http response:
`python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes --data-path habitat_data`
more specifically, the below http request returns 403:
`wget --continue http://dl.fbaipublicfiles.com/habitat/objects_v0.2.zip`

## Steps to Reproduce

1. Create a conda environment and install `habitat-sim` as suggested in the README file.
2. Run `python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes --data-path habitat_data`

## Expected behavior

We should be able to download datasets from the public link.

## Additional context

For what it's worth, if there is any regional restriction, I am currently in Qatar. I *can* download the dataset from my computer in Turkey. Is there some sort of boycott?

## System Info
ENVIRONMENT INFO:
Platform: Linux-5.15.0-46-generic-x86_64-with-debian-bookworm-sid
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.10
Mac version: 
Python version: 3.7.12
Architecture: 64bit ELF
Win version:    
System OS: Linux
Release: 5.15.0-46-generic
Version: 49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022
Operational System: linux
GCC version: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
CMAKE version: cmake version 3.14.0
NVIDIA-SMI: 
```
Fri Nov 18 15:50:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P3    18W /  N/A |    661MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
Pip packages versions:
Conda packages versions:

**Comment by aclegg3** [comment]
Hey @alper111, looking into this. Stay tuned.
