### ISSUE TITLE
`python setup.py install --headless --with-cuda --cmake`   error

### ISSUE THREAD

**Issue by dwei-k** [facebookresearch/habitat-sim#1944]
I run `rm -rf build` and  `python setup.py install --headless --with-cuda --cmake`
and errors:
setup.py:419: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  assert StrictVersion(
setup.py:421: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("3.6"), "Must use python3.6 or newer"
running install
/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/examples
copying examples/settings.py -> build/lib.linux-x86_64-cpython-38/examples
copying examples/ab_test.py -> build/lib.linux-x86_64-cpython-38/examples
copying examples/__init__.py -> build/lib.linux-x86_64-cpython-38/examples
copying examples/example.py -> build/lib.linux-x86_64-cpython-38/examples
copying examples/benchmark.py -> build/lib.linux-x86_64-cpython-38/examples
copying examples/demo_runner.py -> build/lib.linux-x86_64-cpython-38/examples
creating build/lib.linux-x86_64-cpython-38/tests
copying tests/test_profiling_utils.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_sensors.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_greedy_follower.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_pyrobot_noisy_controls.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_light_setup.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_semantic_scene.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_agent.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_robot_wrapper.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_snap_point.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_random_seed.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_physics.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_navmesh.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/conftest.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_utils.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_simulator.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/__init__.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_configs.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_physics_benchmarking.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_compare_profiles.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_examples.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_data_extraction.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_attributes_managers.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_noise_models.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_gfx.py -> build/lib.linux-x86_64-cpython-38/tests
copying tests/test_controls.py -> build/lib.linux-x86_64-cpython-38/tests
creating build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/metadata.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/sim.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/scene.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/errors.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/simulator.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/geo.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/registry.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/logging.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/attributes.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/gfx.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/physics.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/attributes_managers.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
copying habitat_sim/sensor.py -> build/lib.linux-x86_64-cpython-38/habitat_sim
creating build/lib.linux-x86_64-cpython-38/habitat_sim/bindings
copying habitat_sim/bindings/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/bindings
creating build/lib.linux-x86_64-cpython-38/habitat_sim/nav
copying habitat_sim/nav/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/nav
copying habitat_sim/nav/greedy_geodesic_follower.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/nav
creating build/lib.linux-x86_64-cpython-38/habitat_sim/sensors
copying habitat_sim/sensors/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors
copying habitat_sim/sensors/sensor_suite.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors
creating build/lib.linux-x86_64-cpython-38/habitat_sim/agent
copying habitat_sim/agent/agent.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent
copying habitat_sim/agent/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent
creating build/lib.linux-x86_64-cpython-38/habitat_sim/robots
copying habitat_sim/robots/fetch_robot.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/robots
copying habitat_sim/robots/robot_interface.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/robots
copying habitat_sim/robots/mobile_manipulator.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/robots
copying habitat_sim/robots/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/robots
creating build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/compare_profiles.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/gfx_replay_utils.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/validators.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/collect_env.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/profiling_utils.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/common.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/viz_utils.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/manager_utils.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
copying habitat_sim/utils/datasets_download.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils
creating build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/redwood_depth_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/sensor_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/no_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/poisson_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/gaussian_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/speckle_noise_model.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
creating build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
copying habitat_sim/agent/controls/object_controls.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
copying habitat_sim/agent/controls/controls.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
copying habitat_sim/agent/controls/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
copying habitat_sim/agent/controls/default_controls.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
copying habitat_sim/agent/controls/pyrobot_noisy_controls.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/agent/controls
creating build/lib.linux-x86_64-cpython-38/habitat_sim/utils/data
copying habitat_sim/utils/data/data_extractor.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils/data
copying habitat_sim/utils/data/pose_extractor.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils/data
copying habitat_sim/utils/data/data_structures.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils/data
copying habitat_sim/utils/data/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/utils/data
/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'habitat_sim.sensors.noise_models.data' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'habitat_sim.sensors.noise_models.data' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'habitat_sim.sensors.noise_models.data' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'habitat_sim.sensors.noise_models.data' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
creating build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data
copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data
running build_ext
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.1.105
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- The LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example).
-- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/lib
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Found Corrade: /root/Projects/PONI/dependencies/habitat-sim/src/deps/corrade/src  found components: Containers rc Utility 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for glob.h
-- Looking for glob.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for libunwind.h
-- Looking for libunwind.h - not found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for pwd.h
-- Looking for pwd.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/syscall.h
-- Looking for sys/syscall.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for syscall.h
-- Looking for syscall.h - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for ucontext.h
-- Looking for ucontext.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for unwind.h
-- Looking for unwind.h - found
-- Looking for C++ include ext/hash_map
-- Looking for C++ include ext/hash_map - found
-- Looking for C++ include ext/hash_set
-- Looking for C++ include ext/hash_set - found
-- Looking for C++ include ext/slist
-- Looking for C++ include ext/slist - found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Looking for C++ include tr1/unordered_set
-- Looking for C++ include tr1/unordered_set - found
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Looking for C++ include unordered_set
-- Looking for C++ include unordered_set - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned __int16
-- Check size of unsigned __int16 - failed
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Performing Test HAVE_NO_DEPRECATED
-- Performing Test HAVE_NO_DEPRECATED - Success
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for get_static_proc_name in unwind
-- Looking for get_static_proc_name in unwind - not found
-- Looking for UnDecorateSymbolName in dbghelp
-- Looking for UnDecorateSymbolName in dbghelp - not found
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN - Success
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP - Success
-- Performing Test HAVE_RWLOCK
-- Performing Test HAVE_RWLOCK - Failed
-- Performing Test HAVE___DECLSPEC
-- Performing Test HAVE___DECLSPEC - Failed
-- Performing Test STL_NO_NAMESPACE
-- Performing Test STL_NO_NAMESPACE - Failed
-- Performing Test STL_STD_NAMESPACE
-- Performing Test STL_STD_NAMESPACE - Success
-- Performing Test HAVE_USING_OPERATOR
-- Performing Test HAVE_USING_OPERATOR - Success
-- Performing Test HAVE_NAMESPACES
-- Performing Test HAVE_NAMESPACES - Success
-- Performing Test HAVE_GCC_TLS
-- Performing Test HAVE_GCC_TLS - Success
-- Performing Test HAVE_MSVC_TLS
-- Performing Test HAVE_MSVC_TLS - Failed
-- Performing Test HAVE_CXX11_TLS
-- Performing Test HAVE_CXX11_TLS - Success
-- Performing Test HAVE_ALIGNED_STORAGE
-- Performing Test HAVE_ALIGNED_STORAGE - Success
-- Performing Test HAVE_LOCALTIME_R
-- Performing Test HAVE_LOCALTIME_R - Success
-- Shared libraries disabled
-- Looking for ZLIB...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found ZLIB: optimized;/usr/lib/x86_64-linux-gnu/libz.so;debug;/usr/lib/x86_64-linux-gnu/libz.so
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Build an import-only version of Assimp.
CMake Warning (dev) at /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (rt) does
  not match the name of the calling package (RT).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  deps/assimp/cmake-modules/FindRT.cmake:19 (find_package_handle_standard_args)
  deps/assimp/code/CMakeLists.txt:1013 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found rt: /usr/lib/x86_64-linux-gnu/librt.so  
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD STEP
-- Disabled importer formats:
-- Enabled exporter formats:
-- Disabled exporter formats: 3DS ASSBIN ASSXML COLLADA OBJ OPENGEX PLY FBX STL X X3D GLTF 3MF ASSJSON STEP
-- Found Assimp: assimp  
-- Found PythonInterp: /opt/conda/envs/poni/bin/python (found suitable version "3.8.5", minimum required is "3.6") 
-- Bindings being generated for python at /opt/conda/envs/poni/bin/python
-- pybind11 v2.7.0 
-- Found PythonInterp: /opt/conda/envs/poni/bin/python (found version "3.8.5") 
-- Found PythonLibs: /opt/conda/envs/poni/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
CMake Error at /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  deps/magnum/CMakeLists.txt:263 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/Projects/PONI/dependencies/habitat-sim/build/CMakeFiles/CMakeOutput.log".
See also "/root/Projects/PONI/dependencies/habitat-sim/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 440, in <module>
    setup(
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/conda/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 247, in run
    self.build_extension(ext)
  File "setup.py", line 332, in build_extension
    subprocess.check_call(
  File "/opt/conda/envs/poni/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/Projects/PONI/dependencies/habitat-sim/build/lib.linux-x86_64-cpython-38/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/opt/conda/envs/poni/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=OFF', '-DTARGET_HEADLESS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_WITH_VHACD=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=ON', '-DBUILD_BASIS_COMPRESSOR=OFF', '/root/Projects/PONI/dependencies/habitat-sim/src']' returned non-zero exit status 1.

Really need help, thank you very much

**Comment by aclegg3** [comment]
Hey @dwei-k,

Looks like a couple of system configuration issues at first glance.

1. Looks like OpenGL libraries not found and may not be installed or exposed:
```
Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
OPENGL_INCLUDE_DIR)
```
You might try (2) from [the install steps](https://github.com/facebookresearch/habitat-sim/blob/main/BUILD_FROM_SOURCE.md#build-from-source) or equivalent on your system. 

2. Looks like some CMAKE checks are failing. Honestly not sure how significant this is:
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
...
-- Check size of unsigned int16 - failed
...
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
...
-- Performing Test HAVE_RWLOCK - Failed
...
``` and a few more

**Comment by dwei-k** [comment]
thank you very much 
I think my docker's configuration was not correct, I'll try to solve it with your advice
