### ISSUE TITLE
tools/gen_gibson_semantics.sh: line 28: tools/../build/utils/datatool/datatool: No such file or directory

### ISSUE THREAD

**Issue by dwei-k** [facebookresearch/habitat-sim#1948]
'git clone --branch stable https://github.com/facebookresearch/habitat-sim.git'

'cd habitat'

'pip install -r requirements.txt'

'python setup.py install --headless --with-cuda'

'tools/gen_gibson_semantic.sh <path> <path> <path>'

then encountered `tools/gen_gibson_semantics.sh: line 28: tools/../build/utils/datatool/datatool: No such file or directory`

I found that there is no `utils` in `build` and there is a file `utils/datatool` in `src`

**Comment by LIUQI-creat** [comment]
Hello, I performed the same operation and I also encountered this problem. Have you solved it ？Thank you very much! @dwei-k 
@likethesky

**Comment by dwei-k** [comment]
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
conda activate your_env
python setup.py build --build-datatool

**Comment by LIUQI-creat** [comment]
> 

Thanks for your timely reply! I will follow your advice.
