### ISSUE TITLE
habitat-sim problem: Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found 

### ISSUE THREAD

**Issue by FutureGoingOn** [facebookresearch/habitat-sim#1963]
When I want to try another code, I must install the **haistat-sim** first, but I encounter a big bug. I followed the issue in the [**haistat sim No.288** ](https://github.com/facebookresearch/habitat-sim/issues/288), but it did not solve my problem. Who has some good suggestions?

**I follow the codes (version 0.1.7):**

```
conda install -c aihabitat -c conda-forge habitat-sim=0.1.7 headless

git clone --branch v0.1.7 git@github.com:facebookresearch/habitat-lab.git

python -m pip install -r requirements.txt
python -m pip install -r habitat_baselines/rl/requirements.txt
python -m pip install -r habitat_baselines/rl/ddppo/requirements.txt
python setup.py develop --all

wget http://dl.fbaipublicfiles.com/habitat/habitat-test-scenes.zip
unzip habitat-test-scenes.zip

python examples/example.py
```

**Then get the following errors:**

> I1010 18:31:04.590993 11476 SceneGraph.h:93] Created DrawableGroup:
Platform::WindowlessEglApplication::tryCreateContext(): unable to find EGL device for CUDA device 0
WindowlessContext: Unable to create windowless context

**OR**

> I1207 08:31:49.998020  1190 SceneGraph.h:93] Created DrawableGroup: 
Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found, likely a driver issue; enable --magnum-gpu-validation to see additional info
WindowlessContext: Unable to create windowless context

**Also follow the codes: (version stable)**

```
conda create -n habitat python=3.7 cmake=3.14.0

conda install habitat-sim withbullet headless -c conda-forge -c aihabitat

git clone --branch stable https://github.com/facebookresearch/habitat-lab.git

python examples/example_pointnav.py
```

**Then get the following errors:**

> [23:28:21:354663]:[Metadata] SceneDatasetAttributesManager.cpp(261)::loadAndValidateMap : navmesh_instances Value : navmeshes/v3_sc4_staging_18.navmesh not found on disk as absolute path or relative to data/replica_cad
> [23:28:21:354688]:[Metadata] SceneDatasetAttributesManager.cpp(261)::loadAndValidateMap : navmesh_instances Value : navmeshes/v3_sc4_staging_19.navmesh not found on disk as absolute path or relative to data/replica_cad
> [23:28:21:354715]:[Metadata] SceneDatasetAttributesManager.cpp(261)::loadAndValidateMap : navmesh_instances Value : navmeshes/v3_sc4_staging_20.navmesh not found on disk as absolute path or relative to data/replica_cad
> [23:28:21:354761]:[Metadata] SceneDatasetAttributesManager.cpp(35)::createObject : JSON Configuration File (data/replica_cad/replicaCAD.scene_dataset_config.json) based dataset attributes created  and registered.
> [23:28:21:354771]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset data/replica_cad/replicaCAD.scene_dataset_config.json successfully created.
> [23:28:21:354783]:[Metadata] MetadataMediator.cpp(217)::setActiveSceneDatasetName : Attempt to create new dataset data/replica_cad/replicaCAD.scene_dataset_config.json   succeeded. Currently active dataset : data/replica_cad/replicaCAD.scene_dataset_config.json
> [23:28:21:354791]:[Metadata] MetadataMediator.cpp(175)::setCurrPhysicsAttributesHandle : Old physics manager attributes  changed to ./data/default.physics_config.json successfully.
> [23:28:21:354801]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : data/replica_cad/configs/scenes/v3_sc2_staging_10.scene_instance.json and dataset : data/replica_cad/replicaCAD.scene_dataset_config.json which is currently active dataset.
> Platform::WindowlessEglApplication::tryCreateContext(): unable to find EGL device for CUDA device 0
> WindowlessContext: Unable to create windowless context

**The following are all the differences I can understand between PC and server's docker:**

with `**ldconfig -N -v | grep libEGL**`, **In the server's docker:**

>  /sbin/ldconfig.real: Can't stat /usr/local/cuda/compat/lib: No such file or directory
> /sbin/ldconfig.real: Path `/usr/local/cuda/lib64' given more than once
> /sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib: No such file or directory
> /sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib64: No such file or directory
> /sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
> /sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvcuvid.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libcuda.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libvdpau_nvidia.so.440.100 is empty, not checked.
>         libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
>         libEGL.so.1 -> libEGL.so.1.0.0
>         libEGL_nvidia.so.0 -> libEGL_nvidia.so.470.141.03

**BUT in the PC:**

> /sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link
> /sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.23.so is the dynamic linker, ignoring
>         libEGL.so.1 -> libEGL.so.1.1.0
>         libEGL_nvidia.so.0 -> libEGL_nvidia.so.440.44

It seems to be a problem from this difference? but when use driver version 440, the bug is same. 
1. I can confirm that the version of NVIDIA driver is suitable, cuda is also OK, since I can run other CNN-related codes well.
2. In fact, I can run habitat **correctly in my PC,** but I have always encountered this error in docker of my server. 
3. I have tried multiple versions of the NVIDIA driver (440, 450, 470) and cuda (10.1, 10.2, 11.0, 11.2), as well as some possible dependent lib versions, such as libgl in my server, following [**haistat sim No.288** ](https://github.com/facebookresearch/habitat-sim/issues/288) .

Anyone has some good solutions, please help me. Thanks a lot!

**Comment by yimengli46** [comment]
Hi @FutureGoingOn, have you fixed the problem?
I run into the exact same error when running on Docker.
