### ISSUE TITLE
Gfx replay record in c++ habitat-viewer

### ISSUE THREAD

**Issue by Dongmingo** [facebookresearch/habitat-sim#1967]
## Habitat-Sim version
v0.2.3

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

I'm trying to save a camera motion into .json in cpp habitat-sim
What I've done so far is build from scratch followed by document, and use comand below

my environment: 
    intel mac OS Monterey v12.1

```
python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes --data-path test_dataset
./build/viewer --gfx-replay-record-filepath test.json ./test_dataset/scene_datasets/habitat-test-scenes/apartment_1.glb
```

Interactive simulator is successfully loaded, but when I press 'r' to write a replay of the simulated frames, the result 'test.json' only contains the starting location and empty brackets to others like below.

test.json
{"keyframes":[{"loads":[{"type":1,"filepath":"./test_dataset/scene_datasets/habitat-test-scenes/apartment_1.glb","frame":{"up":[0.0,0.0,1.0],"front":[0.0,1.0,0.0],"origin":[0.0,0.0,0.0]},"virtualUnitToMeters":1.0,"forceFlatShading":true,"splitInstanceMesh":true,"shaderTypeToUse":"material","hasSemanticTextures":false}],"creations":[{"instanceKey":0,"creation":{"filepath":"./test_dataset/scene_datasets/habitat-test-scenes/apartment_1.glb","isStatic":true,"isRGBD":true,"isSemantic":true,"isTextureSemantic":false,"lightSetupKey":"no_lights"}}],"stateUpdates":[{"instanceKey":0,"state":{"absTransform":{"translation":[0.0,0.0,0.0],"rotation":[1.0,0.0,0.0,0.0]},"semanticId":0}}]},{},{},{},{},{},{},{},{},{},{},{}]}

Is it under development of saving replays in viewer?

My final goal is to make hand-held like rgbd videos in HM3D dataset. And I'm trying to use replay scripts.
 Is there any alternative way to recommend?

**Comment by aclegg3** [comment]
Hey @Dongmingo,

By default gfx replay does not record the agent's position as part of the replay keyframe. 

However, there is functionality to add your own transforms to the replay frame with [Recorder](https://aihabitat.org/docs/habitat-sim/classesp_1_1gfx_1_1replay_1_1Recorder.html).[addUserTransformToKeyframe](https://aihabitat.org/docs/habitat-sim/classesp_1_1gfx_1_1replay_1_1Recorder.html#aa161d06d04cd44aab0efe13b70a85a9e). 
You could, for example add the agent's transform during the viewer's keyframe recording step at [line 1688](https://github.com/facebookresearch/habitat-sim/blob/4ed8d04021ec7c0c4ad33ad441a3a46163f029ff/src/utils/viewer/viewer.cpp#LL1688C34-L1688C34):
```
recorder->addUserTransformToKeyframe("agent", agentBodyNode_->translation(), agentBodyNode_->rotation());
```

To use this later, you would then set the camera agent's transform from the keyframes with the [Player](https://aihabitat.org/docs/habitat-sim/classesp_1_1gfx_1_1replay_1_1Player.html).[getUserTransform](https://aihabitat.org/docs/habitat-sim/classesp_1_1gfx_1_1replay_1_1Player.html#ae00fe078c60ac740b96de5506ebbba39) function.

@eundersander feel free to correct me if I'm wrong here. :slightly_smiling_face:
