### ISSUE TITLE
How to save a scene after adding objects in python?

### ISSUE THREAD

**Issue by adrshsrvstv** [facebookresearch/habitat-sim#1978]
I can see #1568 which had added functionality to save a scene in c++. Is there an equivalent function for this in python? How should I use it if I am doing all of rest of the processing in python?

Larger context: I want to add objects to existing scenes so as to create a new benchmark. My plan is to add those objects at spcific coordinates in the simulator in python, save the scene and load the scene when running the benchmark.

**Comment by aclegg3** [comment]
Hey @adrshsrvstv,

Your plan sounds reasonable to me.

The C++ viewer is calling the Simulator.[saveCurrentSceneInstance](https://aihabitat.org/docs/habitat-sim/classesp_1_1sim_1_1Simulator.html#a7c698b20deb634e605c7e74e2aa44ea5) function.
The python equivalent is Simulator.[save_current_scene_config](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#save_current_scene_config-0968a) which will write a `scene_instance.json` config file that can be added to your SceneDataset and used to re-instantiate the simulator in saved state.
