### ISSUE TITLE
Cannot run 'Habitat-sim Basics for Navigation' Colab (Installation cell not working) 

### ISSUE THREAD

**Issue by JaechangKo** [facebookresearch/habitat-sim#1981]
https://colab.research.google.com/github/facebookresearch/habitat-lab/blob/master/examples/tutorials/colabs/Habitat_Lab.ipynb
When I run the colab above, Habitat_baseline is missing.  

ModuleNotFoundError: No module named 'habitat_baselines'

**Comment by dhruvbatra** [comment]
https://github.com/facebookresearch/habitat-sim/issues/1965 and https://github.com/facebookresearch/habitat-sim/pull/1966
