### ISSUE TITLE
enableMaterials result in crashes when simulating

### ISSUE THREAD

**Issue by YYDreamzure** [facebookresearch/habitat-sim#1998]
## Habitat-Sim version
v0.2.3

I have issues running the Habitat-sim simulator with materials. 
Sample code I was using: [minimal.example.py ](https://github.com/facebookresearch/sound-spaces/blob/main/examples/minimal_example.py). 
The original setting is:
**audio_sensor_spec.enableMaterials = False**
I had no issues running this successfully
But when I changed it to:
**audio_sensor_spec.enableMaterials = True**
with
**audio_sensor.setAudioMaterialsJSON("/path/to/data/mp3d_material_config.json")**

The jupyter kernel died and when I run in the terminal, the following error was reported:
**Assertion resourceDict_.count(filename) > 0 failed at /path/to/habitat-sim/src/esp/assets/ResourceManager.cpp:2995
Aborted (core dumped)**

Please advice how I can solve this issue. Thank you in advance!

**Comment by sreeharshaparuchur1** [comment]
Hey @YYDreamzure, 

I have faced this issue too and recently the maintainer of the soundspaces repo has listed the same as a known issue over [here](https://github.com/facebookresearch/sound-spaces/blob/main/INSTALLATION.md). 

The best solution would be to set that variable to False.

**Comment by ChanganVR** [comment]
Hi @YYDreamzure this is mostly because you don't have the semantic files for the dataset you are using. Please check if you could find the required semantic files.

**Comment by YYDreamzure** [comment]
@ChanganVR Many thanks for the advice! I used the hm3d sample and the semantic files came in a separate folder. The problem went away after I put them together with the .glb file.
