### ISSUE TITLE
How could I find the Matterport3D (MP3D) dataset used in habitat?

### ISSUE THREAD

**Issue by GuoPingPan** [facebookresearch/habitat-sim#2040]
## Habitat-Sim version
v0.1.7
## ❓ Questions and Help

How could I find the Matterport3D (MP3D) dataset used in habitat?
I couldn't find the `download_mp.py`, and has finished sending email to [matterport3d@googlegroups.com](mailto:matterport3d@googlegroups.com).
Now I am waiting email reply, but how can I recognize which dataset is used by habitat?

**Comment by aclegg3** [comment]
Hey @GuoPingPan,
There are many scene datasets available for use in Habitat.
The first place to start is [DATASETS.md](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md). All download instructions and processes are listed there, including [MP3D](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset) and the newer [HM3D](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d).
If you have specific questions about some step not working feel free to open a new issue.
