### ISSUE TITLE
ImportError: cannot import name 'text' from 'magnum'

### ISSUE THREAD

**Issue by YuquanDeng** [facebookresearch/habitat-sim#2049]
## Habitat-Sim version
vx.x.x

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
I setup the conda environment by running `conda create -n habitat python=3.8` and install habitat-sim from night build by running `conda install habitat-sim=0.2.2 withbullet -c conda-forge -c aihabitat-nightly`. As I followed the solution from #1909 , I also pull the stable tag. But when I run `python examples/viewer.py --scene ./data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`, I still met the error:
<pre><code>
Traceback (most recent call last):
  File "examples/viewer.py", line 19, in <module>
    from magnum import shaders, text
ImportError: cannot import name 'text' from 'magnum' 
</code></pre>

- habitat-sim version and current branch of the repo
![image](https://user-images.githubusercontent.com/88260334/228303892-877b16ba-04c1-48d5-873a-6c9c4294b7d5.png)
![image](https://user-images.githubusercontent.com/88260334/228304686-9f7df3f6-3550-491d-a62c-b95aef7c1200.png)

- If I run the viewer with habitat-sim in c++, it works fine.
![image](https://user-images.githubusercontent.com/88260334/228305539-e317142f-acde-4c67-9d57-22f23fda991d.png)

I don't know what exactly goes wrong. Thank you so much in advance!
___

Another thing is that the installation section suggests using python3.9 or higher but after I created a conda environment with python 3.9 and run `conda install habitat-sim withbullet -c conda-forge -c aihabitat`. I met unstatisfaction error:

<pre> <code>
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          
 
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
 
Specifications:
 
  - habitat-sim -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
 
Your python: python=3.9
 
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
 
The following specifications were found to be incompatible with each other:
 
Output in format: Requested package -> Available versions
 
Package habitat-sim-mutex conflicts for:
withbullet -> habitat-sim-mutex==1.0[build=*_bullet]
habitat-sim -> habitat-sim-mutex==1.0[build='display_bullet|headless_nobullet|display_nobullet|headless_bullet']The following specifications were found to be incompatible with your system:
 
  - feature:/linux-64::__glibc==2.31=0
  - python=3.9 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
 
Your installed version is: 2.31
</code> </pre>

If I understand correctly, the version of habitat-sim I am installing is incomptiable with python 3.9, so I use python 3.8 instead.

**Comment by KyleHuo** [comment]
I met the same problem with you. I also use python 3.8 instead. In addition, I cannot run with C++ either. Hope someone can help.

**Comment by jemo-mh** [comment]
Same issue, can't solve yet. 

Currently available  C++  test `habitat-viewer /path/to/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`

I tried 0.2.2 and 0.2.3 but both encountered same issue.
Env setting is UIbuntu 20.04, nvidia-470 graphic driver with RTX 2080Ti

**Comment by aclegg3** [comment]
Hey folks,

To run the viewer application, you'll need a matching and recent version of the conda packages and cloned local repo code.

I tested today on a fresh conda env following build instructions:
```
conda create -n habitat python=3.9 cmake=3.14.0
conda activate habitat
conda install habitat-sim withbullet -c conda-forge -c aihabitat-nightly
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
```
Note that I installed the nightly build.
Then (assuming you already have `data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`):
```
python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
habitat-viewer data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
```
Both of these work for me.

**Comment by jemo-mh** [comment]
> Hey folks,
> 
> To run the viewer application, you'll need a matching and recent version of the conda packages and cloned local repo code.
> 
> I tested today on a fresh conda env following build instructions:
> 
> ```
> conda create -n habitat python=3.9 cmake=3.14.0
> conda activate habitat
> conda install habitat-sim withbullet -c conda-forge -c aihabitat-nightly
> git clone https://github.com/facebookresearch/habitat-sim.git
> cd habitat-sim
> ```
> 
> Note that I installed the nightly build. Then (assuming you already have `data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`):
> 
> ```
> python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> habitat-viewer data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> ```
> 
> Both of these work for me.

HI there!
Thanks for your help.
As follow ur instructions (also same with documentation says)
c++ code for 
`habitat-viewer data/scene_datasets/habitat-test-scenes/skokloster-castle.glb` works well

but using python example, 
`python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb` print out RenderTarget Error which is 
`RenderTarget::Impl::blitRgbaTo(): target framebuffer has a size of Vector(1600, 1200) but expected Vector(800, 600)
Aborted (core dumped)`

I think a defined buffer size is different. Is there any solution to fix as setting configuration?
Thanks for your help in advance.

Have a nice day :)

**Comment by aclegg3** [comment]
Hey @jemo-mh, this sounds like a different issue.
It reminds me of system DPI scaling issues we've seen in the past.
@0mdc @mosra thoughts here?

**Comment by 0mdc** [comment]
I was able to reproduce locally. I issued a fix here: #2055

@jemo-mh Can you try out these changes?

**Comment by YuquanDeng** [comment]
> 

Sorry for the late reply! Thank you so much for your help!!! That worked!

**Comment by YuquanDeng** [comment]
> Hey folks,
> 
> To run the viewer application, you'll need a matching and recent version of the conda packages and cloned local repo code.
> 
> I tested today on a fresh conda env following build instructions:
> 
> ```
> conda create -n habitat python=3.9 cmake=3.14.0
> conda activate habitat
> conda install habitat-sim withbullet -c conda-forge -c aihabitat-nightly
> git clone https://github.com/facebookresearch/habitat-sim.git
> cd habitat-sim
> ```
> 
> Note that I installed the nightly build. Then (assuming you already have `data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`):
> 
> ```
> python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> habitat-viewer data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> ```
> 
> Both of these work for me.

Sorry for the late reply! Thank you so much for your help!!! That worked for me!

**Comment by jemo-mh** [comment]
> I was able to reproduce locally. I issued a fix here: #2055
> 
> @jemo-mh Can you try out these changes?

Hello there!
Cloning your recent commit, It works now.
Thanks for your help and have a nice day :)

**Comment by chenhaomingbob** [comment]
> > I was able to reproduce locally. I issued a fix here: #2055
> > @jemo-mh Can you try out these changes?
> 
> Hello there! Cloning your recent commit, It works now. Thanks for your help and have a nice day :) 

Hi. I encountered the ImportError in tag v0.3.1. 
Can you remember the version you used that is successfully running?

**Comment by 0mdc** [comment]
That version works for me. What's your environment?

You might want to try re-creating your conda environment before debugging this further.

**Comment by chenhaomingbob** [comment]
> That version works for me. What's your environment?
> 
> You might want to try re-creating your conda environment before debugging this further.

I find that this error is related to the `headless`.
If I use `conda install habitat-sim withbullet -c conda-forge -c aihabitat`  instead of `conda install habitat-sim withbullet headless -c conda-forge -c aihabitat`, the error does not exist.

**Comment by 0mdc** [comment]
I see. In the case of `viewer.py`, this makes sense as `headless` is meant to be used on systems without displays. Therefore, it excludes dependencies like GUI text.

Did you get this error by running something else?

**Comment by chenhaomingbob** [comment]
Thanks for your explanation. When I run `python examples/viewer.py --scene data`, I encounter this error.

**Comment by 2927803072** [comment]
> Hey folks,
> 
> To run the viewer application, you'll need a matching and recent version of the conda packages and cloned local repo code.
> 
> I tested today on a fresh conda env following build instructions:
> 
> ```
> conda create -n habitat python=3.9 cmake=3.14.0
> conda activate habitat
> conda install habitat-sim withbullet -c conda-forge -c aihabitat-nightly
> git clone https://github.com/facebookresearch/habitat-sim.git
> cd habitat-sim
> ```
> 
> Note that I installed the nightly build. Then (assuming you already have `data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`):
> 
> ```
> python examples/viewer.py --scene data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> habitat-viewer data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> ```
> 
> Both of these work for me.
Hello，I followed your procedure and this error occurred

Platform: can't get Xft.dpi property for virtual DPI scaling, falling back to physical DPI
EGL: Failed to get EGL display: Success
Platform::GlfwApplication::tryCreate():  cannot create a window with core OpenGL context, falling back to compatibility context
EGL: Failed to get EGL display: Success
Platform::GlfwApplication::tryCreate(): cannot create a window with OpenGL context

I did this on a remote server, and then I tried to add headless when installing habitat, but there was this problem

from magnum import shaders, text
ImportError: cannot import name 'text' from 'magnum'

Do you know the reason for this? Hope to get your reply, thank you

**Comment by 2927803072** [comment]
> Thanks for your explanation. When I run , I encounter this error.`python examples/viewer.py --scene data`

@chenhaomingbob  Hello, I met the same problem, do you solve it?
