### ISSUE TITLE
Scene's ground's Y coordinate

### ISSUE THREAD

**Issue by XiaohanLei** [facebookresearch/habitat-sim#2050]
Hi!

Thanks for your awesome work!

I got a question that needs to sample navigable points around the scene ground, so I need to know each scene's ground's Y coordinate.
Are there some suggestions?

Thanks in advance!

**Comment by dhruvbatra** [comment]
https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/main/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
