### ISSUE TITLE
Object's Location Problem

### ISSUE THREAD

**Issue by XiaohanLei** [facebookresearch/habitat-sim#2052]
Hi!

Thanks for your contribution to indoor navigation!

Here is the question: I got a homan model and imported it into habitat simulator, but when I tried to read its position in the simulator from the object's property called translation, I found that it was not right. In other words, when the agent could see the object, the object's position from the agent was far from the range that the agent could see. So, is there something wrong with the coordinate?

Thanks in advance!

**Comment by aclegg3** [comment]
Hey @XiaohanLei,
Sounds like I'll need some more details to really be useful here.

Some thoughts:
1. Rigid objects are adjusted upon initialization such that the center of their bounding box (heuristic for center of mass) and local origin (0,0,0) are coincident. Depending on your model's local transformations this could be throwing you off.
2. The agent may be initialized at a random location on the NavMesh, so check that the agent's position is where you expect. It may not be the scene origin.

If you would like more assistance, I'll need some logs, reproducible code (a branch or snippet) and the model to check further.

**Comment by XiaohanLei** [comment]
I think I found the problem.
The reason why I could see the object that should be out of vision range is that the translation property should not be set immediately twice, or it will appear twice at two different places.
Thanks for your help!
