### ISSUE TITLE
Platform::WindowlessEglApplication::tryCreateContext(): unable to find CUDA device 0 among 1 EGL devices in total WindowlessContext: Unable to create windowless context

### ISSUE THREAD

**Issue by Buddies-as-you-know** [facebookresearch/habitat-sim#2099]
## ❓ Questions and Help
Hello,

I am trying to set up habitat-sim on a wsl remote Ubuntu-22.04 machine, but when I try to run the simulation I encounter the following error Any help on installation please:

````
eglQueryDevicesEXT(): EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
eglQueryDevicesEXT(): EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
Platform::WindowlessEglApplication: eglQueryDeviceStringEXT(EGLDevice=0): EGL_MESA_device_software EGL_EXT_device_drm_render_node
eglQueryDeviceAttribEXT(): eglQueryDeviceAttribEXT
Platform::WindowlessEglApplication::tryCreateContext(): unable to find CUDA device 0 among 1 EGL devices in total
WindowlessContext: Unable to create windowless context
````
Ubuntu-22.04 with NVIDIA GPU3090. about via wsl in Windows 10

Steps to reproduce
Install habitat-sim:
conda env create -n habitat python=3.8 cmake=3.14.0
conda start habitat
conda install -n habitat habitat-sim -c conda-forge -c aihabitat
Download and run example: cloned the examples/example.py repo and downloaded the test data. Execute
python examples/example.py --scene . /test_data/scene_datasets/habitat-test-scenes/skokloster-castle.glb

After running nvidia-smi.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03 Driver Version: 531.41 CUDA Version: 12.1 |
|-----------------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr.
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. | | | MIG M. | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr.
| MIG M.
| =========================================+======================+======================|
| 0 NVIDIA GeForce RTX 3090 On | 00000000:02:00.0 On | N/A |
| 0% 47C P8 26W / 370W| 774MiB / 24576MiB | 1% Default |
| | N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=======================================================================================|
| No running processes found |
+---------------------------------------------------------------------------------------+
```

**Comment by 0mdc** [comment]
@YuminosukeSato 

Have you managed to work around this issue?

`eglQueryDeviceStringEXT(EGLDevice=0): EGL_MESA_device_software EGL_EXT_device_drm_render_node` hints that EGL is not finding your NVIDIA driver. This may be a problem with your `glvnd` installation.

**Comment by friolero** [comment]
Not sure if it is the same case with yours. Mine turns out to miss nvidia gl packages from the nvidia cuda docker environment and installing it resolves my issue:

```
sudo apt-get install libnvidia-gl-535 (replace with your nvidia driver version)
sudo apt-get install --reinstall libglvnd-dev
```

**Comment by 0mdc** [comment]
I'll close this as stale. Feel free to file another issue.

**Comment by programingisgoddamndifficult** [comment]
> I'll close this as inactive. Feel free to file another issue.



> Not sure if it is the same case with yours. Mine turns out to miss nvidia gl packages from the nvidia cuda docker environment and installing it resolves my issue:
> 
> ```
> sudo apt-get install libnvidia-gl-535 (replace with your nvidia driver version)
> sudo apt-get install --reinstall libglvnd-dev
> ```

thanks a lot! it works

**Comment by goodstudent9** [comment]
> > I'll close this as inactive. Feel free to file another issue.
> 
> > Not sure if it is the same case with yours. Mine turns out to miss nvidia gl packages from the nvidia cuda docker environment and installing it resolves my issue:
> > ```
> > sudo apt-get install libnvidia-gl-535 (replace with your nvidia driver version)
> > sudo apt-get install --reinstall libglvnd-dev
> > ```
> 
> thanks a lot! it works

E: Unable to locate package libnvidia-gl-535
That seems like I cannot install this package

**Comment by EftePA** [comment]
I have the same problem, and used `nvidia-smi` to check my nvidia driver version, it is 535. But installing `libnvidia-gl-535` and `libglvnd-dev` didn't solve it.

**Comment by goodstudent9** [comment]
> I have the same problem, and used `nvidia-smi` to check my nvidia driver version, it is 535. But installing `libnvidia-gl-535` and `libglvnd-dev` didn't solve it.
 DO NOT TRY to install habitat if you can not do that!
Using docker image provided. I use it smoothly!
![image](https://github.com/facebookresearch/habitat-sim/assets/103085487/b96c7e12-491b-430b-a2c8-8b6a04f2a5b7)

Good luck!

**Comment by betray12138** [comment]
Hi,  I meet the same problem here. My nvidia-smi information is:

Thu Aug 21 16:49:43 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01 Driver Version: 550.163.01 CUDA Version: 12.4 |
|-----------------------------------------+------------------------+----------------------+
| GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|=========================================+========================+======================|
| 0 NVIDIA GeForce RTX 4090 On | 00000000:B8:00.0 Off | Off |
| 59% 27C P8 30W / 450W | 12MiB / 49140MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

<img width="975" height="529" alt="Image" src="https://github.com/user-attachments/assets/272245ae-cdd7-4809-b81c-1ef6240dc973" />

I tried to install libnvidia-gl-550, reinstall libglvnd-dev and install libglib2.0-0 on top of the CUDA base image, but it didn't work. Any help would be greatly appreciated!!!

Hi @goodstudent9 , could you please tell me how to use the Docker image to run the habitat? Many thanks in advance!
