### ISSUE TITLE
Culling based rendering acceleration

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-sim#210]
Culling based rendering acceleration:
- Frustum culling
- Visibility culling based on spatial data structures (BVH, kd-tree etc.);

**Comment by mathfac** [comment]
@bigbike, please assign who is appropriate responsible person. Thank you!

**Comment by Skylion007** [comment]
@bigbike Can this issue be closed?

**Comment by bigbike** [comment]
Only partially resolved.
I only implemented linear FC. Will try the tree structure in the near future.

**Comment by aclegg3** [comment]
No concrete plans to implement more culling tech at this time.
