### ISSUE TITLE
error when setup with Bullet

### ISSUE THREAD

**Issue by Kyridiculous2** [facebookresearch/habitat-sim#212]
when I run 

**python setup.py install --bullet**

I notice this in the log:
Could NOT find Bullet (missing: BULLET_DYNAMICS_LIBRARY
  BULLET_COLLISION_LIBRARY BULLET_MATH_LIBRARY BULLET_SOFTBODY_LIBRARY
  BULLET_INCLUDE_DIR)

but I've successfully installed bullet and can use it through python.

**Comment by aclegg3** [comment]
How did you install it? Looks like the compiler isn't picking it up.

**Comment by Kyridiculous2** [comment]
Thank you very much!
Solved after conda install bullet
