### ISSUE TITLE
Can I make a semantic annotation myself?

### ISSUE THREAD

**Issue by chris-naknak** [facebookresearch/habitat-sim#2165]
## Habitat-Sim version
v0.2.4

## Docs and Tutorials
Did you read the docs? Yes.

Did you check out the tutorials? Yes.

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
Hello, I'm interested in the Habitat platform.
Thank you for your great work.

I am not familiar with the 3D datasets. 
Through the tutorials, I cheked four files: ".glb", ".ply (or _semantic.ply)", ".house", and ".navmesh".
Which of the four files contains the semantic segmentation information?(the semantic annotation?)

And I was wondering if I could render semantic scenes for arbitrary 3D files (e.g., Mydata.glb). 
Is there any way to get semantic annotation using 3D files directly?

Thank you for your attention!
Have a good day :)

**Comment by aclegg3** [comment]
Hey @chris-naknak 
You absolutely can create semantic annotations yourself.
You can "paint" them onto textures (see [this issue](https://github.com/facebookresearch/habitat-lab/issues/1457)) or [set semantic ids for individual imported objects](https://aihabitat.org/docs/habitat-sim/habitat_sim.physics.ManagedRigidObject.html#semantic_id).
