### ISSUE TITLE
the demo code cannot get semantic image

### ISSUE THREAD

**Issue by zuixiaosanlang** [facebookresearch/habitat-sim#2194]
https://aihabitat.org/docs/habitat-sim/image-extractor.html

the demo code cannot get semantic image.

![image](https://github.com/facebookresearch/habitat-sim/assets/20105627/55d0c8e7-3a77-4b28-bd11-c33e07312f50)

**Comment by aclegg3** [comment]
@zuixiaosanlang This scene has no semantics defined.
Try HM3D example scene instead. :)
