### ISSUE TITLE
The dataset in hugging face seems to be not available? 

### ISSUE THREAD

**Issue by Ethan2415** [facebookresearch/habitat-sim#2271]
## Habitat-Sim 0.3.0(latest)

python -m habitat_sim.utils.datasets_download --uids habitat_test_pointnav_dataset --data-path data/
seems to not be working, and so does other datasets? When i enter the address attached in the datasets_download.py file, it show 404. 
Where else can I download those dataset?

**Comment by aclegg3** [comment]
Hey @Ethan2415,

Sometimes network issues prevent access to AWS S3 (in this case) or HuggingFace servers temporarily. This and other data sources are working for me presently. Please try again and update this issue.

**Comment by Lr-2002** [comment]
@Ethan2415  hello,
Were you using your web-browser to view the website(something.git) ? The view with ".git" is not accessable for me both WHILE you can use git to clone it. This might because of the huggingface web.

**Comment by aclegg3** [comment]
Outages happen. Closing this task as stale and likely not a bug.
