### ISSUE TITLE
Habitat installation 

### ISSUE THREAD

**Issue by HalahMohammed** [facebookresearch/habitat-sim#2280]
## Habitat-lab version
 

Hello 

I followed all instructions to install habitat, I did not face any problem in installation.

I tried to run the following task 

 https://github.com/facebookresearch/habitat-lab/blob/main/examples/interactive_play.py 

but I found this problem related to the kernel "The kernel 'habitat (Python 3.9.18)' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details"

Please tell me how I can solve this problem ?

Thanks in advance

**Comment by aclegg3** [comment]
This looks like a habitat-lab issue. Please re-open there if you are still having issues. We'll also need more information (e.g. log output and system info) to start helping.
