### ISSUE TITLE
ECCV 2020 colab notebook failed in 1st cell .

### ISSUE THREAD

**Issue by rebecajohn** [facebookresearch/habitat-sim#2293]
!curl -L https://raw/.githubusercontent.com/facebookresearch/habitat-sim/main/examples/colab_utils/colab_install.sh | NIGHTLY=true bash -s
!wget -c http://dl/.fbaipublicfiles.com/habitat/mp3d_example.zip && unzip -o mp3d_example.zip -d /content/habitat-sim/data
/scene_datasets/mp3d/

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2733  100  2733    0     0   8839      0 --:--:-- --:--:-- --:--:--  8844
--2024-01-05 13:34:23--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving [repo.continuum.io](http://repo.continuum.io/) ([repo.continuum.io](http://repo.continuum.io/))... 104.16.246.55, 104.16.245.55, 2606:4700::6810:f537, ...
Connecting to [repo.continuum.io](http://repo.continuum.io/) ([repo.continuum.io](http://repo.continuum.io/))|104.16.246.55|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [following]
--2024-01-05 13:34:23--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving [repo.anaconda.com](http://repo.anaconda.com/) ([repo.anaconda.com](http://repo.anaconda.com/))... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to [repo.anaconda.com](http://repo.anaconda.com/) ([repo.anaconda.com](http://repo.anaconda.com/))|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 141613749 (135M) [text/x-sh]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-L 100%[===================>] 135.05M   162MB/s    in 0.8s    

2024-01-05 13:34:24 (162 MB/s) - ‘Miniconda3-latest-Linux-x86_64.sh’ saved [141613749/141613749]

PREFIX=/usr/local
Unpacking payload ...
                                                                                
Installing base environment...

Downloading and Extracting Packages:

Downloading and Extracting Packages:

Preparing transaction: done
Executing transaction: done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /usr/local
Channels:
 - aihabitat-nightly
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package habitat-sim-0.3.0.2024.01.04-py3.9_headless_linux_0ca1511424326a8189615b0447c95b8253d9dfb8 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ habitat-sim is installable and it requires
│  ├─ python >=3.9,<3.10.0a0 , which can be installed;
│  └─ python_abi 3.9.* *_cp39, which can be installed;
└─ python 3.10**  is not installable because there are no viable options
   ├─ python [3.10.0|3.10.10|...|3.10.9] conflicts with any installable versions previously reported;
   └─ python [3.10.0|3.10.1|...|3.10.9] would require
      └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported.

An error occurred during the installation of Habitat-sim or Habitat-Lab.
--2024-01-05 13:35:46--  http://dl.fbaipublicfiles.com/habitat/mp3d_example.zip
Resolving [dl.fbaipublicfiles.com](http://dl.fbaipublicfiles.com/) ([dl.fbaipublicfiles.com](http://dl.fbaipublicfiles.com/))... 13.227.219.33, 13.227.219.10, 13.227.219.59, ...
Connecting to [dl.fbaipublicfiles.com](http://dl.fbaipublicfiles.com/) ([dl.fbaipublicfiles.com](http://dl.fbaipublicfiles.com/))|13.227.219.33|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67764531 (65M) [application/zip]
Saving to: ‘mp3d_example.zip’

mp3d_example.zip    100%[===================>]  64.62M  19.8MB/s    in 3.3s    

2024-01-05 13:35:50 (19.8 MB/s) - ‘mp3d_example.zip’ saved [67764531/67764531]

Archive:  mp3d_example.zip
checkdir:  cannot create extraction directory: /content/habitat-sim/data/scene_datasets/mp3d
           No such file or directory

**Comment by aclegg3** [comment]
Note we have stopped supporting colab and converted tutorials to local Jupyter notebooks instead.
