### ISSUE TITLE
Observation Clipping and Perspective

### ISSUE THREAD

**Issue by johncruyff14** [facebookresearch/habitat-sim#2306]
Hi there! Just a trivial bug or issue. I notice that there are lots of "clipping" or "perspective" observations like below if my agent gets too close to the boundary of the rooms. Is this related to my environment setting(Habitat Challenge 2022 Setting)? Or is this a normal issue to add some noise ? Or maybe this is related to the scene? 
 
The scene mentioned in Habitat Matterport 3D V0.1 Semantic which are used in the Habitat Challenge 2022.  
![image](https://github.com/facebookresearch/habitat-sim/assets/40756477/4c5b6273-862b-4cf0-8c24-ab9bda0f9d4b)

![image](https://github.com/facebookresearch/habitat-sim/assets/40756477/703a189e-9423-4271-a642-9e4ca0061010)

![image](https://github.com/facebookresearch/habitat-sim/assets/40756477/c299ea8b-1d3f-41fe-a5d2-d050c307033d)

![image](https://github.com/facebookresearch/habitat-sim/assets/40756477/31ac0d58-fc83-4c88-96c5-dc5279f0873a)

@aclegg3  @erikwijmans

**Comment by aclegg3** [comment]
Hey @johncruyff14 this looks like a standard artifact of 3D scanning processes. Since HM3D scene assets are the result of a scanning pipeline, there can be issues like this. Likely the camera was occluded or there was a reflective surface. In any case, it doesn't look like a simulator bug to me.
