### ISSUE TITLE
colab_install.sh support

### ISSUE THREAD

**Issue by rayxsong** [facebookresearch/habitat-sim#2313]
I am setting up Habitat Sim navigation demo in Colab, it seems that colab_install.sh has been removed in the main branch. Is there another way to set up in Colab? Thank you!

**Comment by aclegg3** [comment]
Hey @rayxsong 
We've deprecated Colab support and converted notebooks to be locally run-able with Jupyter notebook instead.
You're welcome to attempt fixing that install script from the version cached before the deprecation. #2298 
We found that correctly setting up the Colab system backend to be compatible could be trouble, so it is likely non-trivial.
