### ISSUE TITLE
Habitat-sim installation with conda and from source

### ISSUE THREAD

**Issue by realjoshqsun** [facebookresearch/habitat-sim#2329]
Hello, I'm using the code from https://github.com/GT-RIPL/robo-vln, where a modified version of habitat-sim was used [habitat-sim @ d8f5e9b](https://github.com/zubair-irshad/habitat-sim/tree/d8f5e9b664ea28a1db88dbcb89dc9ae3e76d1410).

I was trying the following code to install habitat-sim, but errors occurred.
cd environments/habitat-sim
python setup.py install --headless --with-cuda

(habitat) [q84sun@gra-login1 habitat-sim]$ python setup.py install --headless --with-cuda
running install
running bdist_egg
running egg_info
creating habitat_sim.egg-info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/sensor.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/geo.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/simulator.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/physics.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/gfx.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/attributes.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/registry.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/logging.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/errors.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/scene.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/attributes_managers.py -> build/lib.linux-x86_64-3.6/habitat_sim
copying habitat_sim/sim.py -> build/lib.linux-x86_64-3.6/habitat_sim
creating build/lib.linux-x86_64-3.6/habitat_sim/bindings
copying habitat_sim/bindings/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/bindings
creating build/lib.linux-x86_64-3.6/habitat_sim/agent
copying habitat_sim/agent/agent.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent
copying habitat_sim/agent/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent
creating build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/profiling_utils.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/viz_utils.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/collect_env.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/common.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/compare_profiles.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
copying habitat_sim/utils/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils
creating build/lib.linux-x86_64-3.6/habitat_sim/nav
copying habitat_sim/nav/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/nav
copying habitat_sim/nav/greedy_geodesic_follower.py -> build/lib.linux-x86_64-3.6/habitat_sim/nav
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors
copying habitat_sim/sensors/sensor_suite.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors
copying habitat_sim/sensors/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors
creating build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/pyrobot_noisy_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/default_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/object_controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/controls.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
copying habitat_sim/agent/controls/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/agent/controls
creating build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/data_extractor.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/data_structures.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/pose_extractor.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
copying habitat_sim/utils/data/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/utils/data
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/no_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/redwood_depth_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/gaussian_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/speckle_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/poisson_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/__init__.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
copying habitat_sim/sensors/noise_models/sensor_noise_model.py -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models
creating build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models/data
copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-3.6/habitat_sim/sensors/noise_models/data
running build_ext
Submodule 'docs/m.css' (https://github.com/mosra/m.css) registered for path 'docs/m.css'
Submodule 'src/deps/Sophus' (https://github.com/strasdat/Sophus) registered for path 'src/deps/Sophus'
Submodule 'src/deps/assimp' (https://github.com/assimp/assimp) registered for path 'src/deps/assimp'
Submodule 'src/deps/corrade' (https://github.com/mosra/corrade.git) registered for path 'src/deps/corrade'
Submodule 'src/deps/eigen-git-mirror' (https://github.com/eigenteam/eigen-git-mirror) registered for path 'src/deps/eigen-git-mirror'
Submodule 'src/deps/glfw' (https://github.com/glfw/glfw) registered for path 'src/deps/glfw'
Submodule 'src/deps/glog' (https://github.com/google/glog.git) registered for path 'src/deps/glog'
Submodule 'src/deps/googletest' (https://github.com/google/googletest) registered for path 'src/deps/googletest'
Submodule 'src/deps/imgui' (https://github.com/ocornut/imgui.git) registered for path 'src/deps/imgui'
Submodule 'src/deps/magnum' (https://github.com/mosra/magnum.git) registered for path 'src/deps/magnum'
Submodule 'src/deps/magnum-bindings' (https://github.com/mosra/magnum-bindings.git) registered for path 'src/deps/magnum-bindings'
Submodule 'src/deps/magnum-integration' (https://github.com/mosra/magnum-integration.git) registered for path 'src/deps/magnum-integration'
Submodule 'src/deps/magnum-plugins' (https://github.com/mosra/magnum-plugins.git) registered for path 'src/deps/magnum-plugins'
Submodule 'src/deps/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'src/deps/pybind11'
Submodule 'src/deps/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'src/deps/rapidjson'
Submodule 'src/deps/recastnavigation' (https://github.com/erikwijmans/recastnavigation.git) registered for path 'src/deps/recastnavigation'
Submodule 'src/deps/tinyobjloader' (https://github.com/syoyo/tinyobjloader.git) registered for path 'src/deps/tinyobjloader'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/docs/m.css'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/Sophus'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/assimp'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/corrade'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/eigen-git-mirror'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/glfw'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/glog'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/googletest'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/imgui'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum-bindings'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum-integration'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum-plugins'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/pybind11'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/rapidjson'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/recastnavigation'...
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/tinyobjloader'...
Submodule path 'docs/m.css': checked out '01ea5ad52eb8e85b018027a5d540f5822ebfebba'
Submodule path 'src/deps/Sophus': checked out 'b475c0a81a197ff8ea6bdcf8df8a2f5a7b1da879'
Submodule path 'src/deps/assimp': checked out '8f0c6b04b2257a520aaab38421b2e090204b69df'
Submodule path 'src/deps/corrade': checked out '71624bcdf10a23b60eb9dceda9434d9d7593799e'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/corrade/toolchains'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/corrade/toolchains'...
Submodule path 'src/deps/corrade/toolchains': checked out '03a6b4c2648e9b367b2e8eef4b869a3d7c47c16f'
Submodule path 'src/deps/eigen-git-mirror': checked out 'd10e1f03d4ef456f78ff6b91d9078b1f13a5975c'
Submodule path 'src/deps/glfw': checked out '0a49ef0a00baa3ab520ddc452f0e3b1e099c5589'
Submodule path 'src/deps/glog': checked out '8d7a107d68c127f3f494bb7807b796c8c5a97a82'
Submodule path 'src/deps/googletest': checked out '00938b2b228f3b70d3d9e51f29a1505bdad43f1e'
Submodule path 'src/deps/imgui': checked out 'ca30ef4269150e71a950106c6cfa8f94898581da'
Submodule path 'src/deps/magnum': checked out '8c5a2d6a88392e6bf6b280d8bc04ee6ed695bdcc'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum/toolchains'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum/toolchains'...
Submodule path 'src/deps/magnum/toolchains': checked out '03a6b4c2648e9b367b2e8eef4b869a3d7c47c16f'
Submodule path 'src/deps/magnum-bindings': checked out '66681d4dee950fe48fcbdd2a7e45a76e4480a4ec'
Submodule path 'src/deps/magnum-integration': checked out 'f148cd9cdbe3f1b6b17ca2f7dc5a1531a651533c'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-integration/toolchains'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum-integration/toolchains'...
Submodule path 'src/deps/magnum-integration/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/magnum-plugins': checked out 'c669efd2d67db50f1a8ac5c0776de3b8ae7bea93'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-plugins/toolchains'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/magnum-plugins/toolchains'...
Submodule path 'src/deps/magnum-plugins/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/pybind11': checked out 'e43e1cc01ae6d4e4e5ba10557a057d7f3d5ece0d'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'src/deps/pybind11/tools/clang'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/pybind11/tools/clang'...
Submodule path 'src/deps/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'src/deps/rapidjson': checked out '73063f5002612c6bf64fe24f851cd5cc0d83eef9'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'src/deps/rapidjson/thirdparty/gtest'
Cloning into '/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src/deps/rapidjson/thirdparty/gtest'...
Submodule path 'src/deps/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
Submodule path 'src/deps/recastnavigation': checked out '354591e10a772b8057e42a4f9de701155b9aaa02'
Submodule path 'src/deps/tinyobjloader': checked out 'e52dfdbecdf8893b161a65e508bc009746fa6042'
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- The CUDA compiler identification is unknown
-- Check for working C compiler: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/cc
-- Check for working C compiler: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/c++
-- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/q84sun/q84sun/navigation/robo-vln/environments/habitat-sim/build/CMakeFiles/CMakeOutput.log".
See also "/home/q84sun/q84sun/navigation/robo-vln/environments/habitat-sim/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    include_package_data=True,
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.build_extension(ext)
  File "setup.py", line 273, in build_extension
    env=env,
  File "/home/q84sun/miniconda3/envs/habitat/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-H/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/src', '-Bbuild', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/project/6001557/q84sun/navigation/robo-vln/environments/habitat-sim/build/lib.linux-x86_64-3.6/habitat_sim/_ext', '-DPYTHON_EXECUTABLE=/home/q84sun/miniconda3/envs/habitat/bin/python', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=OFF', '-DTARGET_HEADLESS=ON', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=ON']' returned non-zero exit status 1.

Could you please help me figure it out?

**Comment by QixuanSun** [comment]
I've also tried to install with conda directly. 
E.g., conda install habitat-sim -c conda-forge -c aihabitat
or with a specific version, conda install habitat-sim=0.1.7 -c conda-forge -c aihabitat.
But both failed.
And here's the error message

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - habitat-sim

Current channels:

  - https://conda.anaconda.org/robostack/osx-64
  - https://conda.anaconda.org/robostack/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by shengyin1224** [comment]
If you use Macbook and have arm64 not X86-64, you can conda create -n env and then first input `conda config --env --set subdir osx-64 ` in the terminal.

**Comment by vidyav2** [comment]
@realjoshqsun have you been able to resolve this issue? 
I'm stuck w/ the same issue, any help to resolve this is appreciated.

**Comment by hjy0712** [comment]
i am stuck with the same issue

**Comment by realjoshqsun** [comment]
@vidyav2 @hjy0712 
I'm using ubuntu22.04. And it seems like there's a discrepancy for the installed package.
You have to download the packages on Anaconda and install it manually.
