### ISSUE TITLE
Agent CI test failing at random

### ISSUE THREAD

**Issue by aclegg3** [facebookresearch/habitat-sim#233]
## Steps to reproduce

  1. Run pytest tests/test_agent.py

## Observed Results

  Sometimes the test will fail on np.allclose() with small error.

![image](https://user-images.githubusercontent.com/1445143/65342739-3273dd00-db88-11e9-9c3d-a4f5a5fe5ede.png)

## Expected Results

The test should pass. It will pass most of the time. Re-running the same failed CI test will often succeed.

## Relevant Code
test_agent.py:76
Maybe the `atol=1e-5` is too tight a bound here?

```
assert np.allclose(s1.postion, s2.position, atol=1e-5)
```

**Comment by msbaines** [comment]
I'm starting to hit this pretty regularly also but I don't think I hit this at all until maybe 1 week ago.
