### ISSUE TITLE
Request for Access to Gibson Real and MP3D Real Datasets

### ISSUE THREAD

**Issue by kszpxxzmc** [facebookresearch/habitat-sim#2330]
I am currently working on a project related to your paper "Habitat-Matterport 3D Dataset (HM3D):
1000 Large-scale 3D Environments for Embodied AI" and I find your research highly valuable. However, the datasets mentioned in the paper, specifically the Gibson Real and MP3D Real datasets, require an application process for access. Given the urgency of my work, I was wondering if you could kindly assist in providing their image sets.

**Comment by aclegg3** [comment]
Hey @kszpxxzmc, glad to hear you're interested in this work. 

I can't speak to the Gibson approval process, as that project is managed by another group. 

If you have submitted your access request for MP3D (or HM3D), you should be approved within 24 hours. If you are seeing any delay in that approval I can poke the approving organization to unblock you.

**Comment by kszpxxzmc** [comment]
Thank you very much!
________________________________
发件人: Alexander Clegg ***@***.***>
发送时间: 2024年3月2日 2:21
收件人: facebookresearch/habitat-sim ***@***.***>
抄送: 章梦晨 ***@***.***>; Mention ***@***.***>
主题: Re: [facebookresearch/habitat-sim] Request for Access to Gibson Real and MP3D Real Datasets (Issue #2330)


Hey @kszpxxzmc<https://github.com/kszpxxzmc>, glad to hear you're interested in this work.

I can't speak to the Gibson approval process, as that project is managed by another group.

If you have submitted your access request for MP3D (or HM3D), you should be approved within 24 hours. If you are seeing any delay in that approval I can poke the approving organization to unblock you.

―
