### ISSUE TITLE
Wrong dataset link to AI2-THOR in Datasets README 

### ISSUE THREAD

**Issue by prathishpratt** [facebookresearch/habitat-sim#2352]
## Habitat-Sim version main

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? The bug you are about to report may already be fixed in the latest version.

Main branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

The dataset link for AI2-THOR is wrong here (https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#ai2-thor-habitat) as it guides to the HSSD page, please correct it for clarification.

**Comment by aclegg3** [comment]
This should be resolved now. Thanks for the report!
