### ISSUE TITLE
how to obtain the stage object in a scene?

### ISSUE THREAD

**Issue by YueFan1014** [facebookresearch/habitat-sim#2373]
Hello, i am wondering how to get the stage object after loading a scene into habitat-sim? I want to get the bounding box of the stage in order to achieve the center point of the scene. I notice that there is ```rigid_object_manager``` and ```articulated_object_manager```, but they cannot get the stage object. Is there any way to get the stage object? Thanks!

**Comment by aclegg3** [comment]
Hey @YueFan1014, because the stage is a singleton STATIC backdrop, we don't have a ManagedObject wrapper for that. However, you can get the bounding box of the scene via `Simulator.get_active_scene_graph().get_root_node().cumulative_bb`.

**Comment by YueFan1014** [comment]
Thanks!
