### ISSUE TITLE
add moving objects

### ISSUE THREAD

**Issue by zhouak47** [facebookresearch/habitat-sim#2392]
## Habitat-Sim version
v0.3.1

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
Hello, I'm trying to add some moving obstacles like human or robots in Habitat Sim. But I'm not sure how to do this. Do I need to treat moving obstacles as agents? I'm looking forward to your help. 
Thanks a lot!

**Comment by aclegg3** [comment]
Hey @zhouak47 

Please take a look at the tutorials here: https://aihabitat.org/docs/habitat-sim/

Particularly the "Interactive Rigid Objects 2.0" example.
Also the physics unit tests can be a good source of information, particularly on the ArticulatedObject API which does not have a full tutorial yet.

For more agent/robot focused concepts you can look at the articualted_agents or humanoids tutorials here: https://github.com/facebookresearch/habitat-lab/tree/main/examples/tutorials

I'll close this issue, but please feel free to open another with specific issues or challenges you may encounter.
