### ISSUE TITLE
Slow setup.py install

### ISSUE THREAD

**Issue by danielgordon10** [facebookresearch/habitat-sim#24]
Can we switch https://github.com/facebookresearch/habitat-sim/blob/master/setup.py#L86 to `-j ` instead of `-j 4` This will use all available cpus regardless of the system. While it might be "a burden" while setting up, do we expect people to be multitasking while installing habitat-sim or do we want it to install as fast as possible? I would argue the former.

**Comment by erikwijmans** [comment]
Yeah, that makes sense to do.  Want to make a PR?

**Comment by danielgordon10** [comment]
https://github.com/facebookresearch/habitat-sim/pull/27
