### ISSUE TITLE
How to prevent the robot from falling into floor holes in MP3D and HM3D?

### ISSUE THREAD

**Issue by CrystalSixone** [facebookresearch/habitat-sim#2436]
Hi, I'm new to this platform and trying to load the mesh sources provided in MP3D and HM3D. I noticed that there are some holes in the floor. When I drive the robot with its physical characteristics on another platform, it tends to fall or get stuck in those holes. However, it seems that the robot doesn't fall or get stuck in these holes when using Habitat-sim. I'm curious how Habitat achieves this. Did you make additional fixes to the MP3D mesh data? Or is there an algorithm that prevents the robot from falling into holes in the floor?

I would greatly appreciate any insights or solutions you could provide. Thank you!

**Comment by jturner65** [comment]
Hi
In habitat-sim we generate a navmesh to provide appropriate regions for the robotic agent to navigate upon. This construct avoids any missing gaps in the floor.
