### ISSUE TITLE
How to set a directional sound source?

### ISSUE THREAD

**Issue by szhangjc** [facebookresearch/habitat-sim#2441]
## ❓ Questions and Help
Thanks for your excellent work! I set my sound source as shown below,
`source=np.array([0.0,4.0,1.7]) 
audio_sensor = sim.get_agent(0)._sensors["audio_sensor"]
audio_sensor.setAudioSourceTransform(source) 
audio_sensor.setAudioMaterialsJSON("data/mp3d_material_config.json") 
`
I wonder whether the sound source is omnidirectional or directional? If it is directional, how to change the direction of the sound source?Thanks for your answer!

**Comment by aclegg3** [comment]
Hey @szhangjc,

I believe all sources are current omni-directional.
Please check out the docs here: https://github.com/facebookresearch/habitat-sim/blob/main/docs/AUDIO.md

**Comment by szhangjc** [comment]
I got it, thanks for your answer.
