### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by MorenMoren** [facebookresearch/habitat-sim#2449]
i' haved got the access of the Habitat-Matterport 3D Research Dataset (HM3D).

however,when i'm running `python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_minival_v0.2`,i got error as depicted in the title.

this errors happens after downloading the hm3d-minival-habitat.tar(408.9MB)

**Comment by itak04** [comment]
how to solve it
