### ISSUE TITLE
How can i make this 2.5D map?

### ISSUE THREAD

**Issue by bareblackfoot** [facebookresearch/habitat-sim#2467]
## Habitat-Sim version
v0.3.1

## ❓ Questions and Help

Thank you for your great work!

On the [Habitat homepage](https://aihabitat.org/), there is a navigation example in the video at 1:40. How can I create a similar 2.5D top down map with navigation trajectory?

Please help me.
Thanks!

**Comment by aclegg3** [comment]
Hey @bareblackfoot,

That part of the video was created by an artist using the original scene geometry and ai-generated trajectory. Unfortunately, we don't provide any tools to automatically generate trajectory visualizations like this in Habitat.
