### ISSUE TITLE
download hm3d_basis.scene_dataset_config.json

### ISSUE THREAD

**Issue by kunhumllop** [facebookresearch/habitat-sim#2480]
Hello, I cannot download the file (hm3d_basis.scene_dataset_config.json). Can you provide a download link? Thank you very much!

**Comment by Eku127** [comment]
Hi, do you have the link for downloading this file? I could not find this file in https://github.com/matterport/habitat-matterport-3dresearch?tab=readme-ov-file

**Comment by kunhumllop** [comment]
Yeah, I can't download the file either.

**Comment by aclegg3** [comment]
Hey folks, that file is found in `hm3d-minival-semantic-configs-v0.2.tar` (Format == semantic-configs).

**Comment by Lazy-boy193** [comment]
> 嘿伙计们，该文件位于`hm3d-minival-semantic-configs-v0.2.tar`（格式 == semantic-configs）。

`> ls <PATH TO HM3D>
hm3d_annotated_basis.scene_dataset_config.json    train/
hm3d_basis.scene_dataset_config.json              val/
minival/
`

What's the meaning of this?
Does it mean that the `hm3d_annotated-basis.scene_dataset_comfig.rson` file is actually the `hm3d_masis.scene_dataset_comfig.rson` file? So does the above structure only need to satisfy the following structure:

`> ls <PATH TO HM3D>
hm3d_annotated_basis.scene_dataset_config.json   
train/
val/
minival/
`

Excuse me, is that what the above answer means?
