### ISSUE TITLE
Bundling default physics config and test object meshes with scene meshes

### ISSUE THREAD

**Issue by dhruvbatra** [facebookresearch/habitat-sim#275]
## 🚀 Feature
Right now, we ask users to down this file for the test scenes:
http://dl.fbaipublicfiles.com/habitat/habitat-test-scenes.zip

And then this file for default physics config and test objects: 
http://dl.fbaipublicfiles.com/habitat/objects_v0.1.zip

1. We should bundle them together and release a single file. 

2. We should change viewer.cpp to check not habitat-sim/data/ by default, but /path/to/data/ to look for physics config. 

## Motivation

Smoother interaction. People won't have to download multiple files and places them at different places.

**Comment by aclegg3** [comment]
`data/test_assets` includes the default physics config and test scenes.
`src_python/habitat_sim/utils/datasets_download.py` can be used to acquire additional supported datasources.
