### ISSUE TITLE
Question about texture of inserted objects

### ISSUE THREAD

**Issue by dhuber23b** [facebookresearch/habitat-sim#302]
I have a model of a chair, and I am using the object insertion capability to add the model to a test scene.  The texture of the synthetic object does not look very good.  Basically, there is almost no texture at all.  I am wondering if I am doing something wrong.  Maybe I need to add a lighting setting or something?  Attached is a screenshot of the glb file in an online viewer and the image generated by Habitat for the same object.

![screenshot_04](https://user-images.githubusercontent.com/30168838/66875393-02d7ab00-ef63-11e9-8bf0-5ea4346dd3a3.jpg)
![scene_and_object_color_001](https://user-images.githubusercontent.com/30168838/66875459-37e3fd80-ef63-11e9-9463-65a946a446c9.png)

**Comment by dhuber23b** [comment]
I also noticed that the feet on the chair are not being rendered.

**Comment by aclegg3** [comment]
Hey Daniel, you are correct that there is a missing shader issue here. We have a feature in the works to address this. PR #152 shows the current state of that effort, but we intend to improve on this to support additional shaders and settings in the coming months. For now, if you need non-trivial shading via illumination you can check out some of the changes in the `clutter_nav` branch. 

Specifically: src/esp/gfx/GenericDrawable.cpp shows lighting setup in the shader draw.

Happy to chat more about this and help you get a working solution while we get this feature locked down.

**Comment by aclegg3** [comment]
Related to Issue #319

**Comment by aclegg3** [comment]
I have a new prototype branch to address this issue: [phong_shaded_physics_objects](https://github.com/facebookresearch/habitat-sim/tree/phong_shaded_physics_objects). With this branch all scenes are flat shaded via textures (as in master), but objects you add with PhysicsManager are rendered with a Phong illumination shader. The default setup is 8 lights placed at the scene bounding box corners. You can also set the position, color, and intensity of the lights in python (see [example of this functionality](https://github.com/facebookresearch/habitat-sim/blob/4cac4a88d71eddc998d1c0da24f960dc6410e484/examples/demo_runner.py#L226)). As a note, adjusting light intensities [0,1] for all 8 lights is likely the best course of action to immediately use this functionality for new scenes (default is 0.2).

A more complete implementation to come, but this should do what you need presently. Let me know how it goes!

**Comment by AwokeKnowing** [comment]
I think this makes a lot of sense. It seems the general static 'environment'  should be either fully flat or fully shaded, regardless of if it's loaded 'in pieces' (adding chairs).  But at the physics layer, with dynamic rotation, having shading makes sense, regardless of whether the environment is flat or shaded.

I wonder if some optimization could be done where the object's physics are updated more often than the shading.  This could allow a bit more advanced shading but I don't know what it would look like.
