### ISSUE TITLE
How to set object category?

### ISSUE THREAD

**Issue by dhuber23b** [facebookresearch/habitat-sim#320]
When I manually add a physics object to the scene from the library, it has a semantic category of -1.  Is there a way I can set this to something of my choosing?

**Comment by aclegg3** [comment]
Hey Daniel, this feature has been discussed and is WIP. I'll take a look at the engineering effort and see what we can do to prioritize this.

**Comment by aclegg3** [comment]
Update on this issue: #341 is a prototype which allows you to manually configure the semantic category. Improvements to come.

**Comment by aclegg3** [comment]
Update: configurable semantic id is now enabled by #668.
