### ISSUE TITLE
Enable clang-tidy

### ISSUE THREAD

**Issue by msbaines** [facebookresearch/habitat-sim#323]
## 🚀 Feature

Automate coding style checking.

## Motivation

Developers will be more productively navigating the code and making changes if a consistent
style is followed.

## Pitch

clang-tidy also support static analysis.

**Comment by mathfac** [comment]
The task looks finished.

**Comment by msbaines** [comment]
clang-tidy is now enabled but I am still enabling some checks. I can close this and open separate tasks for the currently disabled checks.
