### ISSUE TITLE
Install error: Could NOT find Corrade

### ISSUE THREAD

**Issue by marek-at-work** [facebookresearch/habitat-sim#327]
## Command
`python setup.py install`

## Error message
```
CMake Error at cmake/dependencies.cmake:13 (add_subdirectory):
  The source directory
    /usr/.../habitat-sim-master/src/deps/corrade
  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:50 (include)
CMake Error at /usr/.../anaconda3/envs/habitat/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
  _CORRADE_CONFIGURE_FILE)
Call Stack (most recent call first):
  /usr/.../anaconda3/envs/habitat/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCorrade.cmake:286 (find_package_handle_standard_args)
  cmake/dependencies.cmake:15 (find_package)
  CMakeLists.txt:50 (include)
```

## System Info
Platform: Linux (debian) amd64-x86_64
Machine: x86_64
Libc version: glibc 2.9
Python version: 3.6.9
Architecture: 64bit 
GCC version: gcc 8.2.0
CMAKE version: cmake version 3.14.0
NVIDIA-SMI: Wed Oct 30 21:15:18 2019       
NVIDIA-SMI 390.87
Conda packages versions:
attrs                     19.3.0                   pypi_0    pypi  19.1.0
numba                     0.46.0                   pypi_0    pypi
numpy                     1.17.3                   pypi_0    pypi
numpy-quaternion          2019.10.3.10.26.21          pypi_0    pypi
pillow                    6.2.1                    pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi  1.3.0
tqdm                      4.36.1                   pypi_0    pypi

**Comment by erikwijmans** [comment]
We rely heavily on git submodules, which do not work with Github's zips/tarballs.  Please clone the repo instead.
