### ISSUE TITLE
Physical units for semantic scene

### ISSUE THREAD

**Issue by zseymour** [facebookresearch/habitat-sim#329]
## ❓ Questions and Help
I can't seem to find this information in the documentation:

Do values given by, e.g., the dimensions of the [AABB for scene objects](https://github.com/facebookresearch/habitat-sim/blob/3673f448b6b9f8b404adb235aa882a271bd0e55d/src/esp/scene/SemanticScene.h#L160), the [maximum environment coordinates](https://github.com/facebookresearch/habitat-api/blob/5fd780796fc919680b2783851db7245a3a8db3b6/habitat/utils/visualizations/maps.py#L31), or the values returned from the unnormalized depth sensor have any physically interpretable units associated with them (meters, centimeters, etc.)?

**Comment by erikwijmans** [comment]
This is dependent on the dataset itself.  For Gibson, Matterport3D, and Replica, all of these are in meters.
