### ISSUE TITLE
Render the Agent!

### ISSUE THREAD

**Issue by dhruvbatra** [facebookresearch/habitat-sim#332]
## 🚀 Feature
We should render an actual agent/virtual-robot as opposed to it being an idealized cylinder. Something like in the video here: 
http://crlab.cs.columbia.edu/learning_your_way/

Fetch files: 
http://wiki.ros.org/Robots/fetch

Locobot files: 
https://github.com/facebookresearch/pyrobot/tree/master/robots/LoCoBot/locobot_description

## Motivation

Right now, all observations in habitat-sim are "first-person" egocentric perspective. We should enable "third-person" (camera above/behind the agent's head) videos. However, in order to be intuitive, they should include a rendering of the agent. 

## Details

We don't need full URDF support of articulated parts for this. Initially, we could simply combine all the part meshes into a single hierarchical mesh of the robot and render that. 

I could be mistaken, but I believe it will require providing agent's class with a mesh to be rendered for the agent: 
https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/agent/Agent.cpp

We will need to be careful that the agent's camera doesn't get self-occluded via the agent mesh. 

Also, we should add an overhead camera to the agent so that we can easily create visualization videos like this: 
![IMG_0862](https://user-images.githubusercontent.com/2941091/68060627-7ab81a80-fd44-11e9-8f9e-7c14a4b567eb.jpg)

Issue contains feedback from @erikwijmans and @msavva

**Comment by aclegg3** [comment]
Addressed by #492.
