### ISSUE TITLE
How to get object category label instead of instance label from observation's segmentation

### ISSUE THREAD

**Issue by XiaoSong9905** [facebookresearch/habitat-sim#337]
## ❓ Questions and Help

Hi, 

I'm having trouble to pull out the label category from the observation step(I know recursive through scene would give you all the region, object, but observation doesn't seem to contain that information), the semantic_sensor from the observation step only give me per-instance label instead of per class label. Is there any way to get a per class label? 

The code in the notebook looks like this 

```python
while total_frames < max_frames:
    action = random.choice(action_names)
    print("action", action)
    observations = sim.step(action)
    rgb = observations["color_sensor"]
    semantic = observations["semantic_sensor"]
    depth = observations["depth_sensor"]
    display_sample(rgb, semantic, depth)
    total_frames += 1
```

**Comment by erikwijmans** [comment]
https://github.com/facebookresearch/habitat-api/issues/230#issuecomment-543878652
