### ISSUE TITLE
from habitat_sim._ext.habitat_sim_bindings import

### ISSUE THREAD

**Issue by GELIELEO** [facebookresearch/habitat-sim#366]
## ❓ Questions and Help

from habitat_sim._ext.habitat_sim_bindings import
I can not find this _ext module in the package.

**Comment by erikwijmans** [comment]
Can you please provide additional details?  The full error message would be helpful.

Note that when using `python setup.py install`, `/path/to/habitat-sim` can **not** be in the `PYTHONPATH` nor can your current working directory be `/path/to/habitat-sim` (as the current working directory gets implicitly added to the `PYTHONPATH`).
