### ISSUE TITLE
Cartoonized simulated RGB image

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/habitat-sim#375]
## ❓ Questions and Help

How to get the Cartoonized simulated RGB image (top left in red circle) shown in the repo home page? Is it just from a specific dataset?

![sensor-data_](https://user-images.githubusercontent.com/14010288/70571022-022a5200-1b6b-11ea-9c3b-680d7eeb3786.png)

I tried to search the config in the source code but with no luck. Only found COLOR, DEPTH and SEMANTICS. Any help would be appreciated.

**Comment by aclegg3** [comment]
Yes, this is just a model from a particular dataset. There is no "cartoonized" render mode.

**Comment by BryanBo-Cao** [comment]
@aclegg3 Did you happen to know which dataset? Matterport3D and Gibson use real images.

**Comment by aclegg3** [comment]
@msavva ?

**Comment by dhruvbatra** [comment]
It's from a dataset that is no longer publicly available. We are unable to comment further because of an ongoing litigation.
