### ISSUE TITLE
Agent state rotation doesn't change after  LOOK_DOWN and LOOK_UP but it changes in the SixDOFPose sensor_state

### ISSUE THREAD

**Issue by erick84mm** [facebookresearch/habitat-sim#377]
## 🐛 Bug

Agent state rotation doesn't change after  LOOK_DOWN and LOOK_UP but it changes in the SixDOFPose sensor_state

* Note the code is from Habitat-API just because is easier. But the problem is coming from Habitat-sim.

## Command
`# command that you run`

self._env._sim.get_agent_state()

## To Reproduce

0. set   ACTION_SPACE_CONFIG: "v1" in the config file
1. Perform LOOK_DOWN or LOOK_UP actions
2. query the state of the agent
3. Check that the agent.rotation doesn't change but state["sensor_states"]["rgb"].rotation does change.

```
import habitat
from habitat.sims.habitat_simulator.actions import HabitatSimActions
from pprint import pprint


def transform_rgb_bgr(image):
    return image[:, :, [2, 1, 0]]


def example():
    env = habitat.Env(
        config=habitat.get_config("configs/tasks/pointnav.yaml")
    )
    observations = env.reset()

    initial_state = env._sim.get_agent_state()
    print("initial state")
    pprint(initial_state)
    action = "LOOK_DOWN"
    observations = env.step(action)
    end_state = env._sim.get_agent_state()
    print("end state")
    pprint(end_state)
    

if __name__ == "__main__":
    example()
```

## Expected behavior

Both quaternions should be the same in the SixDOFPose rotation and the Agent state rotation even after LOOK_DOWN or LOOK_UP action happens.

## Additional context

initial state
AgentState(position=array([2.24071 , 3.204603, 5.213   ], dtype=float32), **rotation=quaternion(-0.300010502338409, 0, 0.953935921192169, 0)**, velocity=array([0., 0., 0.]), angular_velocity=array([0., 0., 0.]), force=array([0., 0., 0.]), torque=array([0., 0., 0.]), sensor_states={'rgb': SixDOFPose(position=array([2.24071 , 4.454603, 5.213   ], dtype=float32), **rotation=quaternion(-0.300010502338409, 0, 0.953935921192169, 0)**)})
running action 5
end state
AgentState(position=array([2.24071 , 3.204603, 5.213   ], dtype=float32), rotation=**quaternion(-0.300010502338409, 0, 0.953935921192169, 0)**, velocity=array([0., 0., 0.]), angular_velocity=array([0., 0., 0.]), force=array([0., 0., 0.]), torque=array([0., 0., 0.]), sensor_states={'rgb': SixDOFPose(position=array([2.24071 , 4.454603, 5.213   ], dtype=float32), rotation=**quaternion(-0.297443866729736, 0.0391592308878899, 0.945774912834167, 0.124513633549213)**)})

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/master/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python habitat_sim/utils/collect_env.py
```

 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - GPU models and configuration:
 - CUDA version:
 - PIP/conda dependencies packages versions
 - Any other relevant information:

**Comment by erikwijmans** [comment]
This is expected and intended. Look up and look down effect the sensors, not the agent body.
