### ISSUE TITLE
Explicitly close unused agents to free memory space?

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/habitat-sim#415]
## ❓ Questions and Help

I initialize lots of agents by ```this_agent = sim.initialize_agent(sim_settings["default_agent"])```. When my code is running, some of my agents that were initialized a long time ago are obsolete. So I manually close them by ```this_agent.close()```. If I don't do ```close()``` explicitly and continue initializing agents, I assume that my memory will be filled up?

**Comment by erikwijmans** [comment]
For clarification, `sim.initialize_agent` does not create a new agent, it sets the specified agent to an initial state (or generates a random one if a state isn't provided) and returns a reference to that agent so unless you are also recreating/reconfiguring the simulator also, you will just have many references to the same agent.

To answer your question, the agent does use a little bit of GPU memory for the rendering buffers for its sensors (this is what `.close()` explicitly frees), so you many need to call `.close()` depending on what you are doing.
