### ISSUE TITLE
The error ''No such file or directory: 'build/compile_commands.json' "

### ISSUE THREAD

**Issue by liuxinzhu0353150307** [facebookresearch/habitat-sim#426]
## ❓ Questions and Help

I use the command   python setup.py build_ext --parallel 1 install  to build he habitat-sim in my virture  machine Ubuntu18.04， but when I built it I get the following error:

running build_ext
error: [Errno 2] No such file or directory: 'build/compile_commands.json'

The file compile_commands.json does not exist surely, so how can I solve the problem?

**Comment by bigbike** [comment]
`rm -rf build/`
run `python setup.py install` again.

**Comment by liuxinzhu0353150307** [comment]
> `rm -rf build/`
> run `python setup.py install` again.

Thanks a lot, I have solved the error.

**Comment by 201814476** [comment]
> > `rm -rf build/`
> > run `python setup.py install` again.
> 
> Thanks a lot, I have solved the error.

Can you tell me how to do that? Thanks a lot!
