### ISSUE TITLE
Errors when building navmesh on the fly for replica models. 

### ISSUE THREAD

**Issue by bigbike** [facebookresearch/habitat-sim#430]
## 🐛 Bug
Built the utility viewer. Tried to load it with replica models.

It segfaults.

```
I0114 14:54:13.283030 169991 PTexMeshData.cpp:837] loading atlas textures: 
I0114 14:54:13.283100 169991 PTexMeshData.cpp:846] Loading atlas 1/6 from /home/yili/models/replica/room_1/textures/0-color-ptex.hdr. 
I0114 14:54:13.487493 169991 PTexMeshData.cpp:846] Loading atlas 2/6 from /home/yili/models/replica/room_1/textures/1-color-ptex.hdr. 
I0114 14:54:13.635692 169991 PTexMeshData.cpp:846] Loading atlas 3/6 from /home/yili/models/replica/room_1/textures/2-color-ptex.hdr. 
I0114 14:54:13.754685 169991 PTexMeshData.cpp:846] Loading atlas 4/6 from /home/yili/models/replica/room_1/textures/3-color-ptex.hdr. 
I0114 14:54:13.947890 169991 PTexMeshData.cpp:846] Loading atlas 5/6 from /home/yili/models/replica/room_1/textures/4-color-ptex.hdr. 
I0114 14:54:13.977864 169991 PTexMeshData.cpp:846] Loading atlas 6/6 from /home/yili/models/replica/room_1/textures/5-color-ptex.hdr. 
I0114 14:54:14.013339 169991 PathFinder.cpp:268] Building navmesh with -2147483648x-2147483648 cells
./run: line 3: 169991 Segmentation fault      (core dumped) __GL_SYNC_TO_VBLANK=0 ./build/utils/viewer/viewer /home/{user}/models/replica/room_1/mesh.ply
```

## Command
`# command that you run`

## To Reproduce

1.
2.
3.

## System Info

Please copy and paste the output from the
[environment collection script](https://github.com/facebookresearch/habitat-sim/tree/master/habitat_sim/utils/collect_env.py)
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python habitat_sim/utils/collect_env.py
```

 - OS (e.g., Linux): Fedora 
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - GPU models and configuration:
 - CUDA version:
 - PIP/conda dependencies packages versions
 - Any other relevant information:

**Comment by aclegg3** [comment]
Related to this review comment: https://github.com/facebookresearch/habitat-sim/pull/400/files/e9e13ecbd1cee404e8ef3e036157aba904bf59d0#r364340322

Currently, the navmesh is recomputed by joining all geometry from `BaseMesh::collisionMeshData_`. This data-structure is not populated in PTex load currently, so we can't recompute navmesh (no geometry to find) and physics won't work in these scenes either. 

Once PR #390 is merged we can unify the data-structure for asset geometry references and ensure it is available for all asset types.

**Comment by bigbike** [comment]
A short term solution is introduced by #434. Will put the long term solution in our TODO list. Close it for now.
