### ISSUE TITLE
How do i access the projection matrix and the camera matrix after the update ?

### ISSUE THREAD

**Issue by ronjamoller** [facebookresearch/habitat-sim#440]
Hi, i have pulled the newest code after i read the blog entry on improved object insertion capabilities  from yesterday and now my code does not work anymore, which was to be expected. However, I cant find a way to fix it. I used to access the Projection matrix and Camera matrix via self._sim._sim._sim.get_active_semantic_scene_graph().get_default_render_camera() within the environment class and then call  
pm = render_camera.getProjectionMatrix()
cm = render_camera.getCameraMatrix()
but now none of the functions exist anymore, only setProjectionMatrix()  is still in GfxBindings.cpp. Is the access to the camera reworked or are we not meant to access these matrices anymore, because my whole algorithm hinges on it and i would have no choice but to go back to a previous version if that is the case.

**Comment by erikwijmans** [comment]
The cameras now inherit from https://doc.magnum.graphics/python/magnum/scenegraph/Camera3D/

So `.getProjectionMatrix() -> .projection_matrix` and `.getCameraMatrix() -> .camera_matrix`

**Comment by ronjamoller** [comment]
Thank you !
