### ISSUE TITLE
Preprocessing of ".glb" file.

### ISSUE THREAD

**Issue by smpotdar** [facebookresearch/habitat-sim#470]
## ❓ Questions and Help
Hi!
I have an ".obj" file which I wish to use for physical interaction. The corresponding ".glb" file was obtained by converting a ".obj" file from an online file converter. However, when I load my ".glb" file, I get the following error:

> I0202 19:18:44.484383  8389 ResourceManager.cpp:204] loading object: /home/sirdome/shamit/habitat/habitat-sim/src/../data/objects/Onion.phys_properties.json
I0202 19:18:44.484473  8389 ResourceManager.cpp:1054] Importing Basis files as BC7
Trade::TinyGltfImporter::mesh3D(): interleaved buffer views are not supported
Containers::Optional: the optional is empty
Aborted (core dumped)

I have all the three required file i.e. Onion.glb, Onion.phys_properties.json and Onion_convex.glb.

I think I need to pre-process it in  a certain way for this to work. Is my pre-processing wrong or am I doing some other mistake. Please let me know. Thanks.

**Comment by mosra** [comment]
Hi! This should be fixed as of #496. Can you try again with current master?
