### ISSUE TITLE
Error when run 'setup.py'

### ISSUE THREAD

**Issue by liuxinzhu0353150307** [facebookresearch/habitat-sim#480]
I run the command "sudo python setup.py install", but I got the following error: 
  
File "setup.py", line 388
    subprocess.check_call(shlex.split(f"pip install {pymagnum_build_dir}"))
                                                                        ^
SyntaxError: invalid syntax

I want to know how to solve the roblem.

**Comment by erikwijmans** [comment]
Habitat-sim requires python>=3.6.  Please follow the build instructions here: https://github.com/facebookresearch/habitat-sim#from-source

**Comment by mylad13** [comment]
I am following the build instruction

> Habitat-sim requires python>=3.6. Please follow the build instructions here: https://github.com/facebookresearch/habitat-sim#from-source

I am following these instruction, but I still get the same error when using "python setup.py install". 
![image](https://user-images.githubusercontent.com/109168632/217356162-5cb778a6-2851-4316-8e06-093bed10361d.png)

**Comment by dhruvbatra** [comment]
Note for future viewers: we no longer support python 3.6
