### ISSUE TITLE
coordinate correspondence between blender (or other 3d program) and habitat

### ISSUE THREAD

**Issue by ronjamoller** [facebookresearch/habitat-sim#487]
Hi, I am working on inserting human meshes into the simulation and i would like to know the exact position of the joints of my human mesh. I can import various meshes from blender into habitat but i cannot get to insert the mesh in such a way that i can reliably compute the joint positions relative to the insertion point. With trial and error i have figured out that when a .glb mesh is imported from blender into habitat the y and z axis are mirrored but there are still translation offsets. 
![600](https://user-images.githubusercontent.com/58071555/74233415-e5c1a780-4cca-11ea-8afd-51c1e89d1057.png)

Furthermore, sometimes a mesh will look completely normal in blender and when imported into habitat it is suddenly deformed and translated/rotated. 
![200_blender](https://user-images.githubusercontent.com/58071555/74233474-05f16680-4ccb-11ea-9690-bbe52a201727.png)

![200](https://user-images.githubusercontent.com/58071555/74233572-3afdb900-4ccb-11ea-9d64-15da6f333ca3.png)

edit: here is an example of 2 meshes that have the same orientation in blender, are inserted in exactly the same way into habitat and suddenly face in different directions. This is especially unfortunate because - as can be seen in the image half that is visualised in habitat - the human mesh would be in exactly  the correct position to overlap the joints (pink circles) in the simulation but when the mesh is imported is suddenly changes and the human mesh ends up somewhere else.
![comparison](https://user-images.githubusercontent.com/58071555/74235159-b7de6200-4cce-11ea-96ce-8f9da7e8c209.png)
 

If anyone has experience with inserting objects into habitat in a way that allows coordinate correspondences i would be very thankful for any advice.

**Comment by aclegg3** [comment]
Translational offsets can occur when the COM of the imported object is not specified in the template. In this case, the object's center (often of its bounding box) is used and the asset is translated such that this point is the origin of the local coordinate system. This translational offset is printed to terminal on load, so you should be able to adjust your points by that offset. Alliteratively, if you do not intend to simulate the object, you can define the COM manually as [0,0,0] to prevent any translation from being applied.

**Comment by ronjamoller** [comment]
thank you so much for the tip - i assumed the COM would translate automatically. For anyone else having the issue: just add "COM": [0,0,0], in the phys_properties json , this will make everything match up. 
Thanks again for the help.
Please let me know if you want me to close this issue.
