### ISSUE TITLE
Texture with colors

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/habitat-sim#502]
## ❓ Questions and Help

May I know how could I change the texture of an object to simply a texture with some colors (like a desk is always blue). The lighting and reflection should remain the same on these textures. Note that this is different from the per-category semantic observation that the color representing a category is uniform regardless of lighting source.

Any help would be appreciated.

**Comment by matthewjmay** [comment]
Hi, thanks for the question! Right now material manipulation is not currently supported, so you would need to manipulate the object asset using another software such as [Blender](https://www.blender.org/). We plan to add material manipulation soon, tracked in #506.
