### ISSUE TITLE
Rename LookLeft and LookRight to RotateLeft and RotateRight

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-sim#51]
author @danielgordon10:
https://github.com/fairinternal/habitat-sim/blob/439d586b8c643fd42f53a31a4b15a65af3e39bcf/src/esp/scene/ObjectControls.cpp#L46

Rotate is a better description of what's actually happening since the entire agent body is being rotated along with the camera.
Based on my understanding of previous conversations, we would __not__ want to change lookUp and lookDown to rotate.

This change will have to be synced with one on habitat-api to similarly rename things.

From @dhruvbatra 

> -- "look right/left" --> "turn right/left"? Because after "looking" semantics of "forward" don't necessarily change, but after "turning" they do. 

@erikwijmans:
turnRight/turnLeft already sneakily exist: https://github.com/fairinternal/habitat-sim/blob/master/src/esp/scene/ObjectControls.cpp#L84.

lookRight/lookLeft just need to be removed from the list of body actions and then those will no longer alter the semantics of forward: https://github.com/fairinternal/habitat-sim/blob/master/src/esp/agent/Agent.cpp#L19

**Comment by erikwijmans** [comment]
I added `turn_left` and `turn_right` when refactoring controls: https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/agent/default_controls.py#L75-L76

**Comment by erikwijmans** [comment]
habitat-api also uses those for the turn actions: https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator.py#L200

**Comment by mathfac** [comment]
@erikwijmans, then we just need to clean up and  rename functions with `look right/left` names?

**Comment by erikwijmans** [comment]
The look actions still have reason to exist as actions that solely move the camera (this is their functionality now).

**Comment by dhruvbatra** [comment]
Agreed, we should leave the "look" actions, as their use/semantics are distinctly useful from the "turn" actions.

**Comment by mathfac** [comment]
> The look actions still have reason to exist as actions that solely move the camera (this is their functionality now).

Not sure I fully understand the difference between `turn_left` and `look_left` here.
Based on [this lines of code](https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/agent/default_controls.py#L75-L76):
```
register_move_fn(look_left, "turn_left")
register_move_fn(look_right, "turn_right")
```
actions look equal.

**Comment by erikwijmans** [comment]
The `turn_*`  variants are body-actions: https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/agent/agent.py#L22 so they will turn the body of the agent.
