### ISSUE TITLE
move_forward and (turn_left or turn_right) simultaneously in one step()?

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/habitat-sim#513]
## ❓ Questions and Help
How to move_forward and (turn_left or turn_right) simultaneously in one step()?

As far as I know, step() takes in one action as input while one action can only be one of ```['move_forward', 'turn_left', 'turn_right']``` and specify each action by ```habitat_sim.agent.ActuationSpec(amount={some_value})```.

Any help would be appreciated.

**Comment by erikwijmans** [comment]
You can follow along with these examples to add new actions:
https://github.com/facebookresearch/habitat-sim/blob/master/examples/new_actions.py
https://github.com/facebookresearch/habitat-api/blob/master/examples/new_actions.py
