### ISSUE TITLE
Object Insertion

### ISSUE THREAD

**Issue by shivanshpatel35** [facebookresearch/habitat-sim#570]
Hi,
I am trying to insert objects in habitat-sim. I have a few questions that are not covered in the documentation or in the existing GitHub issues:
1. What happens if the mesh of the inserted object overlaps with an already existing mesh on translation using `sim.set_translation(object_position, object_id)? `
2. Is there a way to ensure that the objects are placed on the ground or on a surface?

Thanks in advance!
CC: @saimwani

**Comment by aclegg3** [comment]
Hey @shivanshpatel35, more docs coming soon!

For now, if the object is `MotionType::KINEMATIC`, it doesn't matter if there is overlap. If the object is `MotionType::DYNAMIC`, then overlap of collision shapes will likely result in an impulse force applied to the object at the next simulation step. 

You can check for overlap in collision shapes (if using Bullet) with the `contact_test(object_id)` function.

To place objects on the floor you can try querying navigable points from the pathfinder: `sim.pathfinder.get_random_navigable_point()`. Depending on your NavMeshSettings when the navmesh was generated different features will be navigable (e.g. radius, height, climb height and slope, etc). You can play with this in the veiwer.cpp demo. Use 'n' there to visualize the navmesh if you want to tune it for your use case.
