### ISSUE TITLE
Unexpected behavior of Semantic Sensor after Object Insertion

### ISSUE THREAD

**Issue by shivanshpatel35** [facebookresearch/habitat-sim#576]
## Bug

Hi, I am inserting objects using habitat-api. When I visualize results, RBG and Depth sensors work as expected, but the Semantic Sensor ignores the inserted object. This can be verified [here](https://drive.google.com/open?id=1zN7pGPkIdriIinwolhtpCV8ZrWeo8T7Y). 
Also, the inserted object does not appear in `env._sim.semantic_annotations()`. Perhaps some existing functionalities do not completely support inserted objects.
@aclegg3

**Comment by aclegg3** [comment]
@shivanshpatel35 thanks for opening this issue. You are correct that semantic rendering of non-scene objects is not fully supported at this time. There is a draft PR (#341) which began to address this awhile back. This is something which we should look into again.

**Comment by shivanshpatel35** [comment]
Hi @aclegg3 , 
I notice that there are no updates in PR #341 . Will this be fixed anytime soon?

**Comment by aclegg3** [comment]
PR #668 addresses this by enabling configurable semantic ids for rendering non-scene objects with `SEMANTIC` sensor.
