### ISSUE TITLE
web browser failed to retrieve Request URL: https://habitat-resources.s3.amazonaws.com/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb

### ISSUE THREAD

**Issue by rabbit721** [facebookresearch/habitat-sim#649]
## ❓ Questions and Help
Hi, I followed the below steps, and inspect the webpage and see that it failed to retrieve the data from s3. 

Request URL: https://habitat-resources.s3.amazonaws.com/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb

I downloaded and extracted the test data locally, so I have /habitat-sim/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb. But I don't know how to force binding_js to look for the local file instead of getting it from s3. 

Thanks!

**Comment by dhruvbatra** [comment]
CC: @apsdehal @msbaines

**Comment by apsdehal** [comment]
@rabbit721 Hi,

If you running it locally, please use localhost address so that configuration can adjust accordingly. See https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/bindings_js/modules/defaults.js#L33.

**Comment by rabbit721** [comment]
I am running it inside google colab. So I used colab's kernel's own proxy port instead of localhost. Is there another way to specify using the local test data?

**Comment by apsdehal** [comment]
IIRC, you should be able to specify `scene=<path>` directly in your url.

**Comment by rabbit721** [comment]
It works, thanks a lot!
