### ISSUE TITLE
Cannot Modify Agent Action Spaces in agent.py

### ISSUE THREAD

**Issue by medhagitnod** [facebookresearch/habitat-sim#65]
I want to modify the default_action_space method in agent.py such that backwards movement is a default movement as well. However when I change the method from 
def _default_action_space():
    return dict(
        move_forward=ActionSpec("move_forward", ActuationSpec(amount=0.25)),
        turn_left=ActionSpec("turn_left", ActuationSpec(amount=10.0)),
        turn_right=ActionSpec("turn_right", ActuationSpec(amount=10.0)),
)
to 
def _default_action_space():
    return dict(
        move_forward=ActionSpec("move_forward", ActuationSpec(amount=0.5)),
        move_backward=ActionSpec("move_backward", ActuationSpec(amount=0.5)),
        turn_left=ActionSpec("turn_left", ActuationSpec(amount=90.0)),
        turn_right=ActionSpec("turn_right", ActuationSpec(amount=90.0)),
    )
However, after implementing these changes the dictionary when printed still looks like: 
{'move_forward': ActionSpec(name='move_forward', actuation=ActuationSpec(amount=0.25)), 'turn_left': ActionSpec(name='turn_left', actuation=ActuationSpec(amount=10.0)), 'turn_right': ActionSpec(name='turn_right', actuation=ActuationSpec(amount=10.0))}

I installed habitat-sim with setup.py, must I use the developer installation in order to be able to modify agent.py? I have implemented a new method in simulator.py without any issues as well as added print lines to agent.py so I am unsure as to why default agent movement is unable to be modified.

**Comment by erikwijmans** [comment]
Yes, if you want to modify source code, `python setup.py install` won't work.  You should use `build.sh` instead (build.sh is just a wrapper around `python setup.py build_ext --inplace`).

You can also see how to modify the agent's action space from _outside_ the source code here: https://github.com/facebookresearch/habitat-sim/blob/master/examples/new_actions.py
