### ISSUE TITLE
Using semantic annotations

### ISSUE THREAD

**Issue by VladislavHrosinkov** [facebookresearch/habitat-sim#666]
## ❓ Questions and Help
Sorry for the basic question, but how can one access semantic annotations? I am attempting to save images and semantic annotations in files side by side following this example https://aihabitat.org/docs/habitat-api/habitat-api-demo.html#actions-and-sensors with modifications to save images. However, the semantic images turn out grey, except the black space on the van-gogh scene is sometimes partially blue. Here is the beginning information text (I presume the fact there are no semantic annotations is most important):

2020-06-29 17:46:39,936 Initializing dataset PointNav-v1
2020-06-29 17:46:40,127 initializing sim Sim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0629 17:46:40.141813 251131328 Simulator.cpp:96] Loading navmesh from habitat-api/data/scene_datasets/habitat-test-scenes/van-gogh-room.navmesh
I0629 17:46:40.145870 251131328 Simulator.cpp:98] Loaded.
I0629 17:46:40.145929 251131328 SceneGraph.h:92] Created DrawableGroup: 
Renderer: AMD Radeon Pro 570X OpenGL Engine by ATI Technologies Inc.
OpenGL version: 4.1 ATI-2.11.20
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_vertex_array_object
    GL_EXT_debug_label
    GL_EXT_debug_marker
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    apple-buffer-texture-unbind-on-buffer-modify
I0629 17:46:40.203069 251131328 ResourceManager.cpp:1407] Importing Basis files as BC3
W0629 17:46:41.044292 251131328 Simulator.cpp:199] :
---
 The active scene does not contain semantic annotations. 
---
I0629 17:46:41.044631 53440 simulator.py:146] Loaded navmesh habitat-api/data/scene_datasets/habitat-test-scenes/van-gogh-room.navmesh
2020-06-29 17:46:41,046 Initializing task Nav-v0

**Comment by aclegg3** [comment]
Hey @VladislavHrosinkov. You are absolutely right here. That message is informing you that the van-gogh-room asset has no semantic annotations to render. You'll need to try another scene. The [Replica dataset](https://github.com/facebookresearch/Replica-Dataset) is example.
