### ISSUE TITLE
Where is 'habitat_sim._ext'?

### ISSUE THREAD

**Issue by 516875454** [facebookresearch/habitat-sim#701]
## ❓ Questions and Help
  File "/home/zhp/habitat-sim/habitat_sim/nav/__init__.py", line 1, in <module>from habitat_sim._ext.habitat_sim_bindings import (
ModuleNotFoundError: No module named 'habitat_sim._ext'

help!!!

**Comment by Skylion007** [comment]
This happens if you try to run habitat from the root folder of the habitat-sim git repo and habitat-sim has not built with the --inplace argument. Either build it using build.sh, delete the habitat-sim folder, or call it from a different location.

**Comment by 20481535** [comment]
Coule you add above statements to the readMe?

**Comment by erikwijmans** [comment]
This issue is fixed in more recent versions
