### ISSUE TITLE
accessing build/viewer

### ISSUE THREAD

**Issue by VladislavHrosinkov** [facebookresearch/habitat-sim#703]
## ❓ Questions and Help
How does one access build/viewer code? It does not seem to be on GitHub.

**Comment by Skylion007** [comment]
Just pass -DBUILD_GUI_VIEWERS=ON to CMake.

**Comment by VladislavHrosinkov** [comment]
Forgive me, but how is CMake involved? I know it it a dependency, but I have installed it without specifically in invoking it.

**Comment by erikwijmans** [comment]
> How does one access build/viewer **code**

Is this what you are looking for: https://github.com/facebookresearch/habitat-sim/blob/master/src/utils/viewer/viewer.cpp?

**Comment by KenaHemnani** [comment]
How to build this viewer as it is already not there in build folder?

**Comment by aclegg3** [comment]
You'll need to build habitat-sim for a system with display as described here: https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md (i.e., do not include the --headless argument).

**Comment by KenaHemnani** [comment]
Hii @aclegg3 thank you for response , I installed habitat-sim using the same .But, still got error as :
**./build/viewer no such file or directory exists.**

**Comment by aclegg3** [comment]
@KenaHemnani then we'll need more info from your build before we can move forward. You should see an alias to viewer in the habitat-sim/build directory and a habitat-sim/utils/viewer/ directory containing the viewer application.

**Comment by KenaHemnani** [comment]
Hii @aclegg3 I reinstalled habitat-sim using conda . The headless version is working fine , but with display I am not able to visualize even with VNC , Yes I do have habitat-viewer inside habitat-sim/utils/viewer/ directory .So, I run following command
 **./habitat-viewer ~/DIR/habitat-lab/data/scene_datasets/hitat-test-scenes/skokloster-castle.glb**
It shows following `error:
![image](https://user-images.githubusercontent.com/73054008/99804913-ba28f300-2b61-11eb-8dd8-ef059f4ee746.png)

Is there any other way to visualize the performance of agents as how it is navigating inside 3D habitat environment? locally on small dataset.
`
