### ISSUE TITLE
How to extract single color per object in semantic segmentation

### ISSUE THREAD

**Issue by qmaruf** [facebookresearch/habitat-sim#711]
## ❓ Questions and Help
I am following this example https://aihabitat.org/docs/habitat-api/habitat-sim-demo.html to extract semantic segmentation data from Replica dataset. Here is an output.

![image](https://user-images.githubusercontent.com/530250/89006596-6e500500-d34a-11ea-948b-906e6a09a531.png)

I am wondering why the `chair`/`table` instance has multiple color code? Is it changing because of the angular distance? How can I get a unique color code per object?

**Comment by erikwijmans** [comment]
That doesn't look correct, can you please provide the mesh name and agent position?

**Comment by qmaruf** [comment]
I was using `mesh_preseg_semantic.ply` instead of `mesh_semantic.ply`. The output seems Ok now.

![image](https://user-images.githubusercontent.com/530250/89122236-098ed900-d509-11ea-9df3-268012cfc7be.png)

What is the difference between these two files?
Here is the notebook for reference. https://colab.research.google.com/drive/14t0oOuDTKgH-awUohwoJZ79nus96BmRS?usp=sharing

**Comment by erikwijmans** [comment]
Ah, that makes sense.  Preseg is a planar decomposition that creates the segments that are joined together to create the instances (there is also sometimes a little bit of manual fine-tuning).
