### ISSUE TITLE
Generate a ground truth map 

### ISSUE THREAD

**Issue by Singh-sid930** [facebookresearch/habitat-sim#725]
## ❓ Questions and Help
Hi, 
I am looking to perform some learning based computations and predictions for which the ground truth map is required of the entire floor. 

Is it possible to do that somehow or the only way is to keep sampling and stitch the samples together. I understand that the sampling happens at random? Any way to control that too?

**Comment by Skylion007** [comment]
You mean something like this?
https://github.com/facebookresearch/habitat-sim/pull/718

**Comment by ssinghsg** [comment]
Yes Exactly! But along with semantic tags. I am guessing that can be included there by changing the observation parameters?
