### ISSUE TITLE
Interfacing with the interactive viewer

### ISSUE THREAD

**Issue by yanweiw** [facebookresearch/habitat-sim#726]
Hi Everyone - 

Is there a way to interface with the interactive viewer? Specifically, I hope to manually drive the agent in the interactive viewer with a keyboard, while logging down actions, states, and observations. Then I hope to run my trained model to infer actions from the observations I have just saved to see if the agent can navigate from the same starting location to the goal location with its own model. Do API or hacks exist for me to achieve such functionality to test the agent interactively on the fly? 

Thank you for your inputs!

**Comment by dhruvbatra** [comment]
#727
