### ISSUE TITLE
remove a pre defined object

### ISSUE THREAD

**Issue by saishankarn** [facebookresearch/habitat-sim#739]
Is it possible to remove any object like a chair/bed which is already defined in a scene ?

**Comment by mathfac** [comment]
Hi @saishankarn,
For Matterport3D and Gibson scenes objects are part of a large mesh and can't be removed, unless the objects was [inserted programmatically from a library of the objects](https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html#kinematic-object-placement).

**Comment by saishankarn** [comment]
thank you
