### ISSUE TITLE
CORS error in browser demo

### ISSUE THREAD

**Issue by pringithub** [facebookresearch/habitat-sim#743]
## 🐛 Bug

Trying to open the browser demo. On latest Chrome version `Version 84.0.4147.125 (Official Build) (64-bit)` on Ubuntu 18.04.

Getting a CORS request error

![image](https://user-images.githubusercontent.com/10574422/90544304-f741ab80-e154-11ea-8260-e7d712fe7607.png)

**Comment by Skylion007** [comment]
Odd... can't reproduce on OSX Chrome:
Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by Skylion007** [comment]
@pringithub Make sure the demo is open in HTTPS. I think our CORS scripts support http://

**Comment by pringithub** [comment]
Didn't work with either.

**Comment by Skylion007** [comment]
https://github.com/facebookresearch/habitat-lab/issues/416

**Comment by Skylion007** [comment]
@pringithub This is a known issue that happens when the webpage is opened as HTTP instead of HTTPS as the error log indicates.

**Comment by Skylion007** [comment]
We changed some settings on our website to enforce strict HTTPS. Reopen if the issue persists.
