### ISSUE TITLE
How to get better quality rgb image from color sensor

### ISSUE THREAD

**Issue by qmaruf** [facebookresearch/habitat-sim#772]
## ❓ Questions and Help

I have modified the [image extractor tutorial ](https://aihabitat.org/docs/habitat-sim/image-extractor.html) and the [shortest path follower example](https://github.com/facebookresearch/habitat-lab/blob/4657d5b3e76760b979b19f43667f97e151d6d690/examples/shortest_path_follower_example.py)  to move an agent randomly in a scene. The scene is from matterport3d dataset (id E9uDoFAP3SH).  However, the rgb image quality is not that good.

Is it the maximum quality of the rgb image or is there any way to improve the quality? 

![ezgif-4-63f0bd302026](https://user-images.githubusercontent.com/530250/91680123-a89d0400-eb8d-11ea-929b-cddcc1d6a3d4.gif)

A long video is available here. https://www.youtube.com/watch?v=m85no2aqJn0&feature=youtu.be

**Comment by Skylion007** [comment]
You can increase the resolution of the sensors and the map. That should make it look less pixelated

As for the holes in the scene, that is unfortunately just part of the scene dataset. If you need a more photorealistic environment, try the Replica dataset.
