### ISSUE TITLE
Automatically generating static rendering data from replica

### ISSUE THREAD

**Issue by ayushjain1144** [facebookresearch/habitat-sim#773]
## ❓ Questions and Help
Hi,

Thank you for the amazing work on this repository!

I want to generate static data from the replica, more specifically: camera intrinsics & extrinsics, RGB image, depth image, instance segmentation and bounding box. The only constraint it is that : The images should represent something useful - without being heavily occluded, and it should adequately capture the data for multiview training.

I could write a script through which I can manually navigate and capture data using keyboard and actions provided by the agent. I was wondering if there is a way to do that automatically so that it can be used even for bigger datasets like matterplot3D. Any insights will be highly appreciated.

Thank You
Ayush

**Comment by Skylion007** [comment]
See examples/instance_segmentation
