### ISSUE TITLE
IMU sensor support ?

### ISSUE THREAD

**Issue by youzhenxing** [facebookresearch/habitat-sim#787]
## 🚀 Feature

Is there any plans for imu sensor type support? I mean IMU is also an very common sensor type for robot navigation.

**Comment by youzhenxing** [comment]
Is there any plans for imu sensor type support? I meas IMU is also an very common sensor type for robot integration.

**Comment by Skylion007** [comment]
How would you envision this IMU sensor? How would deviate from knowing the ground truth translation/rotation from the start point? We do have similar sensors GPS+Compass in our Habitat-Lab repo.

**Comment by youzhenxing** [comment]
> How would you envision this IMU sensor? How would deviate from knowing the ground truth translation/rotation from the start point? We do have similar sensors GPS+Compass in our Habitat-Lab repo.

One of the scenarios is to use habitat-sim to do visual internal fusion based localization. There are still differences and modeling errors  between using differential of GPS+Compass data  to simulate IMU data and the direct IMU model characteristics

**Comment by dhruvbatra** [comment]
> There are still differences and modeling errors between using differential of GPS+Compass data to simulate IMU data and the direct IMU model characteristics

Agreed, but are there realistic IMU noise models available online? Because if not, then differential of GPS+Compass is the noise-free IMU measurement.

**Comment by ltstein** [comment]
Could a similar approach to other robotics simulators be used where there is a bias and noise is added to the perfect data, such as in [Gazebo](http://gazebosim.org/tutorials?tut=sensor_noise#IMUnoise), especially with the recent addition of physics? However, it might be out of scope for habitat sim and  may be a better use case for the ROS-X-Habitat package so you can use another simulator such as Ignition Gazebo for certain portions and then train the higher level agent using the Habitat sim.
