### ISSUE TITLE
Calculate depth image

### ISSUE THREAD

**Issue by rainbow979** [facebookresearch/habitat-sim#825]
The value of depth image is the forward direction of camera and object, not the Euclidean distance, right?
Could someone tell me how to calculate the depth image

**Comment by Skylion007** [comment]
I am not sure what you are asking, do you want a depth sensor that implements ray tracing and something more complex than a pinhole camera model? You can raytray individual points using the bullet raytrace function, but it would be slow to build a depth image like that as it runs on the CPU.

We currently don't support ray trace rendering in Habitat, but you are welcome to add it.

**Comment by Skylion007** [comment]
Reopen if this doesn't solve your issue.
