### ISSUE TITLE
Permission denied Linux with --user option

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/habitat-sim#83]
## Steps to reproduce

  1. python setup.py install --user

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  ccache: error: Failed to create temporary file for /home/phong/.ccache/tmp/tmp.cpp_stderr: Permission denied
![image](https://user-images.githubusercontent.com/11288381/59831251-132ba080-934a-11e9-9391-937c04fd911d.png)
Hello guys,
I have been trying to install habitat_sim on the conda environment but somehow I am having issue with "Permission denied" even when I add --user in the set up command. Is there anything I should do to fix this ?

**Comment by erikwijmans** [comment]
That seems to be an issue with your install of ccache.  You can use `export CCACHE_DISABLE=1` to disable it.
