### ISSUE TITLE
Google Collab: Import habitat_sim fails

### ISSUE THREAD

**Issue by srkiyengar** [facebookresearch/habitat-sim#831]
## ❓ Questions and Help
Hi,

I am trying to get habitat-sim installed and working in colab.

After running the script the colab_install.sh from habitat-sim/examples/colab_utils/ in colab, while importing habitat_sim, I encounter the following error:
![colab-habitat_sim_error](https://user-images.githubusercontent.com/14953117/95282352-9fa7ee00-082f-11eb-927d-37b015862f2f.PNG)

Any suggestion on how to fix this or what may be wrong with my installation of habitat will be appreciated.

Thanks,
Rajan

**Comment by Skylion007** [comment]
I can't repro with our colabse: https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb

No idea why it would be built against Bullet 2.88, it should be Bullet 2.89 

@mathfac could there be a bug with the stable conda build release script?
