### ISSUE TITLE
How to check number of floors in the scene in mp3d dataset? 

### ISSUE THREAD

**Issue by Singh-sid930** [facebookresearch/habitat-sim#841]
## ❓ Questions and Help
Is there anyway we can found out how many floors are in the scene on which episode is running. And/or the floor which the robot is on ?  We are working on the Mp3d Dataset.

**Comment by Skylion007** [comment]
The semantic LEVELs attribute in MP3D is probably what you are looking for. Just to do a check for which AABB bounding box the agent is in. Also make sure to use the latest master as we just fixed. a bug with the bounding boxes in MP3D. #832 

Example below in our ECCV tutorial
https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb#scrollTo=6s1B7Kg5Megl
