### ISSUE TITLE
how to create a demo like :https://aihabitat.org/demo/ 

### ISSUE THREAD

**Issue by Mingxiao-Li** [facebookresearch/habitat-sim#842]
## ❓ Questions and Help
Hi , I am wandering is there a tutorial about how to create this kind of demo (https://aihabitat.org/demo/), in which user can control the agent ?

**Comment by Skylion007** [comment]
Instructions for running the demo locally are here: https://github.com/facebookresearch/habitat-sim#webgl

**Comment by Mingxiao-Li** [comment]
Hi , thanks but I mean the tutorial of creating this kind of demo instead of running it.

**Comment by Skylion007** [comment]
There is currently not, but you are welcome to contribute one.
