### ISSUE TITLE
Build problem 

### ISSUE THREAD

**Issue by Gabesarch** [facebookresearch/habitat-sim#853]
## 🐛 Bug

I am trying to build habitat-sim on a previous commit for getting a baseline on another model, but am running into a cmake error at the very end of building. 
I am using: 
- Ubuntu 16.04
- gcc 7.5.0

Steps to reproduce: 

```
conda create -n habitat python=3.6 cmake=3.14.0
conda activate habitat
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
git checkout 9575dcd45fe6f55d2a44043833af08972a7895a9
pip install -r requirements.txt
python setup.py install --headless
```

I've tried: 
1. sudo apt install libegl1-mesa-dev
2. installing without --headless
4. conda install ninja

Here is the error log: 
[log.txt](https://github.com/facebookresearch/habitat-sim/files/5368459/log.txt)

**Comment by erikwijmans** [comment]
I guess that is before the PR that solved this issue: https://github.com/facebookresearch/habitat-sim/issues/205. Please cherry-pick in https://github.com/facebookresearch/habitat-sim/pull/247
