### ISSUE TITLE
How to modify the red box icon in the topdown map?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/habitat-sim#857]
How to modify the red box icon in the topdown map?
![image](https://user-images.githubusercontent.com/34536352/95946641-8dc1de80-0e1f-11eb-8b6c-31852c92838f.png)

**Comment by dhruvbatra** [comment]
https://github.com/facebookresearch/habitat-lab/blob/master/habitat/utils/visualizations/maps.py

Wrong repository.

**Comment by dhruvbatra** [comment]
Also, check out Hab-Sim for Navigation tutorial here: 
https://aihabitat.org/tutorial/2020/
