### ISSUE TITLE
How to add the motion blur to the saved image?

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/habitat-sim#864]
## ❓ Questions and Help
Thanks for your great project! I have tested some interesting functions and all works perfectly!
And I notice the gif in README, which the fast motion can have an effect of motion blur. 
![Screenshot from 2020-10-16 22-24-58](https://user-images.githubusercontent.com/54199992/96271537-983ace80-0fff-11eb-912f-5b4dda231177.png)

But I only find the option to add noise. Can you give me a quick idea of how to add the motion blur to the saved image?

**Comment by erikwijmans** [comment]
That was either added in post or is an artifact of aggressive video compression.  Habitat doesn't currently support adding motion blur.

**Comment by sparsh-umd** [comment]
Is there a way to add blur to the scene?

Thanks!
