### ISSUE TITLE
Mapping coordinate system between blender and habitat-sim

### ISSUE THREAD

**Issue by Ainaz99** [facebookresearch/habitat-sim#868]
## ❓ Questions and Help
Hi, 
I'm trying to map the replica mesh coordinates in blender to habitat-sim, but I don't know how to do that. Thank you so much!

**Comment by aclegg3** [comment]
The Replica meshes share Blender coordinate system (Z up, Y forward). Habitat uses a Y up, -Z forward convention, so all coordinates are transformed into this frame.

**Comment by Ainaz99** [comment]
Thanks!

> The Replica meshes share Blender coordinate system (Z up, Y forward). Habitat uses a Y up, -Z forward convention, so all coordinates are transformed into this frame.
