### ISSUE TITLE
build/viewer not exist

### ISSUE THREAD

**Issue by Pixie412** [facebookresearch/habitat-sim#878]
## ❓ Questions and Help
hello, 
I installed habitat-sim via this command: "conda install habitat-sim -c conda-forge -c aihabitat". I can successfully run examples/example.py, but I can't run "./build/viewer /path/to/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb". I found that in the "build folder", there is no viewer. So strange... Any suggestions? 
This is my build folder:
<img width="177" alt="1" src="https://user-images.githubusercontent.com/72333326/96663541-6c16a900-1383-11eb-8a24-78d3d3b1cf48.png">

**Comment by erikwijmans** [comment]
When installing from conda, it will be `habitat-viewer`
