### ISSUE TITLE
Can't find `download_mp.py`

### ISSUE THREAD

**Issue by nickgraz** [facebookresearch/habitat-sim#88]
## Steps to reproduce

1. Clone repo (or open in Github)
2. Search for `download_mp.py` in repo

In the Readme, an urgent [update](https://github.com/facebookresearch/habitat-sim/blob/master/README.md#updates) is mentioned regarding the Matterport3D dataset, and to use the `download_mp.py` script to download it. It is also mentioned in the [Datasets](https://github.com/facebookresearch/habitat-sim/blob/master/README.md#datasets) section, and a command is given to run it. Where is this file? I am can't find it anywhere in the repo or any pull requests. Thanks!

![2019-06-25 23 05 26](https://user-images.githubusercontent.com/9541815/60152452-cf97c300-979d-11e9-8bec-ccea99db0f24.gif)

**Comment by erikwijmans** [comment]
`download_mp.py` is distributed by matterport. Please follow the instructions here: https://github.com/facebookresearch/habitat-sim#datasets

**Comment by nickgraz** [comment]
I see, thanks!
