### ISSUE TITLE
adding a MOVE_BACK action

### ISSUE THREAD

**Issue by ronjamoller** [facebookresearch/habitat-sim#904]
## ❓ Questions and Help
Hi, my goal is pretty easy to explain: I want to add a move_back action - from what i can see in the default.py files, right now there is support for `_C.TASK.POSSIBLE_ACTIONS = ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]`, and later ```
ACTIONS.MOVE_FORWARD = CN()
ACTIONS.MOVE_FORWARD.TYPE = "MoveForwardAction"
ACTIONS.TURN_LEFT = CN()
ACTIONS.TURN_LEFT.TYPE = "TurnLeftAction"
ACTIONS.TURN_RIGHT = CN()
ACTIONS.TURN_RIGHT.TYPE = "TurnRightAction"
ACTIONS.LOOK_UP = CN()
ACTIONS.LOOK_UP.TYPE = "LookUpAction"
ACTIONS.LOOK_DOWN = CN()
ACTIONS.LOOK_DOWN.TYPE = "LookDownAction"
ACTIONS.TELEPORT = CN()
ACTIONS.TELEPORT.TYPE = "TeleportAction"
```
How should i go about adding a move_back action ? should i add a new entry or piggyback off the teleport action ?
thanks !

**Comment by Skylion007** [comment]
https://github.com/facebookresearch/habitat-lab/blob/master/examples/new_actions.py
