### ISSUE TITLE
Importing articulated objects

### ISSUE THREAD

**Issue by ksengin** [facebookresearch/habitat-sim#922]
## ❓ Questions and Help
Hello there,

I was wondering if we can import articulated mesh objects in habitat sim, such as .fbx files. 
If not, do you have any suggestions for adding a walking human in the environment?
Any help is appreciated.

**Comment by Skylion007** [comment]
We have an experimental branch for articulated objects imported via URDF: https://github.com/facebookresearch/habitat-sim/tree/urdf-parser

**Comment by ksengin** [comment]
I see, thank you
