### ISSUE TITLE
Issues on runing examples/example.py

### ISSUE THREAD

**Issue by ruoyuwangeel4930** [facebookresearch/habitat-sim#938]
## ❓ Questions and Help
Hi guys!

I have installed habitat-sim using conda with the following command:

`conda install habitat-sim -c conda-forge -c aihabita`,

and then I tried to run the `example/example.py`:

`python examples/example.py --scene habitat-test-scenes/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb 
`.

Here is the error I got:

sim_cfg.physics_config_file = ./data/default.physics_config.json
Traceback (most recent call last):
  File "examples/example.py", line 70, in <module>
    perf = demo_runner.example()
  File "/home/ruoyu/project/habitat-sim/examples/demo_runner.py", line 409, in example
    start_state = self.init_common()
  File "/home/ruoyu/project/habitat-sim/examples/demo_runner.py", line 322, in init_common
    self._cfg = make_cfg(self._sim_settings)
  File "/home/ruoyu/project/habitat-sim/examples/settings.py", line 53, in make_cfg
    sim_cfg.scene_id = settings["scene"]
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'scene_id'

It seems that there is a missing attribute 'scene_id'. Could anyone help me with this? Thank you very much!

**Comment by Skylion007** [comment]
That is due to an api_change. You need to either checkout the tagged repo version that matches the conda install or install it from the aihabitat-nightly channel.
