### ISSUE TITLE
Wrong category for semantic_scene.object

### ISSUE THREAD

**Issue by fraazor** [facebookresearch/habitat-sim#948]
## ❓ Questions and Help
Hello again!

I am not sure whether I am dealing with an error of mine, an error in habitat sim or if the mp3 annotation itself is faulty.
The scene is 17DRP5sb8fy.
I am building a semantic map  on top of the gt maps of the occupancy anticipation paper.
For the semantic masks, I am using the position/dimension of objects from the semantic_scene. I built this dic that I use to map the objects.

scene = env.habitat_env.sim.semantic_scene
obj_pos = {}
for name in label_idx.keys():
    obj_pos[name] = {obj.id : [obj.aabb.center,obj.aabb.sizes]
                        for obj in scene.objects
                        if name == obj.category.name()}

For the key "tables" I receive four obj. 3 of them working out fine but one of them does not seem to exist in reality. That table is in the middle of the room where there is supposed to be nothing. The only thing the bb could possibly capture is the carpet. I have a similar situation with one "chair" object where once again, most chairs are fine, but again one shows possibly in place of a carpet.

The table object in doubt has the id "0_7_132". 

This scene also only appears to have one level so I don't think it comes from a lower or upper floor.

![Bildschirmfoto 2020-11-25 um 14 08 31](https://user-images.githubusercontent.com/29123898/100231941-fa082580-2f27-11eb-900a-84e534a4ff29.png)

![Bildschirmfoto 2020-11-25 um 14 09 47](https://user-images.githubusercontent.com/29123898/100231950-fc6a7f80-2f27-11eb-97a3-745f436e84af.png)

**Comment by erikwijmans** [comment]
For the first thing, that is due to a difference in reconstruction for the mesh used for RGB rendering and the mesh with semantic labels.  The mesh with semantic labels is generally a much worse reconstruction, but sometimes it has things that the RGB mesh doesn't.
![image](https://user-images.githubusercontent.com/12722529/100260331-46973500-2f17-11eb-98da-4e0c8df88e68.png)

For the second case, there is something there in that location:
![image](https://user-images.githubusercontent.com/12722529/100260620-9ece3700-2f17-11eb-888e-cc22861b22f4.png)
I would probably call that a table tho.

In general, the annotations in the mp3d dataset are not perfect.  They are pretty good but not perfect.

**Comment by fraazor** [comment]
Thank you again Erik! The second table is supossed to be a chair but I assume it categorized the couch as a chair. It seems all good then.

**Comment by vincent341** [comment]
> ## ❓ Questions and Help
> Hello again!
> 
> I am not sure whether I am dealing with an error of mine, an error in habitat sim or if the mp3 annotation itself is faulty. The scene is 17DRP5sb8fy. I am building a semantic map on top of the gt maps of the occupancy anticipation paper. For the semantic masks, I am using the position/dimension of objects from the semantic_scene. I built this dic that I use to map the objects.
> 
> scene = env.habitat_env.sim.semantic_scene obj_pos = {} for name in label_idx.keys(): obj_pos[name] = {obj.id : [obj.aabb.center,obj.aabb.sizes] for obj in scene.objects if name == obj.category.name()}
> 
> For the key "tables" I receive four obj. 3 of them working out fine but one of them does not seem to exist in reality. That table is in the middle of the room where there is supposed to be nothing. The only thing the bb could possibly capture is the carpet. I have a similar situation with one "chair" object where once again, most chairs are fine, but again one shows possibly in place of a carpet.
> 
> The table object in doubt has the id "0_7_132".
> 
> This scene also only appears to have one level so I don't think it comes from a lower or upper floor.
> 
> ![Bildschirmfoto 2020-11-25 um 14 08 31](https://user-images.githubusercontent.com/29123898/100231941-fa082580-2f27-11eb-900a-84e534a4ff29.png)
> 
> ![Bildschirmfoto 2020-11-25 um 14 09 47](https://user-images.githubusercontent.com/29123898/100231950-fc6a7f80-2f27-11eb-97a3-745f436e84af.png)

Hi. I'm attempting to create 2D top-down semantic maps for MP3D. I know this link was some time ago. Would you mind giving more details on how you created the 2D top-down semantic maps? Great thanks!

**Comment by vincentcartillier** [comment]
Hi @vincent341 , you can check the following project: [Semantic-MapNet](https://github.com/vincentcartillier/Semantic-MapNet) in which we built such top-down semantic maps for MP3D.

Specifically you should check the following scripts:
```
data/build_point_cloud_from_mesh_h5.py
compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py
```

**Comment by vincent341** [comment]
> Hi @vincent341 , you can check the following project: [Semantic-MapNet](https://github.com/vincentcartillier/Semantic-MapNet) in which we built such top-down semantic maps for MP3D.
> 
> Specifically you should check the following scripts:
> 
> ```
> data/build_point_cloud_from_mesh_h5.py
> compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py
> ```

@vincentcartillier Thanks so much for the link. You saved my day!
