### ISSUE TITLE
Camera calibration and distortion parameters

### ISSUE THREAD

**Issue by mmahdavian** [facebookresearch/habitat-sim#949]
Hi
I am trying to run ORB_SLAM in habitat simulator. It needs some information about the camera and all I could find out about habitat camera was a projection matrix which was like [1,0,0,0;0,1,0,0;0,0,1,0;0,0,0,1] matrix which is different from what ORB_SLAM needs. It needs camera calibration and distortion information to make the calibration matrix from them. Can you please help me for finding these values? I have attached a sample file for ZED2 camera.
Thank You

[ZED2.yaml.tar.gz](https://github.com/facebookresearch/habitat-sim/files/5598863/ZED2.yaml.tar.gz)

**Comment by erikwijmans** [comment]
This may be helpful: https://github.com/facebookresearch/habitat-lab/blob/master/habitat_baselines/slambased/data/mp3d3_small1k.yaml
