### ISSUE TITLE
Error Building from source

### ISSUE THREAD

**Issue by elientumba2019** [facebookresearch/habitat-sim#970]
Hello. I am trying to build from source and get the following error. (See log file)

**Steps to reproduce** 
conda create -n habitat python=3.6 cmake=3.14.0
conda activate habitat
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
pip install -r requirements.txt
python setup.py install --with-cuda --cmake

**System**
ubuntu1~18.04
gcc 7.5.0

[log.txt](https://github.com/facebookresearch/habitat-sim/files/5682541/log.txt)

**Comment by elientumba2019** [comment]
what could be the cause and how can I fix it? Thanks

**Comment by erikwijmans** [comment]
```
fatal: not a git repository (or any parent up to mount point /media/lf216)
```

It seems like you downloaded a zip of the repo instead of cloning.  Please clone the repo instead.
