### ISSUE TITLE
Error when building from source.

### ISSUE THREAD

**Issue by elientumba2019** [facebookresearch/habitat-sim#982]
## ❓ Questions and Help
Hello i am having the following error when building from source (see log). can someone help me resolve it ?
the steps to reproduce this error are same as those in the guide on git.

[log.txt](https://github.com/facebookresearch/habitat-sim/files/5709752/log.txt)

**Comment by erikwijmans** [comment]
That is an issue with git updating the submodules.  It seems like you made changes to the submodules.  Please revert those
