### ISSUE TITLE
Skokloster castle scene dims are [-inf, -inf, -inf]

### ISSUE THREAD

**Issue by medhagitnod** [facebookresearch/habitat-sim#99]
## Steps to reproduce

  1. initialize a DemoRunner with the default settings (as found in settings.py with the skoklester castle scene)
dr = DemoRunner(default_sim_settings)
  2. call the print_semantic_scene method with the instance of the DemoRunner class
  3. Dimensions of the scene are printed to terminal as: 
<habitat_sim._ext.habitat_sim_bindings.SemanticScene object at 0x7fdf1c0c8260>
House center:[0. 0. 0.] dims:[-inf -inf -inf]

Why are the dimensions of the castle scene [-inf, -inf, -inf] if the castle scene has walls? How can one ensure that as an agent moves throughout a scene it stays within the scene itself if the dimensions beyond the room are infinite?

**Comment by erikwijmans** [comment]
The Skokloster castle scene does not have semantic annotations and the SemanticScene is only valid for scenes with semantic annotations -- Matterport3D, SUN-CG, and Replica (although we still need to add the loading code for Replica's semantic scene graph).
