### ISSUE TITLE
[CIRCLECI] Run clang-tidy on the Bullet bindings too

### ISSUE THREAD

**Issue by Skylion007** [facebookresearch/habitat-sim#991]
## 🐛 Bug

Currently, clang-tidy isn't run when the bullet bindings are enabled. We should fix that in CircelCI

## Expected behavior
Clang-tidy brings us close to full coverage. Perhaps we should build it in non-headless mode as well.

**Comment by aclegg3** [comment]
@Skylion007 still relevant?

**Comment by Skylion007** [comment]
Nope: https://github.com/facebookresearch/habitat-sim/blob/49afedddcfc7c90746bd67d236b08849ef69922d/.circleci/config.yml#L481
